### ISSUE TITLE
i18n support for Webview2

### ISSUE THREAD

**Issue by starship-jr** [tauri-apps/wry#1012]
First, thank you all for these great projects !

**Is your feature request related to a problem? Please describe**

My question follows this issue : #442 
I only tried Tauri on Windows 11 x86, and the current navigator language does not respect the system settings language.
I am currently using rustc 1.69.0 (84c898d65 2023-04-16)

I found this issue [WebView2Feedback issue](https://github.com/MicrosoftEdge/WebView2Feedback/issues/3635)
Apparently, I quote them : `Setting CoreWebView2EnvironmentOptions Language property doesn't change accept-language http header unless you delete the Preferences file or use a new userDataFolder path.`

So it seems that once we set up the prefered language, we can no longer work anymore with CoreWebView2EnvironmentOptions Language property.

However, in this issue they mention that we can still use **_ICoreWebView2EnvironmentOptions::put_AdditionalBrowserArguments_** to set the language.

**Describe the solution you'd like**

We are already using this method in wry webview2 
https://github.com/tauri-apps/wry/blob/70d8ae057c5e8b81db4aac28e5fa2dd3424b3307/src/webview/webview2/mod.rs#L128-L143

So I tried to set the --accept-lang through it 

```rust

use sys_locale::get_locale;

let locale_lang = match get_locale() {
   Some(v) => format!("--accept-lang={} ", v),
   None => "".to_string(),
};

let _ = options.SetAdditionalBrowserArguments(PCWSTR::from_raw(
   encode_wide(pl_attrs.additional_browser_args.unwrap_or_else(|| {
      format!(
         "{}--disable-features=msWebOOUI,msPdfOOUI,msSmartScreenProtection{}",
          locale_lang,
          if autoplay {
             " --autoplay-policy=no-user-gesture-required"
          } else {
             ""
          }
      )
   }))
   .as_ptr(),
));
```

I tried the multi_window example and see navigator language update correctly when I change Windows language settings.

**Would you want to assign yourself to implement this feature?**

Do you think this could be a valid approach ? 
If yes, will be glad to contribute and work through a PR

**Comment by amrbashir** [comment]
I would like to wait a bit for a while and see if https://github.com/MicrosoftEdge/WebView2Feedback/issues/3635 gets resolved. For now, do use the provided API to change the browser args.

**Comment by amrbashir** [comment]
upstream issue is fixed, closing this
