### ISSUE TITLE
wry + window-vibrancy doesn't work

### ISSUE THREAD

**Issue by rhysd** [tauri-apps/wry#1013]
**Describe the bug**

I'm trying to use [window-vibrancy](https://github.com/tauri-apps/window-vibrancy) with WebView window.

I confirmed [window-vibrancy's example](https://github.com/tauri-apps/window-vibrancy/blob/dev/examples/tao.rs) worked. Then I tried to combine the example code into wry's `hello_world` example code.

However, vibrancy looked not applied to the window.

**Steps To Reproduce**

1. Create a new Rust project with `cargo new`
2. Run `cargo add window-vibrancy`
3. Set the following source as main.rs
4. Run `cargo run`

```rust
fn main() -> wry::Result<()> {
  use window_vibrancy::*;
  use wry::{
    application::{
      event::{Event, StartCause, WindowEvent},
      event_loop::{ControlFlow, EventLoop},
      window::WindowBuilder,
    },
    webview::WebViewBuilder,
  };

  let event_loop = EventLoop::new();

  let mut builder = WindowBuilder::new()
    .with_title("Hello World")
    .with_decorations(false)
    .with_transparent(true);
  #[cfg(target_os = "windows")]
  {
    builder = builder.with_undecorated_shadow(false);
  }
  let window = builder.build(&event_loop)?;

  #[cfg(target_os = "windows")]
  window.set_undecorated_shadow(true);

  #[cfg(target_os = "windows")]
  apply_acrylic(&window, None)
    .expect("Unsupported platform! 'apply_blur' is only supported on Windows");

  #[cfg(target_os = "macos")]
  let _ = apply_vibrancy(&window, NSVisualEffectMaterial::HudWindow, None, None)
    .expect("Unsupported platform! 'apply_vibrancy' is only supported on macOS");

  let webview = WebViewBuilder::new(window)?
    .with_html("<html><body>hello, world</body></html>")?
    .with_transparent(true)
    .build()?;

  event_loop.run(move |event, _, control_flow| {
    *control_flow = ControlFlow::Wait;

    match event {
      Event::NewEvents(StartCause::Init) => println!("Wry has started!"),
      Event::WindowEvent {
        event: WindowEvent::CloseRequested,
        ..
      } => *control_flow = ControlFlow::Exit,
      _ => (),
    }
  });
}
```

**Expected behavior**

Vibrancy is applied to the launched window.

**Screenshots**

Here is a screenshot of the window:

<img width="804" alt="image" src="https://github.com/tauri-apps/wry/assets/823277/85012729-e1c6-476a-9dc9-8ff9ffc861be">

I also tried the repro with enabling DevTools. I confirmed that no background color was set to both `<html>` and `<body>`.

<img width="1005" alt="screenshot" src="https://github.com/tauri-apps/wry/assets/823277/db560dde-e5ff-436f-aff7-51cee467b0bd">

When I removed `let webview = ...` statement, I confirmed vibrancy was applied:

<img width="509" alt="image" src="https://github.com/tauri-apps/wry/assets/823277/8bb113a6-77da-4a61-8eae-818eee7e4664">

**Platform and Versions (please complete the following information):**
OS: macOS 11
Rustc: 1.72.0
wry: 70d8ae057c5e8b81db4aac28e5fa2dd3424b3307
window-vibrancy: 0.4.0

**Would you want to assign yourself to resolve this bug?**
- [ ] Yes
- [x] No

**Additional context**

Nothing.

**Comment by amrbashir** [comment]
You need to also make the `<html>` and `<body>` elements transparent.

**Comment by rhysd** [comment]
Ah, ok, I'll try `background-color: transparent`

**Comment by rhysd** [comment]
@amrbashir I tried the following but the window was still not vibrant. Did I make any mistake?

```rust
fn main() -> wry::Result<()> {
  use window_vibrancy::*;
  use wry::{
    application::{
      event::{Event, StartCause, WindowEvent},
      event_loop::{ControlFlow, EventLoop},
      window::WindowBuilder,
    },
    webview::WebViewBuilder,
  };

  let event_loop = EventLoop::new();

  let mut builder = WindowBuilder::new()
    .with_title("Hello World")
    .with_decorations(false)
    .with_transparent(true);
  #[cfg(target_os = "windows")]
  {
    builder = builder.with_undecorated_shadow(false);
  }
  let window = builder.build(&event_loop)?;

  #[cfg(target_os = "windows")]
  window.set_undecorated_shadow(true);

  #[cfg(target_os = "windows")]
  apply_acrylic(&window, None)
    .expect("Unsupported platform! 'apply_blur' is only supported on Windows");

  #[cfg(target_os = "macos")]
  let _ = apply_vibrancy(&window, NSVisualEffectMaterial::HudWindow, None, None)
    .expect("Unsupported platform! 'apply_vibrancy' is only supported on macOS");

  let webview = WebViewBuilder::new(window)?
    .with_html(
      r#"
        <html style="background-color: transparent">
            <body style="background-color: transparent">
                hello, world
            </body>
        </html>
    "#,
    )?
    .with_transparent(true)
    .build()?;

  event_loop.run(move |event, _, control_flow| {
    *control_flow = ControlFlow::Wait;

    match event {
      Event::NewEvents(StartCause::Init) => println!("Wry has started!"),
      Event::WindowEvent {
        event: WindowEvent::CloseRequested,
        ..
      } => *control_flow = ControlFlow::Exit,
      _ => (),
    }
  });
}
```

**Comment by rhysd** [comment]
In addition, the default `background-color` CSS value is `transparent`. So the elements should be transparent even if `background-color` attribute is unspecified.

https://developer.mozilla.org/en-US/docs/Web/CSS/background-color

**Comment by rhysd** [comment]
I noticed wry has `transparent` feature. Enabling it makes entire window completely transparent so it didn't help to solve this issue. With `transparent` feature enabled and applying `background-color: white; opacity: 0.8` to `<html>`, I got the following window. Opacity is applied but vibrancy doesn't look applied.

<img width="644" alt="image" src="https://github.com/tauri-apps/wry/assets/823277/5805a135-bca9-45b8-8853-7ab9c4911616">

**Comment by rhysd** [comment]
I'm not familiar with Apple's Cocoa framework, but I somewhat understood that both wry and window-vibrancy are modifying `contentView` of the window.

- https://github.com/tauri-apps/wry/blob/70d8ae057c5e8b81db4aac28e5fa2dd3424b3307/src/webview/wkwebview/mod.rs#L827
- https://github.com/tauri-apps/window-vibrancy/blob/98dc472a7f96bfba595c74b009073bd2c7b28339/src/macos.rs#L122-L135

wry does:

```
window
└── contentView ← This is created as `parent_view` and set directly with setContentView
    └── webview
```

window-vibrancy does:

```
window
└── contentView ← Existing before calling set_vibrancy
    └── blurred_view ← This is added with addSubview
```

In my example, I called `set_vibrancy` at first then I created `WebView`. If my understanding is correct, the `blurred_view` is removed from the view hierarchy by setting the `parent_view` by wry.

```diff
diff --git a/examples/hello_world.rs b/examples/hello_world.rs
index d362941..bcb9756 100644
--- a/examples/hello_world.rs
+++ b/examples/hello_world.rs
@@ -32,10 +32,6 @@ fn main() -> wry::Result<()> {
   apply_acrylic(&window, None)
     .expect("Unsupported platform! 'apply_blur' is only supported on Windows");
 
-  #[cfg(target_os = "macos")]
-  let _ = apply_vibrancy(&window, NSVisualEffectMaterial::HudWindow, None, None)
-    .expect("Unsupported platform! 'apply_vibrancy' is only supported on macOS");
-
   let webview = WebViewBuilder::new(window)?
     .with_html(
       r#"
@@ -49,6 +45,15 @@ fn main() -> wry::Result<()> {
     .with_devtools(true)
     .build()?;
 
+  #[cfg(target_os = "macos")]
+  let _ = apply_vibrancy(
+    webview.window(),
+    NSVisualEffectMaterial::HudWindow,
+    None,
+    None,
+  )
+  .expect("Unsupported platform! 'apply_vibrancy' is only supported on macOS");
+
   webview.open_devtools();
 
   event_loop.run(move |event, _, control_flow| {
```

I changed the order to create WebView instance then call `set_vibrancy`. Then the WebView was no longer rendered and vibrancy was applied. This is consistent with my understanding.

**Comment by rinsuki** [comment]
After add some changes to @rhysd's first example (create webview first, then apply vibrancy to `webview.window()`), it seems to be work (fyi: you need to activate window by click to enable vibrancy).

<img width="572" alt="image" src="https://github.com/tauri-apps/wry/assets/6533808/078712ed-1033-46d9-bf70-58db7b486802">

my `src/main.rs`:

```rust
fn main() -> wry::Result<()> {
  use window_vibrancy::*;
  use wry::{
    application::{
      event::{Event, StartCause, WindowEvent},
      event_loop::{ControlFlow, EventLoop},
      window::WindowBuilder,
    },
    webview::WebViewBuilder,
  };

  let event_loop = EventLoop::new();

  let mut builder = WindowBuilder::new()
    .with_title("Hello World")
    .with_decorations(false)
    .with_transparent(true);
  #[cfg(target_os = "windows")]
  {
    builder = builder.with_undecorated_shadow(false);
  }
  let window = builder.build(&event_loop)?;

  #[cfg(target_os = "windows")]
  window.set_undecorated_shadow(true);

  let webview = WebViewBuilder::new(window)?
    .with_html("<html><body>hello, world</body></html>")?
    .with_transparent(true)
    .build()?;

  #[cfg(target_os = "windows")]
  apply_acrylic(&window, None)
    .expect("Unsupported platform! 'apply_blur' is only supported on Windows");

  #[cfg(target_os = "macos")]
  let _ = apply_vibrancy(webview.window(), NSVisualEffectMaterial::HudWindow, None, None)
    .expect("Unsupported platform! 'apply_vibrancy' is only supported on macOS");

  event_loop.run(move |event, _, control_flow| {
    *control_flow = ControlFlow::Wait;

    match event {
      Event::NewEvents(StartCause::Init) => println!("Wry has started!"),
      Event::WindowEvent {
        event: WindowEvent::CloseRequested,
        ..
      } => *control_flow = ControlFlow::Exit,
      _ => (),
    }
  });
}
```

my `Cargo.toml`:
```
[package]
name = "sandbox_ca5ebd70539664ff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
window-vibrancy = "0.4.0"
wry = { version = "0.31.1", features = ["transparent"] }
```

**Comment by amrbashir** [comment]
thanks @rinsuki, gonna go ahead and close this then

**Comment by rhysd** [comment]
I tried @rinsuki's code and it worked well. But I'm not understanding what was the difference from my previous comment. https://github.com/tauri-apps/wry/issues/1013#issuecomment-1694333075

@rinsuki Would you explain what did you change from my previous comment?
