### ISSUE TITLE
Directories and files such as .gitignore are interpreted as HTML MIME type

### ISSUE THREAD

**Issue by WilliamVenner** [tauri-apps/wry#106]
**Describe the bug**

These lines:

```rust
let suffix = uri.split(".").last();
...
// Assume HTML when a TLD is found for eg. `wry:://tauri.studio` | `wry://hello.com`
Some(_) => Self::HTML,
```

In [`src/mimetype.rs`](https://github.com/tauri-apps/wry/blob/master/src/mimetype.rs#L40-L53) cause files such as `.gitignore` to be interpreted as HTML files.

**Steps To Reproduce**

```rust
println!("{:?}", crate::mimetype::MimeType::parse_from_uri("C:\\Users\\billy\\.gitignore_global"));
```

**Expected behavior**

I believe it should return `MimeType::OCTETSTREAM`

**Screenshots**

![image](https://user-images.githubusercontent.com/14863743/110217174-9e482380-7eaa-11eb-83e8-87e9aeeb704a.png)

**Platform and Versions (please complete the following information):**
OS: Windows
Rustc: `rustc 1.48.0 (7eac88abb 2020-11-16)`

**Would you assign yourself to resolve this bug?**
- [X] Yes
- [ ] No

**Comment by wusyong** [comment]
Hey sorry I fall back to `Pathbuf` for now because mimetype is actually a private type.
We'll have a discussion about the security on file drop handler later this week.

**Comment by wusyong** [comment]
Closing this as mime-type is still private type and I don't think we could enumerate all types.
