### ISSUE TITLE
WebView v.s. Webview

### ISSUE THREAD

**Issue by rhysd** [tauri-apps/wry#1073]
**Is your feature request related to a problem? Please describe.**

Many wry's APIs use `WebView` but a few APIs use `Webview` in their names. It would be confusing for users.

I know rust-analyzer is smart enough to help them in most cases. However, it does not help if they want to refer APIs which are not supported in the host environment. For example, when writing code on macOS, `WebviewExtUnix` does not appear in completion.

**Describe the solution you'd like**

Let's use 'WebView' consistently. Currently the following APIs will be affected:

- `WebviewExtWindows` → `WebViewExtWindows`
- `WebviewExtUnix` → `WebViewExtUnix`
- `WebviewExtMacOS` → `WebViewExtMacOS`
- `WebviewExtIOS` → `WebViewExtIOS`
- `WebviewExtAndroid` → `WebViewExtAndroid`
- `WebviewUriLoader` → `WebViewUriLoader`

**Describe alternatives you've considered**

- Considering backward compatibility of API, do not change those APIs.
- Use 'Webview' instead of 'WebView'. However changes will be bigger in this case since it renames `WebView` and `WebViewBuilder` which are widely used.

**Would you want to assign yourself to implement this feature?**
- [x] Yes
- [ ] No

**Additional context**

I haven't created a PR for this issue because I'm not sure those changes are worth breaking changes. Once I could get the consensus, I'll make a PR.

**Comment by wusyong** [comment]
Yeah I'm happy to see this move. I think I wrote those trait without noticing they had typos and we use them ever since.

**Comment by rhysd** [comment]
I created a PR #1074 for this issue since this issue got 2 upvotes.
