### ISSUE TITLE
enable the drag-and-drop permission, but still can't drag and drop files

### ISSUE THREAD

**Issue by alindas** [tauri-apps/wry#1078]
**Describe the bug**
i set 'fileDropEnabled' to true, but still can't drag and drop files. gui show not allow icon, and can not trigger the 'tauri://file-drop', 'tauri://file-drop-hover' events.

**Screenshots**

**Platform and Versions (please complete the following information):**
tauri: 1.4.0
platform: windows
nodejs: 16.18.2

**Would you want to assign yourself to resolve this bug?**
- [+] Yes
- [ ] No

**Comment by FabianLars** [comment]
https://github.com/tauri-apps/tauri/issues/8218

**Comment by alindas** [comment]
i have see something，my app runup need Administrator privileges，so when i try to drop normal file，it cant tragger 'file-drop' event。but when i try to drop some app files with administrator privileges, it works!
