### ISSUE TITLE
Support for setting the background color of the webview

### ISSUE THREAD

**Issue by geocine** [tauri-apps/wry#111]
**Is your feature request related to a problem? Please describe.**
There is no direct problem related to this feature request. But it would be good to have so that white flashes are not visible especially when your application is loading and you do not have a white background.

**Describe the solution you'd like**
Be able to set the background color of the webview

**Describe alternatives you've considered**
-

**Would you assign yourself to implement this feature?**
- [ ] Yes
- [x] No

> I wish I could help

**Additional context**
-

**Comment by nklayman** [comment]
For windows, we need [this feature](https://github.com/MicrosoftEdge/WebView2Feedback/issues/414) to become available in the webview2 crate. For linux, we just use `webview.set_background_color(&RGBA::black());`. Not sure about Mac.

**Comment by wusyong** [comment]
setting background color (with transparency) can be achieved by setting a transparent attribute and then set [this](https://github.com/tauri-apps/wry/blob/master/examples/transparent.rs#L14) in your HTML.
Windows is not available for now since it's a pre release option. We'll update it once webview 2 has a new release.

**Comment by xuchaoqian** [comment]
> setting background color (with transparency) can be achieved by setting a transparent attribute and then set [this](https://github.com/tauri-apps/wry/blob/master/examples/transparent.rs#L14) in your HTML. Windows is not available for now since it's a pre release option. We'll update it once webview 2 has a new release.

This API has released: [put_defaultbackgroundcolor](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2controller2?view=webview2-1.0.1823.32#put_defaultbackgroundcolor)
