### ISSUE TITLE
bug: fix docs.rs build

### ISSUE THREAD

**Issue by wusyong** [tauri-apps/wry#1118]
**Describe the bug**

**Steps To Reproduce**
Steps to reproduce the behavior. It **must** use wry directly instead of tauri.

**Expected behavior**

**Screenshots**

**Platform and Versions (please complete the following information):**
OS:
Rustc:

**Would you want to assign yourself to resolve this bug?**
- [ ] Yes
- [ ] No

**Additional context**

**Comment by pewsheen** [comment]
It shall pass on the next release.

**Comment by pewsheen** [comment]
Looks like it passed, closing this issue.
