### ISSUE TITLE
[Feature] Text find in page

### ISSUE THREAD

**Issue by nawbc** [tauri-apps/wry#1126]
We can use `window.find()` as a workaround, but that feature is non-standard. So it's possible to support something like
Electron `contents.findInPage`  [Detail](https://www.electronjs.org/docs/latest/api/web-contents#contentsfindinpagetext-options)

**Comment by FabianLars** [comment]
Duplicate of https://github.com/tauri-apps/wry/issues/585. Thanks for the request :)
