### ISSUE TITLE
Computationally Secure RANDOM

### ISSUE THREAD

**Issue by nothingismagick** [tauri-apps/wry#113]
**Describe the bug**
https://github.com/tauri-apps/wry/blob/master/src/webview/mod.rs#L165

Random is NOT computationally secure. I am not sure what the implications are of it here. Are we are worried about it being hijacked? Since this is about message ID's I am actually worried about ID hijacking at the boundary. If you agree, we should use `Crypto.random` as shown below, or leverage some UUID (@lucasfernog - you wrote something like that for tauri... right?) 

```
var array = new Uint32Array(10);
window.crypto.getRandomValues(array);
```

**Would you assign yourself to resolve this bug?**
- [x] MAYBE

**Comment by lucasfernog** [comment]
We have uuid at Tauri but it doesn't use crypto random - we should.

**Comment by nothingismagick** [comment]
I think the problem previously is that the webview in alpha Tauri wasn't in a secure context, so we `window.crypto` was `false`. This *should* be fixed with wry and custom protocol.

**Comment by nothingismagick** [comment]
We still need to fix this, definitely before the audit.

https://github.com/tauri-apps/wry/blob/22f96f3b58c7dcbd931da151d2bba2c32b69cbf2/src/webview/mod.rs#L186
