### ISSUE TITLE
Window getters

### ISSUE THREAD

**Issue by amrbashir** [tauri-apps/wry#116]
**Is your feature request related to a problem? Please describe.**
Add getters on `WindowProxy`

**Describe alternatives you've considered**
Keep track of an `Attributes` struct and update it whenever a setter method is called but that won't work properly for maximized, minimized and more.

**Would you assign yourself to implement this feature?**
- [ ] Yes
- [ ] No

**Additional context**
Most of the getters can be implemented for gkt-backend but not winit-backend
I made a table to list what is possible and what is not 

|        getters       | winit |  gtk  |
|:--------------------:|:-----:|:-----:|
|       resizable      |   no  |  yes  |
|         title        |   no  |  yes  |
|       maximized      |  yes  |  yes  |
|       minimized      |   no  | maybe(2) |
|        visible       |   no  |  yes  |
|      decoration      |   no  |  yes  |
|     always_on_top    |   no  | maybe(2)|
|     width, height    |  yes  |  yes  |
| min/max width/height |   no  | maybe(2)|
|         x , y        |  yes  |  yes  |
|      fullscreen      |  yes  | maybe(2)|
|     skip_taskbar     |   no  |  yes  |
|         url(3)          |               |
|        icon(4)         |               |
|     transparent(4)      |               |
|initialization_scripts(4)|               |

2. gtk docs are confusing and I am not sure if the getter is possible.
3. `url` is possible I guess but not sure if it's worth it.
4. I think `transparent`, `icon`, `initialization_scripts`, and `skip_taskbar` don't need getters imo.

**Comment by wusyong** [comment]
We do can add it to the struct field but this will bloat up the size of many types.
`Attributes` is one of the biggest types in this crate. And since it has Clone trait.
Maybe we just let users to handle this.

**Comment by amrbashir** [comment]
The drawback with mutating an Attribute struct rather than querying the OS, is that users can't track changes  to the  window state (ie maximized, minimzed, size changed) unless it is changed programatically.

**Comment by wusyong** [comment]
Sorry I misread the description in your top comments.
Yeah I think getters can be achieved by adding another channel but reversed (sender on `Application`, receiver on `WindowProxy`)

**Comment by wusyong** [comment]
I see. Maybe we could introduce some that are already available on both winit and gtk just like what your list above.

**Comment by wusyong** [comment]
Close this because we use new application api and those waiting to be implemented are listed in #165
