### ISSUE TITLE
Incorrect and incosistent window size with multiwebview

### ISSUE THREAD

**Issue by thewh1teagle** [tauri-apps/wry#1172]
**Describe the bug**

**Steps To Reproduce**
```console
git clone https://github.com/tauri-apps/wry
cd wry
cargo run --example multiwebview
```

**Expected behavior**
The sizes should be of the whole window and same as it is in MacOS

**Screenshots**

## Windows (incorrect size)

<img width="600" alt="image" src="https://github.com/tauri-apps/wry/assets/61390950/b71a6333-c462-4606-a179-b439afe227d6">

## MacOS (correct size)

<img width="600" alt="image" src="https://github.com/tauri-apps/wry/assets/61390950/48987d97-daee-49b8-b135-2709f700ac39">

**Platform and Versions (please complete the following information):**
```console
OS: Windows 11
Rustc: 
cargo 1.75.0 (1d8b05cdd 2023-11-20)
rustc 1.75.0 (82e1608df 2023-12-21)
```

**Additional context**
It works well on `MacOS`

**Comment by amrbashir** [comment]
Thanks for reporting, I am aware of that issue and I am working on fixing it before next release.

**Comment by thewh1teagle** [comment]
You may be already aware of, but looks like the problem is that in windows the expected size is PysicalSize but in MacOS the expected size is LogicalSize (calculated with scale factor by default in multiwebview example)
So in windows, by removing the `to_logical` in both window setup and resize handler fixes it.

**Comment by amrbashir** [comment]
Yeah, I think we will need to pick one or another and do the conversions internally.
