### ISSUE TITLE
Custom protocol in `wry` on Windows

### ISSUE THREAD

**Issue by JohnScience** [tauri-apps/wry#1174]
**Describe the bug**
Hi, I'm trying to understand how to add and access custom protocols with `wry` on Windows. I want to use them to more efficiently reimplement `tauri::command` by using a binary protocol for data transfer.

I seem to have grasped how to implement and add a protocol:

```rust
fn custom_protocol(
    _req: wry::http::request::Request<Vec<u8>>,
) -> wry::http::response::Response<Cow<'static, [u8]>> {
    let resp = wry::http::response::Response::builder()
        .status(wry::http::status::StatusCode::OK)
        .header(
            wry::http::header::ACCESS_CONTROL_ALLOW_ORIGIN,
            wry::http::HeaderValue::from_static("*"),
        )
        .body(Cow::<'static, [u8]>::Borrowed(b"Hello, world!"))
        .unwrap();

    resp
}

fn main() {

  // ...
  let _webview = WebViewBuilder::new(&window)
        .with_url(&format!("http://localhost:{port}/"))?
        .with_custom_protocol("my_proto".to_string(), custom_protocol)
        .build()?;
  // ...

}
```

However, I'm struggling to access the protocol data (on Windows).

I opened the console in the dev tools of the `wry` app (on Windows) and tried the following

```
function reqListener () {
  console.log(this.responseText);
}

var oReq = new XMLHttpRequest();
oReq.addEventListener("load", reqListener);
oReq.open("GET", "http://my_proto.");
oReq.send();
```

Error:

```
GET http://my_proto./ net::ERR_NAME_NOT_RESOLVED
```

---

Doing this with an initialization script (to prevent issues similar to <https://github.com/tauri-apps/wry/issues/949>),

```rust
.with_initialization_script(
            r#"
            (function () {
                function reqListener () {
                    console.log(this.responseText);
                  }
                  
                  var oReq = new XMLHttpRequest();
                  oReq.addEventListener("load", reqListener);
                  oReq.open("GET", "http://my_proto./");
                  oReq.send();
            })();
            "#,
        )
```

didn't help either.

Originally, this was [asked as a question](https://discord.com/channels/616186924390023171/1208617755482398771/1208617755482398771) in the Discord server of Tauri.

**Steps To Reproduce**
...

**Expected behavior**
That "Hello world" would be printed.

**Screenshots**

<img width="759" alt="Capture" src="https://github.com/tauri-apps/wry/assets/16991108/2cff8270-86e3-44f6-b5cb-4c5efda74e02">

![Screenshot (561)](https://github.com/tauri-apps/wry/assets/16991108/37af8089-791e-4f55-9a0f-f07fc6fa25cc)

**Platform and Versions (please complete the following information):**
OS: Windows
Rustc: `rustc 1.75.0 (82e1608df 2023-12-21)`

**Additional context**

**Comment by amrbashir** [comment]
The problem lies in the underscore in your protocol name, it is not a valid scheme for a URI, see https://datatracker.ietf.org/doc/html/rfc3986#section-3.1.

The error is not very descriptive, I am refactoring a few parts of WRY and hopefully the next release will include the proper error why a request failed before reaching your custom protocol handler.

**Comment by JohnScience** [comment]
@amrbashir I tried it without the underscore (`myproto` instead of `my_proto`) and it didn't work either.

**Comment by amrbashir** [comment]
Here is a full working example of your example
```rs
use std::borrow::Cow;

use tao::{
  event::{Event, WindowEvent},
  event_loop::{ControlFlow, EventLoop},
  window::WindowBuilder,
};
use wry::WebViewBuilder;

fn main() -> wry::Result<()> {
  let event_loop = EventLoop::new();
  let window = WindowBuilder::new().build(&event_loop).unwrap();

  #[cfg(any(
    target_os = "windows",
    target_os = "macos",
    target_os = "ios",
    target_os = "android"
  ))]
  let builder = WebViewBuilder::new(&window);

  #[cfg(not(any(
    target_os = "windows",
    target_os = "macos",
    target_os = "ios",
    target_os = "android"
  )))]
  let builder = {
    use tao::platform::unix::WindowExtUnix;
    use wry::WebViewBuilderExtUnix;
    let vbox = window.default_vbox().unwrap();
    WebViewBuilder::new_gtk(vbox)
  };

  fn custom_protocol(
    _req: wry::http::request::Request<Vec<u8>>,
  ) -> wry::http::response::Response<Cow<'static, [u8]>> {
    let resp = wry::http::response::Response::builder()
      .status(wry::http::status::StatusCode::OK)
      .header(
        wry::http::header::ACCESS_CONTROL_ALLOW_ORIGIN,
        wry::http::HeaderValue::from_static("*"),
      )
      .body(Cow::<'static, [u8]>::Borrowed(b"Hello, world!"))
      .unwrap();

    resp
  }

  let _webview = builder
    .with_url("myproto://localhost")
    .with_custom_protocol("myproto".to_string(), custom_protocol)
    .with_initialization_script(
      r#"
    (function () {
        function reqListener () {
            console.log(this.responseText);
          }
          
          var oReq = new XMLHttpRequest();
          oReq.addEventListener("load", reqListener);
          oReq.open("GET", "http://myproto.localhost/");
          oReq.send();
    })();
    "#,
    )
    .build()?;

  event_loop.run(move |event, _, control_flow| {
    *control_flow = ControlFlow::Wait;

    if let Event::WindowEvent {
      event: WindowEvent::CloseRequested,
      ..
    } = event
    {
      *control_flow = ControlFlow::Exit
    }
  });
}

```

Notice `my_proto` is now `myproto`, also note the request is made to `http://myproto.localhost`

**Comment by JohnScience** [comment]
> Here is a full working example of your example
> 
> ```rust
> use std::borrow::Cow;
> 
> use tao::{
>   event::{Event, WindowEvent},
>   event_loop::{ControlFlow, EventLoop},
>   window::WindowBuilder,
> };
> use wry::WebViewBuilder;
> 
> fn main() -> wry::Result<()> {
>   let event_loop = EventLoop::new();
>   let window = WindowBuilder::new().build(&event_loop).unwrap();
> 
>   #[cfg(any(
>     target_os = "windows",
>     target_os = "macos",
>     target_os = "ios",
>     target_os = "android"
>   ))]
>   let builder = WebViewBuilder::new(&window);
> 
>   #[cfg(not(any(
>     target_os = "windows",
>     target_os = "macos",
>     target_os = "ios",
>     target_os = "android"
>   )))]
>   let builder = {
>     use tao::platform::unix::WindowExtUnix;
>     use wry::WebViewBuilderExtUnix;
>     let vbox = window.default_vbox().unwrap();
>     WebViewBuilder::new_gtk(vbox)
>   };
> 
>   fn custom_protocol(
>     _req: wry::http::request::Request<Vec<u8>>,
>   ) -> wry::http::response::Response<Cow<'static, [u8]>> {
>     let resp = wry::http::response::Response::builder()
>       .status(wry::http::status::StatusCode::OK)
>       .header(
>         wry::http::header::ACCESS_CONTROL_ALLOW_ORIGIN,
>         wry::http::HeaderValue::from_static("*"),
>       )
>       .body(Cow::<'static, [u8]>::Borrowed(b"Hello, world!"))
>       .unwrap();
> 
>     resp
>   }
> 
>   let _webview = builder
>     .with_url("myproto://localhost")
>     .with_custom_protocol("myproto".to_string(), custom_protocol)
>     .with_initialization_script(
>       r#"
>     (function () {
>         function reqListener () {
>             console.log(this.responseText);
>           }
>           
>           var oReq = new XMLHttpRequest();
>           oReq.addEventListener("load", reqListener);
>           oReq.open("GET", "http://myproto.localhost/");
>           oReq.send();
>     })();
>     "#,
>     )
>     .build()?;
> 
>   event_loop.run(move |event, _, control_flow| {
>     *control_flow = ControlFlow::Wait;
> 
>     if let Event::WindowEvent {
>       event: WindowEvent::CloseRequested,
>       ..
>     } = event
>     {
>       *control_flow = ControlFlow::Exit
>     }
>   });
> }
> ```
> 
> Notice `my_proto` is now `myproto`, also note the request is made to `http://myproto.localhost`

The key part was using `http://myproto.localhost` instead of a path.

Thank you!
