### ISSUE TITLE
Windows User Data for bundled Application

### ISSUE THREAD

**Issue by lemarier** [tauri-apps/wry#121]
**Describe the bug**
The application does not work when we bundle the application in Program Files as Webview2 tries to create the cache at `<ExePath>.Webview2` as Program Files is protected the webview panic.

**Steps To Reproduce**

Put a compiled application inside `Program Files` and try to launch.

**Expected behavior**
Webview should open.

**Screenshots**
N/A

**Platform and Versions (please complete the following information):**
OS: Windows
Rustc: N/A

**Would you assign yourself to resolve this bug?**
- [x] Yes
- [ ] No

**Comment by Dalan94** [comment]
I also have this problem. How did you manage to solve it? I can't find an API to set the user data folder ?

**Comment by FabianLars** [comment]
You set that via the WebviewContext's new method: https://docs.rs/wry/latest/x86_64-pc-windows-msvc/wry/webview/struct.WebContext.html#method.new and then give that context to the webviewbuilder: https://docs.rs/wry/latest/x86_64-pc-windows-msvc/wry/webview/struct.WebViewBuilder.html#method.with_web_context

**Comment by Dalan94** [comment]
Ok, thanks !
