### ISSUE TITLE
Windows 11 Transparency goes through wgpu example

### ISSUE THREAD

**Issue by nicholasc** [tauri-apps/wry#1212]
I was looking to play around with the latest changes in wry to explore potentially using it with Bevy.
So I decided to run the wgpu example and noticed some strange behavior on Windows 11.

Basically, I am getting the same behavior as #1026. I need to resize over the bounds of the webview to get correct transparency, but when I do, the wry viewport is actually letting through the content behind the window and not the actual triangle being rendered by wgpu.

I tried using `with_undecorated_shadow(false)` on window creation like mentioned in #1026 but it does nothing (even if I reactivate it afterwards).

Is there a feature I am not using to run the example properly or is this a bug?

https://github.com/tauri-apps/wry/assets/2378304/4ff6d1f5-cb95-4b27-a823-506ad00bf7a2

**Comment by amrbashir** [comment]
By default winit adds `WS_CLIPCHILDREN` by default to its windows and you need this unreleased API to remove it https://github.com/rust-windowing/winit/blob/4cd6877e8e19e7e1ba957a409394dca1af4afcdd/src/platform/windows.rs#L369-L370, once `WS_CLIPCHILDREN` window style is removed, it should show the content behind it on the window and not go through.

**Comment by nicholasc** [comment]
Ok, I'll try and test this.

So this is not going to be fixed until winit's new trait-based API is released and wry has migrated to it.

**Comment by amrbashir** [comment]
There is no migration needed on our side.

**Comment by nicholasc** [comment]
Oh right. My mistake, I was thinking about tao but wry is window agnostic.
