### ISSUE TITLE
Support WebView2 non client area APIs

### ISSUE THREAD

**Issue by Legend-Master** [tauri-apps/wry#1245]
Add support for WebView2 non client area APIs

> https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes/?tabs=win32cpp#10242047

**Comment by amrbashir** [comment]
The linked API is for composition API which we can't use atm because it doesn't support Windows 7

**Comment by amrbashir** [comment]
Also these APIs exist so as a way to forward `WM_NCHITTEST` to Webview2 not the other way around.

**Comment by Legend-Master** [comment]
Can we at least support the setting that enables `app-region` css property?

> https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2settings9?view=webview2-1.0.2478.35

**Comment by amrbashir** [comment]
yeah sure, we can enable it by default
