### ISSUE TITLE
Expose gtk window

### ISSUE THREAD

**Issue by andrewbaxter** [tauri-apps/wry#1253]
**Is your feature request related to a problem? Please describe.**
I need to use the wl-layer-shell wayland extensions, and the `gtk-layer-shell` project provides methods for doing that on a raw gtk window.

The gtk window within tao's `Window` is private.

Alternatively I considered making my own window, but the `app` inside `EventLoop` is also private, and afaict that wouldn't work because the window needs to access internal methods to connect the window to the event loop.

**Describe the solution you'd like**
I think the simplest would be to provide a method to get the gtk window from the `Window` object.

**Describe alternatives you've considered**
I also looked at `winit`, which also uses gtk in the backend I think.  It's possible that they'd be amenable to changes to expose the gtk window or add the layer-shell methods directly.

**Comment by amrbashir** [comment]
Use https://docs.rs/tao/latest/tao/window/struct.Window.html#method.gtk_window

**Comment by andrewbaxter** [comment]
Oh thanks! I'm not sure how I missed that, I spent a good bit of time digging around.
