### ISSUE TITLE
Transparent WebView not working on MacOS

### ISSUE THREAD

**Issue by TheKnarf** [tauri-apps/wry#1266]
**Describe the bug**
Transparent WebView not working on MacOS

**Steps To Reproduce**
- Clone the wry example
- Change line 61 of `examples/transparent.rs`:

```
diff --git a/examples/transparent.rs b/examples/transparent.rs
index 96b26dd..9960ff9 100644
--- a/examples/transparent.rs
+++ b/examples/transparent.rs
@@ -58,7 +58,7 @@ fn main() -> wry::Result<()> {
     // And the last is in html.
     .with_html(
       r#"<html>
-          <body style="background-color:rgba(87,87,87,0.5);"></body>
+          <body style="background-color:rgba(87,87,87,0);"></body>
           <script>
             window.onload = function() {
               document.body.innerText = `hello, ${navigator.userAgent}`;
```
- Run the example (on MacOS) `cargo run --example transparent` and observe that there is no transparency.

**Expected behavior**
For the background to be transparent

**Screenshots**
![Screenshot 2024-05-15 at 14 48 42](https://github.com/tauri-apps/wry/assets/213777/64aa62e1-a8cc-4d9d-8d0f-3255c9655a3a)

**Platform and Versions (please complete the following information):**
OS: MacOS Sonoma 14.4.1
Rustc: rustc 1.77.1 (7cf61ebde 2024-03-27)

**Additional context**
N/A

**Comment by FabianLars** [comment]
Try running it like this `cargo run --example transparent --features transparent`
On macOS transparency uses private apis so it's not enabled by default.

Also, i would expect the compiler to complain about this, weird 🤔
