### ISSUE TITLE
[Windows] Undecorated window only resizable at the top on Windows 10

### ISSUE THREAD

**Issue by floriansbh** [tauri-apps/wry#1273]
**Describe the bug**
Window created with tao `.with_decorations(false)` only resizable at the top when using it to create a WebView with wry on Windows 10. There is also a 1px gray border only at the top which disapears when losing focus to the window. I guess it's a bug in wry as the tao Window is resizable before it's being used to create the WebView but not entirely sure tho.

**Steps To Reproduce**
Just run this minimal example using tao `0.28.0` and wry `0.40.0` on Windows 10 (it doesn't really matter what content the webview contains as far as I know):
```rs
use tao::event_loop::EventLoop;
use tao::window::WindowBuilder;
use wry::WebViewBuilder;

fn main() {
    let event_loop = EventLoop::new();
    let window = WindowBuilder::new()
        .with_decorations(false)
        .build(&event_loop).unwrap();

    let webview = WebViewBuilder::new(&window)
        .with_background_color((0, 0, 0, 1))
        .build()
        .unwrap();

    event_loop.run(|_, _, _| {});
}
```

**Expected behavior**
The window (when used to create a wry WebView) should be resizable on all edges and not just at the top. The 1px gray border should also not be there when disabling decorations.

**Screenshots**
![image](https://github.com/tauri-apps/wry/assets/79258644/57a20d40-8c81-4f07-bf8d-604cd6d3c9a0)

**Platform and Versions (please complete the following information):**
OS: Windows 10
Rustc: I'm on 1.79.0-nightly but I think it doesn't really matter

**Additional context**
This is also an issue in tauri v2.

**Comment by amrbashir** [comment]
When the webview is added to a window, it prevents click from reaching the window surface and thus can't resize the window, you will need to implement a resizing logic yourself, see https://github.com/tauri-apps/wry/blob/dev/examples/custom_titlebar.rs for an example

**Comment by floriansbh** [comment]
Makes sense, thanks for explaining it. I don't necessarily think that this should be the default behavior in tauri v2 tho as most people using tauri probably don't want to implement their custom resizing logic to get a good app experience. Also, do you know what's up with the 1px gray border at the top? Is it possible to remove it somehow?

**Comment by amrbashir** [comment]
>  I don't necessarily think that this should be the default behavior in tauri v2 tho as most people using tauri probably don't want to implement their custom resizing logic to get a good app experience.

Absolutely, this just for WRY. We implemented a similar logic for Tauri v2

**Comment by amrbashir** [comment]
> Also, do you know what's up with the 1px gray border at the top? Is it possible to remove it somehow?

Probably because of the shadows, try setting `.with_undecorated_shadow(false)` to the window
