### ISSUE TITLE
Better error message for invalid custom scheme name on webkit

### ISSUE THREAD

**Issue by ottomated** [tauri-apps/wry#1295]
**Is your feature request related to a problem? Please describe.**

When registering an invalid scheme like so `.register_asynchronous_uri_scheme_protocol("in_valid", ...)`, the error (on macos) is:
```
thread 'main' panicked at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wry-0.40.1/src/wkwebview/mod.rs:403:18:
Uncaught exception <NSException: 0x149f0c280>
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
libc++abi: terminating due to uncaught foreign exception
```

**Describe the solution you'd like**
Either the scheme name should be validated on the Rust end beforehand or the error from webkit should be handled better.

**Additional context**
Tested on tauri 2.0.0-beta

**Comment by pewsheen** [comment]
Thanks for the report!
Currently, the `objc` crate we are using can't tell which `NSException` it is, so we don't know if the thrown exception is either the scheme name is invalid, or it's already been registered. Checking the name before using it looks more promising for now.

**Comment by ottomated** [comment]
Honestly, even `The schema "in_valid" is invalid or already registered` would be enough in my opinion. The issue right now is that it doesn't point to scheme registration at all
