### ISSUE TITLE
Add an option to keep the event loop alive even if the last window is closed

### ISSUE THREAD

**Issue by hediet** [tauri-apps/wry#130]
WRY is amazing! Thanks for creating it - I think it has a very bright future ahead!

**Is your feature request related to a problem? Please describe.**
I'd like to create an RPC server that spawns windows.
However, the event loop is terminated when the last window is closed, even though the RPC server is still active and might spawn a new window in the future.

**Describe the solution you'd like**
Please make it configurable if the event loop should terminate when last window closes.

**Describe alternatives you've considered**
Maybe the event loop could be put into an outer loop, so that it is restarted whenever it terminates. However, this invalidates the app proxy and is a very hacky solution.

**Would you assign yourself to implement this feature?**
- [x] Yes
- [ ] No

**Comment by wusyong** [comment]
One workaround is creating a hidden window to keep the event loop. This is also how Windows creates pop-up windows without showing on the taskbar. This is less hacky imho.

Otherwise, we could add another field in `Attribute` for this option.

**Comment by hediet** [comment]
Oh, of course! I completely forgot about that option. I hope this hidden window won't take much resources though.

**Comment by wusyong** [comment]
Close this because we use the winit interface as application now. Users can decide whether to end by specifying control flow to `ControlFlow::Exit` themselves.
