### ISSUE TITLE
Text double click behavior different from browser

### ISSUE THREAD

**Issue by nooblyf** [tauri-apps/wry#1305]
**Describe the bug**
When i double click a text in an input on a web browser, the selection breaks off at period. But when i do it in the app it selects the whole text till slash. Is there a way to imitate the text selection behavior of browser on the app?

Here's how it is on the browser (same app)
https://github.com/tauri-apps/wry/assets/54323745/4e715ee2-9cca-46f7-b217-07bfe4982110

Here's what happens in the app
https://github.com/tauri-apps/wry/assets/54323745/32805a48-0d06-4b85-99ab-ebff32c41990

**Steps To Reproduce**
- Just have an input box, write a text having period.
- Open the same app in browser and notice the double click behavior difference

**Expected behavior**
I was expecting it to behave the same

**Screenshots**
Added screen recording above

**Platform and Versions (please complete the following information):**
OS: MacOS Sonoma 14.5
Rustc: 1.78.0
Tauri: 2.0.0-beta.22

I believe this has to do with the webview that's why i opened the issue here instead of [tauri](https://github.com/tauri-apps/tauri)

**Comment by FabianLars** [comment]
Which browser(s) did you test this in? Did you also check Safari? That's the closest thing to tauri's webview so if it behaves the same it's a general webkit thing and not our fault.

**Comment by nooblyf** [comment]
I see, yeah Safari is the same as app but Firefox and Chrome are different. Thanks!
