### ISSUE TITLE
Error: UnsupportedWindowHandle on startup / WaylandWindowHandle unhandled

### ISSUE THREAD

**Issue by flokli** [tauri-apps/wry#1314]
**Describe the bug**
I'm running an app using a `WebViewBuilder`, and it immediately crashes on startup with `Error: UnsupportedWindowHandle`

Further inspection shows this is thrown at https://github.com/tauri-apps/wry/blob/93eddc31df613cd42688e85f434c6abde9c1250b/src/webkitgtk/mod.rs#L113.

I patched in a `eprintln!("{h:?}");`, the handle type I get back is `Wayland(WaylandWindowHandle { surface: 0x55fd504c0950 })`.

**Steps To Reproduce**
Run https://github.com/VanuPhantom/fossbeamer in a gnome-shell session using wayland.

**Expected behavior**
The program does run.

**Platform and Versions (please complete the following information):**
OS: NixOS
Rustc: `1.78.0`

**Comment by flokli** [comment]
I did get further running with `GDK_BACKEND=x11` env var being set, to force it into Xwayland, but it's not properly rendering there either - I get a grey background without a webview. The cursor does change between pointer and text selection, so I assume it does render somewhere, it's just invisible.

**Comment by amrbashir** [comment]
The error is correct, `WaylandWindowHandle` is not supported because we can't inject a gtk widget into it.

**Comment by flokli** [comment]
> The error is correct, `WaylandWindowHandle` is not supported because we can't inject a gtk widget into it.

https://blogs.igalia.com/itoral/2013/12/11/webkitgtk-2013-hackfest-on-the-road-to-webkit2-wayland-support-in-webkitgtk/ (from 2014) does mention some strategies on how to deal with webkit and wayland back then, and https://blogs.igalia.com/itoral/2014/01/17/webkitgtk-wayland-progress/ initial work on the approach. I kept reading, and https://bugs.webkit.org/show_bug.cgi?id=115803 ended up being merged in 2016: https://trac.webkit.org/changeset/205116/webkit. Considering things like epiphany support rendering on wayland, I'd be surprised it's still not possible to do this.

Did you read my comment on `GDK_BACKEND=x11`?

> I did get further running with GDK_BACKEND=x11 env var being set, to force it into Xwayland, but it's not properly rendering there either - I get a grey background without a webview. The cursor does change between pointer and text selection, so I assume it does render somewhere, it's just invisible.

Is it expected for rendering to be broken (invisible, but text selectable and visible while dragging)  even when setting `GDK_BACKEND=x11`?

And wouldn't it make sense for wry to give some more documentation it's not planning to support wayland, and give workarounds for people running on wayland?

**Comment by amrbashir** [comment]
I skimmed over the links you posted, and it seems unrelated. The error you're seeing here is because you're trying to use `WebviewBuilder::new` which tries to first embed a gtk window in the raw window handle you passed (this is not supported), secondly, initiate a webkit2gtk widget inside it. 

If you want wayland support, you can use [`WebviewBuilder::new_gtk`](https://docs.rs/wry/latest/wry/trait.WebViewBuilderExtUnix.html#tymethod.new_gtk) which supports X11 and Wayland.

See these examples:
- https://github.com/tauri-apps/wry/blob/dev/examples/simple.rs
- https://github.com/tauri-apps/wry/blob/dev/examples/gtk_multiwebview.rs

**Comment by flokli** [comment]
Indeed, that worked! Thanks!
