### ISSUE TITLE
Delay when processing javascript messages sent from the backend on Linux/GTK

### ISSUE THREAD

**Issue by aschey** [tauri-apps/wry#132]
**Describe the bug**
This bug occurs on the latest `dev` branch. I'm sending in a stream of `evaluate_script` commands into Wry as the backend listens to events from an external source. On the Winit backend this works perfectly, but on GTK these events are delayed in making it to the browser unless the user is actively engaged with the browser, such as clicking on something or moving their mouse. This happens because of the call to ` gtk::main_iteration()` on the main loop used by `src/application/gtkrs.rs`. `gtk::main_iteration()` is a blocking call, so once one iteration of the loop completes, no more messages sent to `self.event_loop_proxy_rx` will be processed until GTK thinks it needs to run the next iteration. If the user isn't actively using the browser, it appears GTK doesn't think it needs to update very often and only runs the next loop roughly once every second. As a result, every javascript callback sent into the queue gets batch executed roughly once per second instead of in real time.

**Steps To Reproduce**
I've created [an example here](https://github.com/aschey/wry/blob/server-push/examples/server_push.rs) that demonstrates this behavior. On Windows it behaves as expected, but on Linux it demonstrates the processing delay. The backend sends a counter increment to the UI every 500 milliseconds, but the UI only updates every second, so you should only see every other number displayed on the UI unless you focus on the window and start moving your mouse, then the UI should begin to update as expected. If you change the interval to something smaller, the batch delay becomes more apparent.

**Expected behavior**
I should be able to push events to the UI from the backend without user intervention and see the UI update without major processing delay.

**Platform and Versions (please complete the following information):**
OS: Arch Linux
Rustc: 1.51

**Would you assign yourself to resolve this bug?**
- [x] Yes
- [ ] No

If I swap the call to `gtk::main_iteration()` with the nonblocking version `gtk::main_iteration_do(false)`, the code begins to process messages quickly and behave as expected, but now the entire loop is nonblocking and eats up a large amount of CPU, which is not great. The most obvious solution to me is to have the event loop for `self.event_loop_proxy_rx` run in a separate thread so it can process messages without waiting for gtk's event loop, however it appears that the gtk objects used in `self.webviews` are not threadsafe, so the thread that handles the event loop will also need complete ownership of the webviews.

I'd be happy to take a stab at this, but I'd like some input on my thoughts above as well as any other potential solutions first. Thanks!

**Comment by wusyong** [comment]
Thanks for the issue! It looks like `gtk::main_iteration()` does delay around one second if there's no gtk event.
We could use `gtk::events_pending` to check if we should iterate the gtk process.

```rust
if gtk::events_pending() {
    gtk::main_iteration();
} else {
    std::thread::sleep(ten_milliseconds_maybe);
}
``` 
I could update it right away. But if you are interested in opening a PR, feel free to contribute :)

**Comment by aschey** [comment]
Thanks for tooking a look at this! I tried out that suggestion and it worked great. I thought it might be nice to try out other approaches that could avoid sleeping on the main loop, so I poked around the gtk-rs docs a bit and found [spawn_local](https://gtk-rs.org/docs/glib/struct.MainContext.html#method.spawn_local), which lets you spawn a future on the main thread that gets executed concurrently. With this approach, the events need to get sent through an async channel instead of stdlib's mpsc (I picked the [async_channel](https://docs.rs/async-channel/1.6.1/async_channel/) crate because it doesn't require the `try_send` method to obtain a mutable reference which makes things much easier). 

I'm new to gtk-rs so I'm not too familiar with how it works, but it looks like it has it's own async executor so this doesn't require a dependency to tokio or async-std. After messing with it a bit, the difference in resource usage looks negligible, but now we can use the original `gtk::main_iteration()` on the main loop without sleeping. I'd be happy to PR this if you're okay with including async code, or I can make a PR for your original idea if you'd prefer that.

**Comment by wusyong** [comment]
We use tokio in the main tauri crate. Tokio usually will panic if it finds other runtimes are running.
But feel free to open a PR! I'll test it if it can work seamlessly.

**Comment by lucasfernog** [comment]
I can test it if wry needs to use tokio. I think it could work but we might need to make some changes downstream.

**Comment by aschey** [comment]
Yes, good point. I was worried about that too so I created two test apps using both  tokio and async-std and verified that I could still spawn tasks. I also pointed Tauri to my local copy and tested it that way, and the async code there seemed to work okay from what I could tell. Definitely let me know if I missed anything. I'll try to clean it up and get the PR together soon.
