### ISSUE TITLE
WebView is not visible on AppKit window from Godot

### ISSUE THREAD

**Issue by doceazedo** [tauri-apps/wry#1335]
**Describe the bug**
In a Godot extension (GDExtension) made with Rust, creating a WebViewBuilder with `::new()` makes the window dark gray (left screenshot), and using `::new_as_child()` does not show anything (right screenshot):

| **`::new()`**  | **`::new_as_child()`** |
|---|---|
| ![image](https://github.com/user-attachments/assets/12b4af53-524e-4d4e-a735-51fb6f09e943) | ![image](https://github.com/user-attachments/assets/7c97bee9-9f2d-412e-bdc9-3df3b0147693) |

Devtools works just fine on both cases.

Note that on the right screenshot, the game is rendered fine but the webview is not. On left screenshot, not even the game is rendered, only a dark gray screen, which i don't *think* comes from Godot as the clear background color for the game is that dark blue seen on the other screenshot. It also doesn't seem to be a "blank" screen, as the system is in light mode and the webview background color is red, so I'm not sure where this solid color comes from.

I suspect it might have something to do with `NSView` layer ordering or something like that, but I'm not sure how to debug `NSView`. I'm currently downloading Windows to test the behavior there.

**Steps To Reproduce**
Create a GDExtension that returns the window view pointer:
```rs
struct GodotWindow;

impl HasWindowHandle for GodotWindow {
    fn window_handle(&self) -> Result<WindowHandle<'_>, HandleError> {
        let display_server = DisplayServer::singleton();
        let window_handle = display_server.window_get_native_handle(HandleType::WINDOW_VIEW);
        unsafe {
            Ok(WindowHandle::borrow_raw(
                RawWindowHandle::AppKit(AppKitWindowHandle::new({
                    assert!(is_main_thread(), "can only access AppKit handles on the main thread");
                    let ptr: *mut c_void = transmute(window_handle);
                    NonNull::new(ptr).expect("Id<T> should never be null")
                }))
            ))
        }
    }
}
```

Then create the webview:
```rs
impl INode for WebView {
    // ...

    fn ready(&mut self) {
        let window = GodotWindow;
        let webview = WebViewBuilder::new_as_child(&window)
            .with_url("https://example.com")
            .with_background_color(RGBA::from((0, 255, 0, 255)))
            .with_devtools(true)
            .build()
            .unwrap();

        webview.open_devtools();
    }
}
```

_Alternatively, here's a repo to reproduce this error: https://github.com/doceazedo/godot_wry_

Add the WebView node to a Godot scene and start the game.

**Expected behavior**
The webview is visible

**Platform and Versions (please complete the following information):**
OS: macOS 14.5 23F79 arm64
Rustc: rustc 1.79.0 (129f3b996 2024-06-10)

**Comment by amrbashir** [comment]
Does it matter if you specify a size?

See https://docs.rs/wry/latest/wry/struct.WebViewBuilder.html#method.with_bounds

**Comment by doceazedo** [comment]
> Does it matter if you specify a size?
> 
> See https://docs.rs/wry/latest/wry/struct.WebViewBuilder.html#method.with_bounds

No... I added this and it made no difference:
```rs
.with_bounds(Rect {
    position: Position::from(LogicalPosition::new(0, 0)),
    size: Size::from(LogicalSize::new(100, 100)),
})
```
I tried it with `::new_as_child` and `::new` (just in case).

**Comment by amrbashir** [comment]
I don't have a macOS to test, so hopefully someone else can help

**Comment by Eveeifyeve** [comment]
> I don't have a macOS to test, so hopefully someone else can help

I do have a mac I could test, but I need to download Godot.

**Comment by doceazedo** [comment]
Finally got to try it on Windows. The behavior there is similar, but with these differences:

- DevTools doesn't open
- Resizing the window leaves a persistent gray/black rectangle the size of the original window (see below). I guess that is where WRY would be rendered, and it fails to resize with the window, but again that's just a guess.

| **`::new()`**  | **`::new_as_child()`** |
|---|---|
| ![image](https://github.com/user-attachments/assets/0588b70e-b57d-4c24-b420-2e6215fc26fa) | ![image](https://github.com/user-attachments/assets/c2293bc7-b91c-49b9-bd0f-ad191f2e4ec8) _I only got this black rectangle to appear once._ |

I tried updating WRY since there were a few releases since this issue was opned and it seems like DevTools do open for a split second but closes right after:

https://github.com/user-attachments/assets/f280e4a1-0956-4920-8e74-0f4c27e491db

I pushed a [`windows` branch here](https://github.com/doceazedo/godot_wry/tree/windows) if anyone wants to debug it further.

**Comment by Eveeifyeve** [comment]
> Finally got to try it on Windows. The behavior there is similar, but with these differences:
> 
>     * DevTools doesn't open
> 
>     * Resizing the window leaves a persistent gray/black rectangle the size of the original window (see below). I guess that is where WRY would be rendered, and it fails to resize with the window, but again that's just a guess.
> 
> 
> **`::new()`** 	**`::new_as_child()`**
> ![image](https://private-user-images.githubusercontent.com/33992396/378046334-0588b70e-b57d-4c24-b420-2e6215fc26fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMTIyMTMsIm5iZiI6MTcyOTMxMTkxMywicGF0aCI6Ii8zMzk5MjM5Ni8zNzgwNDYzMzQtMDU4OGI3MGUtYjU3ZC00YzI0LWI0MjAtMmU2MjE1ZmMyNmZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDA0MjUxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiMWE0MTk4MzU2NmExYTk2ZGU0ZDM4YmNhYTM5ZThlOGE4MDY1NTk1NmY2N2FlODYyMzhjNTdkOTg3ZTNjZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AxVT5hyrxstTahDW2nOyowbrwRHiYAjFZpuCSK-Hln4) 	![image](https://private-user-images.githubusercontent.com/33992396/378046305-c2293bc7-b91c-49b9-bd0f-ad191f2e4ec8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMTIyMTMsIm5iZiI6MTcyOTMxMTkxMywicGF0aCI6Ii8zMzk5MjM5Ni8zNzgwNDYzMDUtYzIyOTNiYzctYjkxYy00OWI5LWJkMGYtYWQxOTFmMmU0ZWM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDA0MjUxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1OGJlOTI5MzFjZDdkZDYzMWY0YjkzYjQyMDYzN2I5NjJiNTdlNzdiMjU2MTc1NTYxZmI2OGFmMDExMjA5YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KwoW96ZSvR8PYH-SgdSI86FBIu_BRX3-ZW_hFiO1oKo) _I only got this black rectangle to appear once._
> 
> I tried updating WRY since there were a few releases since this issue was opned and it seems like DevTools do open for a split second but closes right after:
> Godot_v4.3-stable_win64_b1g8fKL9mA.mp4
> 
> I pushed a [`windows` branch here](https://github.com/doceazedo/godot_wry/tree/windows) if anyone wants to debug it further.

I can debug the mac problems but I need some detailed reproduce steps. 
But unfortunately I can't reproduce windows as I use linux maybe someone else?

**Comment by doceazedo** [comment]
1. Fork the [repo](https://github.com/doceazedo/godot_wry) (checkout to the `windows` branch if needed)
2. Go to the `rust` directory and run `cargo build`
3. Open Godot 4.2 or up
4. Import the project from `godot/project.godot`
5. Click the Run Project (▶︎) button (or ⌘+B)
6. You will notice the same behavior showed in the screenshots

Godot will reimport the extension binaries as soon as you build them, so all you need is to click on Run Project again to test your changes.

**Comment by amrbashir** [comment]
Taking a look at the repo, it seems like you're not keeping the webview around and I think the webview gets dropped and thus removed from the window here https://github.com/doceazedo/godot_wry/blob/be04896f7dfa9af55e0854d039fd16430c8e6d35/rust/src/lib.rs#L63-L85

You also not using it with `.build_as_child` which I assume is what you want, instead of `build` which will cover the whole window.

**Comment by doceazedo** [comment]
@amrbashir Thank you!!!!!!!!! After doing some research and trying a bunch of things, wrapping the `WebViewBuilder::new()` with `ManuallyDrop::new()` prevents the webview from being dropped and it solves the issue!!

<img width="1378" alt="image" src="https://github.com/user-attachments/assets/48b852c4-3aa4-43f2-a2a6-6ee211a2ed7c">

**Comment by amrbashir** [comment]
@doceazedo I don't know much about Godot but you probably don't need `ManuallDrop`, the `ready` method takes `&mut Self`, so you probably can add do something like this:
```rs
struct Webview {
  webview: Option<wry::WebView>,
  base: Base<Node> 
}

#[godot_api]
impl INode for WebView {
  fn ready(&mut self) {
    // create webview
    let webview = WebViewBuilder::new().build(&window);
    
    // store it on this Node
    self.webview.replace(webview);
  }
}

```


Also there is the `init` method which could be used to create the webview there? if works, you won't need the `Option`

**Comment by doceazedo** [comment]
@amrbashir Cool, that also works :)

> Also there is the `init` method which could be used to create the webview there?

I don't think so, as this runs in the Godot editor, not in the game window.

I will close this issue since the problem is solved. Thank you so much once again :)
