### ISSUE TITLE
Windows: Support setting `ICoreWebView2EnvironmentOptions8::ScrollBarStyle`

### ISSUE THREAD

**Issue by Themayu** [tauri-apps/wry#1339]
# Is your feature request related to a problem? Please describe.
I need a way to set the WebView2 instance on Windows to use Fluent-style overlay scrollbars in Tauri. A member of the project has informed me on Discord that Wry exposes a way to set some platform-specific attributes by use of `PlatformSpecificWebViewAttributes` that are then used to configure settings in the WebView2 options and environment options.

# Describe the solution you'd like
I propose adding a new field to `PlatformSpecificWebViewAttributes` on Windows, and a setter method to `WebViewBuilderExtWindows` to update this field. I'm unsure whether to use a boolean where `true` = fluent overlay scrollbars and `false` = default scrollbars, or an enum that exposes both `Default` and `FluentOverlay`. I feel the latter would be better for extensibility if Microsoft extend the list of scrollbar styles in the future.

I expect the API would look something like this (documentation omitted for brevity):

```rust
#[cfg(windows)]
#[derive(Clone, Copy, Default)]
pub enum ScrollbarStyle {
  #[default]
  Default,
  FluentOverlay,
}

...

#[cfg(windows)]
#[derive(Clone)]
pub(crate) struct PlatformSpecificWebViewAttributes {
  ...
  scrollbar_style: ScrollbarStyle,
}

#[cfg(windows)]
impl Default for PlatformSpecificWebViewAttributes {
  fn default() -> Self {
    Self {
      ...
      scrollbar_style: ScrollbarStyle::Default,
    }
  }
}

#[cfg(windows)]
pub trait WebViewBuilderExtWindows {
  ...
  fn with_scrollbar_style(self, style: ScrollbarStyle) -> Self;
}

#[cfg(windows)]
impl WebViewBuilderExtWindows for WebViewBuilder<'_> {
  ...
  fn with_scrollbar_style(self, style: ScrollbarStyle) -> Self {
    self.platform_specific.scrollbar_style = style;
    self
  }
}
```

# Describe alternatives you've considered
I **cannot** use a browser flag for this, as per [the Microsoft Documentation on WebView2 browser flags](https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/webview-features-flags) where it says that browser feature flags are subject to being removed or altered at any time.

Also, it was either this or adding and exposing a Windows-specific wrapper around all of `ICoreWebView2EnvironmentOptions*`. I feel that for now, this will do.

**Comment by amrbashir** [comment]
> I'm unsure whether to use a boolean where `true` = fluent overlay scrollbars and `false` = default scrollbars, or an enum that exposes both `Default` and `FluentOverlay`. I feel the latter would be better for extensibility if Microsoft extend the list of scrollbar styles in the future.

An enum sounds fine

Do you plan to work on this in a PR? I can assign the issue to you in that case.

**Comment by Themayu** [comment]
I'm fine with adding this myself.

**Comment by Themayu** [comment]
Ah. I think I've encountered a bit of a problem: I can't figure out how I am going to expose this in Tauri, given that this is Windows-specific functionality with an enum that only exists in Wry when compiling for Windows.

**Comment by amrbashir** [comment]
one step at a time, you only need to worry about exposing it as a method on `WebviewBuilderExtWindows`, then later we can open a PR in Tauri, that will call this method.

**Comment by Themayu** [comment]
I have it exposed on `WebviewBuilderExtWindows` in my `wry` fork already, on the `feat/windows-add-scrollbar-style-option` branch. The reason I'm trying to figure out how to expose it in Tauri right now is so that I can test it, and make sure it's actually doing what I want it to.

**Comment by amrbashir** [comment]
you can see this commit for inspiration https://github.com/tauri-apps/tauri/commit/3dc38b150ea8c59c8ba67fd586f921016928f47c

**Comment by Themayu** [comment]
...I just realised I don't need to expose it in Tauri to test it just yet. I can just do something dirty - force it inside a local patch of `tauri_runtime_wry`, then revert that when I'm done.

**Comment by Themayu** [comment]
...

Well that's... **very** annoying.

Turns out that despite them being exposed, and despite [the Microsoft documentation for `ICoreWebView2EnvironmentOptions`](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2environmentoptions?view=webview2-1.0.2651.64) clearly showing the ability to cast `CoreWebView2EnvironmentOptions` to `ICoreWebView2EnvironmentOptions4` and above, it turns out that `webview2-com` doesn't actually reflect the implementations of `ICoreWebView2EnvironmentOptions4` or above on `CoreWebView2EnvironmentOptions`. So everything lines up according to the C++ documentation, but I'm completely unable to actually *cast* to `ICoreWebView2EnvironmentOptions8` in order to set the scrollbar style.

I'm going to submit a request for the missing COM interfaces to be added.

**Comment by amrbashir** [comment]
`webview2-com` does have that https://docs.rs/webview2-com/latest/webview2_com/Microsoft/Web/WebView2/Win32/struct.ICoreWebView2EnvironmentOptions8.html , we just haven't updated the version in wry, probably because we need to update `windows-sys` and `windows` crate across our repos

gonna start working on that today

**Comment by Themayu** [comment]
It has the interface defined. So does the version we are using here. It **does not** appear to have an implementation of that interface reflected on `CoreWebView2EnvironmentOptions`, which means we cannot cast to it.

**Comment by amrbashir** [comment]
I see, it is missing in https://github.com/wravery/webview2-rs/blob/2a4d92c91002f91b49fd282abbbe8ec8d3318339/crates/webview2-com/src/options.rs#L26-L31

**Comment by Themayu** [comment]
I've opened a request in `webview2-com`: https://github.com/wravery/webview2-rs/issues/30

**Comment by Themayu** [comment]
@amrbashir Good news: The missing COM interface implementations were added to `CoreWebView2EnvironmentOptions` in `webview2-com@0.33.0`, so this can go forward once Wry updates to the latest version.

Also, it turned out that the raw `ICoreWebView2EnvironmentOptions4` had a problem, so it was replaced with a custom-made `IFixedEnvironmentOptions4` instead.

**Comment by amrbashir** [comment]
webview2-com is updated in https://github.com/tauri-apps/wry/pull/1341

**Comment by Themayu** [comment]
Alright. I'll rebase onto that commit once it lands, then open a PR for both this and moving to using the `CoreWebView2EnvironmentOptions` API directly.
