### ISSUE TITLE
Is it possible to use this with the Iced crate? 

### ISSUE THREAD

**Issue by videni** [tauri-apps/wry#1345]
**Is your feature request related to a problem? Please describe.**
I'd like to open a url inside Iced app, I am wondering if it is possible to use this libary inside an Iced app, this libary uses raw-window-handle to manages window,  so does winit ,  and iced depends on winit.

**Comment by pewsheen** [comment]
Wry can work with the winit. You can try to create a webview with the Winit window: https://github.com/tauri-apps/wry/blob/dev/examples/winit.rs

That example is quite outdated now since Winit made lots of changes recently.
