### ISSUE TITLE
Reloading a webview initialized with `with_html` results in an empty page

### ISSUE THREAD

**Issue by just-be-dev** [tauri-apps/wry#1367]
**Describe the bug**

When initializing a webview with `with_html`, the webview is blank after reload. 

**Steps To Reproduce**
```rust
fn main() -> wry::Result<()> {
    use tao::{
        event::{Event, WindowEvent},
        event_loop::{ControlFlow, EventLoop},
        window::WindowBuilder,
    };
    use wry::WebViewBuilder;

    let event_loop = EventLoop::new();
    let window = WindowBuilder::new().build(&event_loop).unwrap();

    let _webview = WebViewBuilder::new(&window)
        .with_html("<h1>Hello, World!</h1>")
        .build()?;

    event_loop.run(move |event, _, control_flow| {
        *control_flow = ControlFlow::Wait;

        match event {
            Event::WindowEvent {
                event: WindowEvent::CloseRequested,
                ..
            } => *control_flow = ControlFlow::Exit,
            _ => (),
        }
    });
}
```

Right click the webview and select reload. 

**Expected behavior**

When reloading, the initial HTML should be present. 

**Screenshots**

**Platform and Versions (please complete the following information):**
OS: MacOS Sonoma 14.6.1
Rustc: rustc 1.78.0 (9b00956e5 2024-04-29)

**Additional context**

I'm sure that I could _prevent_ reloading via the navigation handler, but that seems slightly undesirable given that sometimes refreshing is an important recovery method for when things go really wrong in the UI. I would programmatically inject the HTML on refresh, but it's not clear to me exactly how to go about doing that. [`.load_url`](https://docs.rs/wry/latest/wry/struct.WebView.html#method.load_url) with a data URL?

**Comment by just-be-dev** [comment]
For extra context, I stumbled across this as I've been working on https://github.com/zephraph/webview which is a deno binding (ish) for Wry. The HTML usecase is important, but as I was working through building out some example apps I had one that was refreshing (for reasons I haven't yet determined), but that makes the app lose its content.

**Comment by amrbashir** [comment]
looking at our usage https://github.com/tauri-apps/wry/blob/aa42ca437262729afd0e3188f00fabec675f0dbe/src/wkwebview/mod.rs#L1166 and the docs for `loadHTMLString`, there is nothing weird we are doing, so I suspect this just how `loadHTMLString` behaves. 

We don't recommend using `wiht_html` and instead register a custom protocol to serve the html and use `with_url`.

**Comment by just-be-dev** [comment]
@amrbashir, yeah, I somewhat suspected that was the case. Implementing a custom protocol is something on my list, but for some basic usage using HTML is quite convenient. Something I think that would alleviate this issue is to implement `Webview::load_html` so that the HTML can be reloaded later. 

I've started out a sketch implementation in #1368. Is that something y'all would have an appetite for considering? It seems like it would add parity to the `load_url` API.

**Comment by amrbashir** [comment]
@zephraph yeah that's alright, thanks for the PR

**Comment by just-be-dev** [comment]
Given that #1368 is merged, I'm going to close this as that'll solve my problem. Thanks for the help!
