### ISSUE TITLE
Webview2 binding crate

### ISSUE THREAD

**Issue by wusyong** [tauri-apps/wry#137]
We switched back to `window-rs` in dev branch now which is pretty great.
This means we are also going to publish webview2 binding crate.
Some refactoring and documentation might be required before we actually publishing.

**Comment by nothingismagick** [comment]
I still think that we should put that behind a feature flag and not just replace it. There are cases where people will absolutely want to be able to ship to win7 and this will not allow that.

**Comment by wusyong** [comment]
windows-rs can provide win32 as well. I plan to open another PR to add the previous impl back but with this interface.

Edit: On second thought, I don't think windows7 can compile windows-rs even we don't use winrt. I'll just bring the old implementation back with good old winapi crate.

**Comment by wusyong** [comment]
winrt is now under a feature flag and we are able to publish it to crates.io
