### ISSUE TITLE
Request for documentation on safety

### ISSUE THREAD

**Issue by Mubelotix** [tauri-apps/wry#1374]
Could you please document why the following code is safe? If it's safe, why isn't it implemented in the library providing it directly? Thanks!

https://github.com/tauri-apps/wry/blob/eafaadb9b35f74f07ef83da3d3e738c9ae631f7c/src/webkitgtk/web_context.rs#L359

**Comment by amrbashir** [comment]
This is an internal type, the gtk type it warps is not safe. However our usage of it is guarded by `MainContext::invoke` which ensures it runs on the gtk main loop.

See our usage here https://github.com/tauri-apps/wry/blob/eafaadb9b35f74f07ef83da3d3e738c9ae631f7c/src/webkitgtk/web_context.rs#L222-L225

**Comment by Mubelotix** [comment]
Thank you! I was using it wrong
