### ISSUE TITLE
wry panics if non-files are dropped on it

### ISSUE THREAD

**Issue by hediet** [tauri-apps/wry#138]
**Describe the bug**
wry panics if non-files are dropped on it

**Steps To Reproduce**
```rust
use wry::{Application, Attributes, Result};

fn main() -> Result<()> {
  let mut app = Application::new()?;

  let attributes = Attributes {
    url: Some("https://www.google.com/".to_string()),
    title: String::from("App"),
    transparent: true,
    ..Default::default()
  };

  let w = app.add_window_with_configs(attributes, None, None, Some(Box::new(|e| {
    println!("{:?}", e);
    true
  })))?;
  
  app.run();
  Ok(())
}
```

* `cargo run`
* drop a bookmark from chrome on the window

**Expected behavior**
It does not crash.

**Actual Behavior**
```
finished dev [unoptimized + debuginfo] target(s) in 2.13s
     Running `target\debug\wry-demo-2.exe`
thread 'main' panicked at 'Error occured while processing dropped/hovered item: item is not a file.', C:\Users\henni\.cargo\git\checkouts\wry-0ba07c7b81cd1a87\d2a2a9f\src\webview\win\file_drop.rs:295:7
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: Rust panics must be rethrown
error: process didn't exit successfully: `target\debug\wry-demo-2.exe` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
```

**Platform and Versions (please complete the following information):**
OS: Windows 10
Rustc: rustc 1.53.0-nightly (07e0e2ec2 2021-03-24)

**Would you assign yourself to resolve this bug?**
- [ ] Yes
- [x] No

**Comment by wusyong** [comment]
This is because we have a debug assert which always panic if the dropped item isn't a file.
Release build should work fine.
I could remove it if this isn't desired.

**Comment by hediet** [comment]
I think it shouldn't panic, as this is not an impossible state.
It should do nothing until drag/drop support for non-files is supported.
I can do a PR for this one!

**Comment by wusyong** [comment]
Feel free to open a PR 😀

**Comment by hediet** [comment]
Thank you!
