### ISSUE TITLE
macos issue when using `run_return` on the winit event loop - [webview is not created]

### ISSUE THREAD

**Issue by lemarier** [tauri-apps/wry#145]
**Describe the bug**
When I create a new webview inside a winit window on macOS using the `run_return` loop the webview didn't get created. I need to resize the window manually to get it to work.

With the tests I've made, the webview didn't get created at all as I see as the right-click is not enabled, so it seems to be only the winit window.

**Steps To Reproduce**
I created a reproducible example available here:
→ https://github.com/lemarier/wry_macos_bug

**Expected behavior**
Webview should be created and initialized on the first draw.

**Screenshots**
![sample gif](https://i.imgur.com/xVConhs.gif)

**Platform and Versions (please complete the following information):**
OS: macOS Big Sur 11.2.3
Rustc: 1.51.0 (2fd73fabe 2021-03-23)

**Would you assign yourself to resolve this bug?**
- [ ] Yes
- [x] No

**Comment by lemarier** [comment]
After different test it seems to be a winit bug

**Comment by wusyong** [comment]
I couldn't reproduce it. Commented out the start cause event but it still can open the page for me.
Did you try `run` method of the event loop? `run_return` is usually not recommended for some subtle issues.

**Comment by lemarier** [comment]
Issue related to winit and not wry.
