### ISSUE TITLE
[Feature] Allow window to be resizable when decoration is set to false

### ISSUE THREAD

**Issue by Shotman** [tauri-apps/wry#158]
**Is your feature request related to a problem? Please describe.**
Add the ability to resize the window when decoration is set to false

**Describe the solution you'd like**
Even though the window is set to be resizable when decoration is set to false, no handles are present on the webview so it's not possible to resize the window at will

**Would you assign yourself to implement this feature?**
- [ ] Yes
- [x] No

**Additional context**
Found that using Tauri beta release

**Comment by nothingismagick** [comment]
@amrbashir made a PR to fix this upstream, but there are problems...

https://github.com/rust-windowing/winit/pull/1891

**Comment by wusyong** [comment]
With #333, we now have support of resizing on borderless window.
