### ISSUE TITLE
MacOS version tied to bundler OS?

### ISSUE THREAD

**Issue by nothingismagick** [tauri-apps/wry#159]
We need to know what versions we can run these binaries on. I am filing this here instead of tauri, because many are using wry without tauri so we need to help them out. 

I briefly spoke with @rajivshah3 and he said:

> You can use `otool -l` on the binaries and libraries and look for `LC_BUILD_VERSION` or `LC_VERSION_MIN_MACOSX`

**Comment by rajivshah3** [comment]
Crashes on older versions of macOS look like [this](https://github.com/iotaledger/firefly/issues/897) (`Symbol not found: ____chkstk_darwin`). I think something like ~~https://github.com/iotaledger/firefly/pull/907~~ iotaledger/firefly#1012 should fix the issue

**Comment by wusyong** [comment]
Reopened it since apple doc is lying :(
