### ISSUE TITLE
Want a logo?

### ISSUE THREAD

**Issue by nothingismagick** [tauri-apps/wry#16]
![image](https://user-images.githubusercontent.com/35242872/107113294-607dbe00-685e-11eb-8325-f9a38195ee25.png)

**Comment by wusyong** [comment]
Definitely!

**Comment by nothingismagick** [comment]
Here with a proper color scheme
![wry_2](https://user-images.githubusercontent.com/35242872/107114290-15b37480-6865-11eb-9c40-b8d1a9daecaa.png)

**Comment by nothingismagick** [comment]
Will PR with SVG to the repo this afternoon.
