### ISSUE TITLE
bug(custom-protocol): history push state error on windows

### ISSUE THREAD

**Issue by lemarier** [tauri-apps/wry#170]
**Describe the bug**
Unable to use history API on windows.

**Steps To Reproduce**
- Launch any wry example on Windows.
-  Open Console.
- Execute code below:
```js
history.pushState({}, "Test", "index.html");
```

**Expected behavior**
Expect no error

**Screenshots**
![Screen Shot 2021-04-19 at 3 04 01 PM](https://user-images.githubusercontent.com/22237916/115289375-7e01ba80-a120-11eb-878a-2d86485f7336.png)

**Platform and Versions (please complete the following information):**
OS: Windows
Rustc: 1.51.0

**Would you assign yourself to resolve this bug?**
- [ ] Yes
- [x] No

**Comment by lemarier** [comment]
I think we should check [SetVirtualHostNameToFolderMapping](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2_3?view=webview2-1.0.774.44&preserve-view=true#setvirtualhostnametofoldermapping) -- instead of using file:// we'll be able to use http:// or maybe there is other possibilities that I'm not aware?

**Comment by nothingismagick** [comment]
`origin 'null'` is scary

**Comment by wusyong** [comment]
I think this also has something to do with our workaround on Windows. Current webview2 binding doesn't expose this method either.
So either way, we'll need to update upstream webview2.

**Comment by wusyong** [comment]
Looks like it's possible to register a custom protocol with version 1.0774
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.addwebresourcerequestedfilter?view=webview2-dotnet-1.0.774.44#Microsoft_Web_WebView2_Core_CoreWebView2_AddWebResourceRequestedFilter_System_String_Microsoft_Web_WebView2_Core_CoreWebView2WebResourceContext_

**Comment by lemarier** [comment]
> Looks like it's possible to register a custom protocol with version 1.0774
> https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.addwebresourcerequestedfilter?view=webview2-dotnet-1.0.774.44#Microsoft_Web_WebView2_Core_CoreWebView2_AddWebResourceRequestedFilter_System_String_Microsoft_Web_WebView2_Core_CoreWebView2WebResourceContext_

Do you think we should open a PR to webview2 crate to add the binding?

Edit: I saw binding are already here and we already use it. So more tests are required by changing the `file` handler to the same approach we are doing with macOS and Linux?

Edit 2: Available since `1.0.664.37` and we already use it. Tried with webview2 current branch who use `1.0774` and got (same error as crate version)
![Screen Shot 2021-04-20 at 8 22 46 AM](https://user-images.githubusercontent.com/22237916/115395189-9a9a0300-a1b1-11eb-8d6c-49f7f5c35452.png)

**Comment by wusyong** [comment]
Ah sorry I should link the issue instead: https://github.com/MicrosoftEdge/WebView2Feedback/issues/73
But again with the new stable version 1.0744, it should include this fix.
I'll test it on winrt first.

Edit: ugh sorry again. It's these issues that should be tracked: https://github.com/MicrosoftEdge/WebView2Feedback/issues/172 / https://github.com/MicrosoftEdge/WebView2Feedback/issues/173
And it seems it hasn't resolved yet. We'll need to stick to current workaround for a while :(
