### ISSUE TITLE
Cursor bug on macOS

### ISSUE THREAD

**Issue by lemarier** [tauri-apps/wry#175]
**Describe the bug**
The cursor didn't respect CSS / Webview properties. For example, hovering a link, will NOT display the pointer cursor has expected. Sometimes it works, sometimes it doesn't.

**Steps To Reproduce**
Run `cargo run --example custom_protocol` on macOS and the link cursor shouldn't; work. If it works, move the cursor out of the window area and if you come back to the link, the pointer will not work. Resize the window seems to fix.

**Expected behavior**
The cursor should work on the first webview paint.

**Screenshots**

https://user-images.githubusercontent.com/22237916/115412033-ff5d5980-a1c1-11eb-91e7-bd7db9c730d4.mov

**Platform and Versions (please complete the following information):**
OS: macOS

**Would you assign yourself to resolve this bug?**
- [ ] Yes
- [x] No

**Additional context**

I think this is because the webview didn't get the focus.

We need to check if it's a webview or a winit bug. 
For me, it looks like a winit bug.

**Comment by wusyong** [comment]
Saw a StackOverflow question similar to this: https://stackoverflow.com/questions/51692295/wkwebview-on-macos-missing-pointer-events-hover-cursor-changes-etc

**Comment by lemarier** [comment]
Using this event loop help to track the issue

```rust
match event {
      Event::NewEvents(StartCause::Init) => {
        println!("Wry application started!");
      },
      Event::WindowEvent {
        event: WindowEvent::CloseRequested,
        ..
      } => *control_flow = ControlFlow::Exit,
      Event::WindowEvent {
        event: WindowEvent::Focused(focused),
        ..
      } => {
        println!("Window focus {}", focused);
      },
      Event::WindowEvent {
        event: WindowEvent::CursorEntered { .. },
        ..
      } => {
        println!("Cursor entered window");
      },
      Event::WindowEvent {
        event: WindowEvent::CursorLeft { .. },
        ..
      } => {
        println!("Cursor left window");
      },
      _ => (),
}
```

What I saw is having this flow make the cursor work every time:
- Window focus false
- Cursor entered window
- Window focus true

**Comment by lemarier** [comment]
I think implementing the focus on the window should fix our problem here, but it's a workaround. Would be better of course if we can track down why the NSView require a focus false to work.

Or maybe we should check to implement the focus at the `NSView` level

**Comment by lemarier** [comment]
Not sure if it'll fix the cursor bug, but should resolve other related issues;

https://github.com/rust-windowing/winit/blob/b9f3d333e41464457f6e42640793bf88b9563727/src/platform_impl/macos/activation_hack.rs#L1

https://github.com/rust-windowing/winit/pull/1903

https://github.com/tauri-apps/wry/issues/184
