### ISSUE TITLE
macOS Event Loop / Focus Bug

### ISSUE THREAD

**Issue by lemarier** [tauri-apps/wry#184]
**Describe the bug**
This is the main issue to track all bugs related to the macOS Event Loop / Focus weird behaviors.

To resume the looks like the event loop is not working great with the focus.

On the first draw, the [activation hack](https://github.com/rust-windowing/winit/blob/b9f3d333e41464457f6e42640793bf88b9563727/src/platform_impl/macos/activation_hack.rs#L1) seems to disable some elements and makes the window unusable.

We also lost the focus on the Window / Webview causing different problems.

**Steps To Reproduce**
N/A

**Expected behavior**
Should work exactly like a native window.

**Screenshots**
N/A

**Platform and Versions (please complete the following information):**
OS: macOS

**Additional context**
Please refer to linked issues.

**Comment by wusyong** [comment]
Closed by #220
