### ISSUE TITLE
Add gtk widget to x11 window

### ISSUE THREAD

**Issue by wusyong** [tauri-apps/wry#19]
I can't get away from this idea since winit use x11 for window creation. Hope any kind soul can help making it happen.

https://tronche.com/gui/x/xlib/window-and-session-manager/XReparentWindow.html

**Comment by wusyong** [comment]
Okay I did it but it's not what we think. the window is next to the x11 window...

**Comment by nklayman** [comment]
Will this work if the user is using Wayland instead of X11?

**Comment by wusyong** [comment]
I think it's going to be the same. We might stick to gtk-rs for now since gtk also support wayland. It's better we could support both on Linux anyway.

**Comment by wusyong** [comment]
Close it since this is not what we expect. If there's a new way to integrate winit and gtk. We'll open a new issue for it.
