### ISSUE TITLE
CPU Usage 12% even though the window is minimized

### ISSUE THREAD

**Issue by Ciantic** [tauri-apps/wry#204]
**Describe the bug**
CPU Usage 12% even though the window is minimized, and no WebViewBuilder in use

**Steps To Reproduce**
```toml
[dependencies]
wry = { git = "https://github.com/tauri-apps/wry", branch = "dev" }
```

```rust
fn main() -> wry::Result<()> {
    use wry::{
        application::{
            event::{Event, StartCause, WindowEvent},
            event_loop::{ControlFlow, EventLoop},
            window::WindowBuilder,
        },
        webview::WebViewBuilder,
    };

    let event_loop = EventLoop::new();
    let window = WindowBuilder::new()
        .with_title("Hello World")
        .build(&event_loop)?;
    // let _webview = WebViewBuilder::new(window)?
    //     .with_url("https://tauri.studio")?
    //     .build()?;

    event_loop.run(move |event, _, control_flow| {
        *control_flow = ControlFlow::Poll;

        match event {
            Event::NewEvents(StartCause::Init) => println!("Wry has started!"),
            Event::WindowEvent {
                event: WindowEvent::CloseRequested,
                ..
            } => *control_flow = ControlFlow::Exit,
            _ => (),
        }
    });
}
```

**Expected behavior**
Something considerably less 

**Screenshots**
![image](https://user-images.githubusercontent.com/64731/116009895-9e4fde80-a624-11eb-9b57-80befd4a6409.png)

**Platform and Versions (please complete the following information):**
OS: Windows 10 
Rustc: rustc 1.51.0 (2fd73fabe 2021-03-23)

**Would you assign yourself to resolve this bug?**
- [ ] Yes
- [x] No

This bug maybe related to winit bug https://github.com/rust-windowing/winit/issues/1634 but maybe not, however I think winit should also be fixed, IMO it's unusable with silent reading of mouse and keyboard by default.

**Comment by wusyong** [comment]
I can reproduce this and also got around 15% CPU usage.
But it can get significantly lower if the control flow is set to`ControlFlow::Wait`.
Even with moving mouse and typing keyboard constantly will only be 1~2%.
I think it's safe to close this issue unless we see any more usage outburst.
