### ISSUE TITLE
App is freezing when it was minimize for a long time

### ISSUE THREAD

**Issue by Silbad** [tauri-apps/wry#212]
Hello,

**Describe the bug:**
In dev mode (i have not try with a build one), the app is freezing when it was minimize for a long time.
The screen become black.

**Platform and Versions:**
OS: WIN10, Tauri rc2

https://discord.com/channels/616186924390023171/731495047962558564/836548390476578827

Thanks,

**Comment by lemarier** [comment]
Fixed in https://github.com/tauri-apps/wry/pull/232 - Please reopen if you have same problem on the next releases.

Thanks
