### ISSUE TITLE
`drag_window` API is not consistent

### ISSUE THREAD

**Issue by lucasfernog** [tauri-apps/wry#224]
On Linux, it returns `()`: https://github.com/tauri-apps/wry/blob/cea79fb7098cf870274b24512b117bd220ca7f34/src/application/window.rs#L717
But the winit interface returns a Result: https://docs.rs/tauri-winit/0.24.1/winit/window/struct.Window.html#method.drag_window

**Comment by amrbashir** [comment]
yikes, that's my bad, will PR a fix now
