### ISSUE TITLE
Webview rounded corner

### ISSUE THREAD

**Issue by lemarier** [tauri-apps/wry#239]
**Is your feature request related to a problem? Please describe.**
Allow rounded corner for webview

**Describe the solution you'd like**
n/a

**Describe alternatives you've considered**
n/a

**Would you assign yourself to implement this feature?**
- [x] Yes
- [ ] No

**Additional context**

## macOS / linux

```
let layer = webview.layer();
let _: () = msg_send![layer, setMasksToBounds: YES];
let _: () = msg_send![layer, setCornerRadius: 50.0];
```

## Windows 
to be validated

**Comment by wusyong** [comment]
closing this since it can be done by CSS and a few window configs
