### ISSUE TITLE
Prepare repo for production

### ISSUE THREAD

**Issue by nothingismagick** [tauri-apps/wry#24]
Obviously we need to have a number of things added to this repository:

- [x] CI: clippy, fmt, licensecheck
- [x] CI: matrix tests
- [x] CI: covector with appropriate tokens
- [x] CI: Dependabot
- [ ] CI: Hook to update tauri.studio documentation
- [x] ORG: issue template
- [x] ORG: PR template
- [x] ORG: security policy
- [x] ORG: community guidelines
- [x] DEV: contribution info

**Comment by jbolda** [comment]
Covector PR, but still needs the tokens.
https://github.com/tauri-apps/wry/pull/55

**Comment by wusyong** [comment]
The only thing left is the hook but not sure do we need it on the site?

**Comment by nothingismagick** [comment]
Do we want to move default branch to dev and introduce branch protections?

**Comment by wusyong** [comment]
Of course! Let me push a dev branch real soon

**Comment by wusyong** [comment]
It seems we have done most of them and now default branch is dev
