### ISSUE TITLE
Fix winrt support & windows-rs

### ISSUE THREAD

**Issue by wusyong** [tauri-apps/wry#247]
As `windows-rs` released v0.9, we are unable to update it for several reasons
Right now, it's already broken because of `DestroyWindow` from winapi.
But this is trivial and we can fix no doubt.
The main problem is update the webview2, its binding in rust, and windows-rs version.
So in order to keep the maintain of winrt flag, we need to:

- [ ] Fix compile error for current version
- [ ] Update `windows-webview2` to a stable webview2 version
- [ ] Update `windows-rs`

I would say the most difficult one is updating `windows-webview2`, because we also have to make sure lots of new features are delivered.
Any help is welcome! <3

**Comment by wusyong** [comment]
With `webview2` crate is getting stable and we added more features. I feel like we should just remove the winrt support for now.
Until we get all we need on `windows-rs`

**Comment by amrbashir** [comment]
I agree

**Comment by amrbashir** [comment]
I agree

**Comment by amrbashir** [comment]
I agree

**Comment by amrbashir** [comment]
I agree

**Comment by wusyong** [comment]
Closed by #356
