### ISSUE TITLE
flat() and flatMap() on MacOs

### ISSUE THREAD

**Issue by cluskii** [tauri-apps/wry#249]
**Describe the bug**
Hi, 

I'm trying to use Tauri and WRY. I'm seeing an issue with `flat()` and `flatMap()`. My app is typescript, compiled from es2019 to ES6. I've tried opening the app through safari, where the error does not happen. As far as I know, ES6 should be supported by WebKit (and since safari is happy, it seems to be?), so I was wondering if it's potentially something to do with WRY. If it's nothing to do with WRY, then apologies, I'm still fairly hazy with how the Tauri stack works in depth.

If I can provide any extra info, please let me know.

The error:
```TypeError: array.flat is not a function. (In 'array.flat()', 'array.flat' is undefined)```

**Steps To Reproduce**
1. Use `flat()` or `flatMap()` in typescript file
```
const array: number[][] = [[1],[2]];
const flatArray = array.flat();
console.log(flatArray);
```
2. Compile and start app
3. Activate the code with `flat` or `flatMap` being used.

**Expected behavior**
I'm expecting the code to not throw an error, and use flat correctly.

**Platform and Versions (please complete the following information):**
OS: MacOs 10.13.6
Rustc: rustc 1.51.0 (2fd73fabe 2021-03-23)

**Would you assign yourself to resolve this bug?**
- [ ] Yes
- [x] No

**Additional context**

**Comment by wusyong** [comment]
Thanks for the report! Your feedback is valuable to us for sure! We are trying to improve our issue filing process and templates too!

I tried to run the hello world example and write some pure js in debug console. And it seems working fine.
I'll investigate further and maybe have some discussion on discord.
<img width="239" alt="圖片" src="https://user-images.githubusercontent.com/8409985/117605471-5b484c00-b18a-11eb-8085-29bcef476faf.png">

**Comment by cluskii** [comment]
Hey, thanks for your response. 

I tried running the same, just as a sanity check, and it looks like I can trigger it in the console (Screenshot below). Maybe since I'm not on the latest MacOs yet I'm missing some newer features?

Happy to chat on discord, I'm on the Tauri server and my handle is @cluskii 

![image](https://user-images.githubusercontent.com/8582713/117656222-fe4f9480-b18f-11eb-9be2-e5b97c837097.png)

**Comment by cluskii** [comment]
After further discussion on discord, looks like this is an issue with outdated OS and typeScript compilation not working properly on my project.
