### ISSUE TITLE
Test suite with webdrivers

### ISSUE THREAD

**Issue by wusyong** [tauri-apps/wry#252]
It would be awesome if we can have a test harness with webdrivers. But different platform might require different and in-depth know how:

- Linux: unkown
- macOS: unkown
- Windows: https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/webdriver

**Comment by nothingismagick** [comment]
This is being worked on here:
https://github.com/tauri-apps/tauri/tree/feat/webdriver/tooling/webdriver

**Comment by bukowa** [comment]
Take a look here https://github.com/bukowa/tauri-e2e
