### ISSUE TITLE
RPC handler overhaul

### ISSUE THREAD

**Issue by wusyong** [tauri-apps/wry#253]
**Is your feature request related to a problem? Please describe.**
As the library is stable, I think it's a good time to look back at our RPC handling.
Indeed, we do extend it to become more flexible. But it still has some restrictions.
the handler could only be one. and some of the handling processes is done by this lib which limits some use case for users.

**Describe the solution you'd like**
Extend the RPC handler just like what custom protocols did. We could offer a vector of handlers and let users decide how many they want to define.
Furthermore, we remove the implementation of JSON RPC. Don't get me wrong, this is actually the right implementation IMHO. But as a general webview lib, we should just expose vanilla parameters each platform provides.

**Describe alternatives you've considered**
Keep current one. But I believe it's better to let users decide the amount and the message format of the RPC handler.

**Would you assign yourself to implement this feature?**
- [x] Yes
- [ ] No

**Additional context**
This also means #79 should let users implement instead. And in our cases, might transfer to tauri repo.

**Comment by nothingismagick** [comment]
I think a couple nice options would be:
- a highly secure RPC (ala noise protocol)
- a low-bandwidth non-JSON datastructure
- some kind of data streaming (e.g. for video)

**Comment by wusyong** [comment]
> a low-bandwidth non-JSON data structure

This is the one this issue what to address at the moment. Because we could use the interface each platform provides and reduce as many overheads as possible.

As for other protocol and format enhancements, I suppose we could add them behind the feature flag or implement them in tauri instead in the future.

**Comment by nothingismagick** [comment]
Yeah - I was sort of wondering about adding them in Tauri - or finding a way to do it with a Tauri plugin...

**Comment by wusyong** [comment]
I was exploring the native way to send back message to javascript on rpc.
Linux and Windows are working so far.
The only one left is macOS, but I have stuck for a while.

Here's the bottleneck to look into and I appreciate any help!
https://github.com/tauri-apps/wry/blob/feat/rpc/src/webview/macos/mod.rs#L90

**Comment by shirakaba** [comment]
Happy to help with this, once I’m done implementing the Cocoapods workflow.

**Comment by shirakaba** [comment]
Though if it’s any help in the meantime, here’s an example of how we used it in React Native WebView:

https://github.com/react-native-webview/react-native-webview/blob/f84b5fdec8845df0a2ffc080265d13cfb166ec3a/apple/RNCWebView.m#L498

Note in particular the comment above the delegate method:

```objc
/**
 * This method is called whenever JavaScript running within the web view calls:
 *   - window.webkit.messageHandlers[MessageHandlerName].postMessage
 */
 ```

**Comment by wusyong** [comment]
Yes, this is what we already did.
What I wish to accomplish is using [userContentController:didReceiveScriptMessage:replyHandler:](https://developer.apple.com/documentation/webkit/wkscriptmessagehandlerwithreply/3585111-usercontentcontroller?language=objc) instead of evaluate javascript to send message back to javascript.

**Comment by lucasfernog** [comment]
I hope this improves the performance a bit :P nice

**Comment by lucasfernog** [comment]
Also is it possible to use this new RPC style but without relying on the rpc handler return value, but use a callback instead? tauri doesn't use the return value because it spawns a tokio task and evals the response.

**Comment by wusyong** [comment]
@lucasfernog yes, this is also what this issue wants to accomplish. Ideally, users handle those themselves.
In tauri, we probably will set up some methods that suit best ourselves.

**Comment by olup** [comment]
So switching here from #1877

The poor performance seems unrelated to serializing - I get this whatever the form or size of what is returned.
Even if I don't return anything from the rust command, the js promise can still take a very long time to resolve.
In DEV mode or with the BUILT product It can go up to 6 seconds. And never less thant 600-ish miliseconds. The rust operations ends up under a milisecond, of course.

**Comment by wusyong** [comment]
Some updates on Linux here.
Webkit2gtk does have the methods we need, but it's in the latest commit.
And I couldn't use it directly because gtk-rs is refactoring the repo structure which I couldn't compile them at the moment.

**Comment by wusyong** [comment]
Closing it because I'm not going to do any other breaking changes for Tauri 1.0
Perhaps we could look into it again on 2.0
