### ISSUE TITLE
Add method to check if WebView2 is installed before opening the window

### ISSUE THREAD

**Issue by federico-terzi** [tauri-apps/wry#265]
First of all, thank you for all your hard work. This project, along with Tauri is wonderful!

**Is your feature request related to a problem? Please describe.**
I'm looking forward to integrating wry with my project [espanso](https://github.com/federico-terzi/espanso), and one thing I'd like to implement is a graceful fallback if the WebView2 runtime is not available.

**Describe the solution you'd like**
I'd love to have a method to check if a suitable WebView2 runtime is available **before** launching the wry window. Something like `is_webview2_available() -> bool`, which could be called beforehand, letting espanso fall back to another alternative "gracefully".

**Describe alternatives you've considered**
Currently, if the WebView2 runtime is not available. the `WebViewBuilder...build()` method returns a `WebView2Error`. But while doing so, it also "flashes" an empty window, which is not great from a UX perspective.

![wry_webview_not_present](https://user-images.githubusercontent.com/20475953/118395166-25eba480-b649-11eb-88c1-9c8010637e5e.gif)

Having a `is_webview2_availabe()` method would allow espanso to check if a runtime is available before opening the window

**Would you assign yourself to implement this feature?**
- [ ] Yes
- [X] No

I checked "No" because for the upcoming months I might not be able to allocate much time to it, but things might change in 4/6 months.

Let me know what you think :)

**Comment by wusyong** [comment]
There's [method](https://github.com/tauri-apps/wry/blob/dev/src/webview/mod.rs#L464) in next patch which can check the webview version. It will return error if there's no webview2 runtime.
If you need it soon, I could publish a patch version in the coming days.

**Comment by federico-terzi** [comment]
> There's method in next patch which can check the webview version. It will return error if there's no webview2 runtime.

@wusyong Sounds wonderful! That's exactly what I need :)

> If you need it soon, I could publish a patch version in the coming days.

No worries, I'll probably need it in a couple of months, so there is time for that, I'll wait for the official release :) Thank you very much for your hard work!

**Comment by wusyong** [comment]
v0.9.4 now has a [function ](https://docs.rs/wry/0.9.4/wry/webview/fn.webview_version.html)to check webview version

**Comment by federico-terzi** [comment]
@wusyong Awesome, thank you!
