### ISSUE TITLE
Webview2 runtime performance issues

### ISSUE THREAD

**Issue by lucasfernog** [tauri-apps/wry#275]
**Describe the bug**
The WRY implementation has a few issues regarding the webview2 runtime usage (Windows):

- There's no way to know if an async code finished running, so it uses a hack code that delays app initialization a couple seconds: https://github.com/tauri-apps/wry/blob/a76206c11fa0a4ba1d041aa0f25452dd80941ee9/src/webview/win32/mod.rs#L217
- We've seen some performance issues on the latest webview2 runtime (version 90.0.818.62). A basic tauri application needed 5~ seconds to load a page, and reloads are also affected.

**Steps To Reproduce**
Clone the WRY or Tauri repo, and run one of the examples.

**Expected behavior**
The app loads as fast as possible. The loading is excellent on Linux/macOS.

**Videos**

Videos from @tensor-programming 

https://user-images.githubusercontent.com/20051258/118724460-05684980-b805-11eb-9b51-d4fcb6970bbb.mp4

https://user-images.githubusercontent.com/20051258/118724468-08633a00-b805-11eb-8c55-a95788cb7d21.mp4

**Comment by tensor-programming** [comment]
It seems that Microsoft is aware of the speed deficiency with the current evergreen runtime.  As far as the other issue is concerned, its a matter of figuring out a method to deal with the async calls and not block the main thread.

**Comment by Boscop** [comment]
The initial load time is very annoying during development when the backend is restarted often (e.g. with cargo-watch).
I opened an upsteam issue here: https://github.com/MicrosoftEdge/WebView2Feedback/issues/1298

**Comment by Beanow** [comment]
The multiwindow example is most pronounced here. Comparing vs linux on today's dev branch.

https://user-images.githubusercontent.com/497556/118727645-5db64000-b833-11eb-877e-fcbd455143a4.mp4


https://user-images.githubusercontent.com/497556/118727646-5ee76d00-b833-11eb-8991-054e22a1993a.mp4

**Comment by tensor-programming** [comment]
https://user-images.githubusercontent.com/22513880/118727821-668e1e00-b801-11eb-94e9-d5ca35c83f15.mp4

Heres an example of the multiwindow from my side.

**Comment by nothingismagick** [comment]
https://github.com/tauri-apps/tauri/issues/1850#issuecomment-843913641

**Comment by wusyong** [comment]
I just realized #315 actually fixed this issue. Lucas also confirmed that.
If it holds the same after patch version, I think we can close this issue.
