### ISSUE TITLE
Option do disable the default context menu

### ISSUE THREAD

**Issue by sassman** [tauri-apps/wry#30]
When packaging a default webapp, then the context menu (at least on macOS) has 2 entries:

 - reload
 - back

I wonder if there is an option to disable the context menu by configuration?
Of course, I can implement that in JavaScript but I wonder if that is not like a common case, where people want to default to no context menu actions because their webapp does not have any own ones.

**Comment by nklayman** [comment]
You can disable on linux with this: `webview.connect_context_menu(|_, _, _, _| true);`. See [this page](https://webkitgtk.org/reference/webkit2gtk/stable/WebKitWebView.html#webkit-web-view-set-input-method-context) for more details on the linux implementation. Not sure how to do it on other platforms.

**Comment by wusyong** [comment]
context menu can be disabled from javascript with:
`document.addEventListener('contextmenu', event => event.preventDefault());`
Until this becomes a critical feature that we really need it, I'll close this one

**Comment by FastLight126** [comment]
you can use this:

function disableMenu() {
      if (window.location.hostname !== 'tauri.localhost') {
        return
      }

      document.addEventListener('contextmenu', e => {
        e.preventDefault();
        return false;
      }, { capture: true })

      document.addEventListener('selectstart', e => {
        e.preventDefault();
        return false;
      }, { capture: true })
    }

disable contextmenu only release

**Comment by FastLight126** [comment]
you can use this:

`disableMenu() {
  if (window.location.hostname !== 'tauri.localhost') {
    return
  }

  document.addEventListener('contextmenu', e => {
    e.preventDefault();
    return false;
  }, { capture: true })

  document.addEventListener('selectstart', e => {
    e.preventDefault();
    return false;
  }, { capture: true })
}`

disable contextmenu auto only release

**Comment by FastLight126** [comment]
you can use this:

disableMenu() {
if (window.location.hostname !== 'tauri.localhost') {
return
}

document.addEventListener('contextmenu', e => {
e.preventDefault();
return false;
}, { capture: true })

document.addEventListener('selectstart', e => {
e.preventDefault();
return false;
}, { capture: true })
}

disable contextmenu auto only release

**Comment by JokerQyou** [comment]
Of course it's possible to do this in Javascript, but what if you only want to disable it for release build? There is no debug flag in Javascript, so you'd have to invoke another command to get debug flag from Rust first. This seems too much twisted logic for such a small feature.

**Comment by cmdmasquerade** [comment]
> Of course it's possible to do this in Javascript, but what if you only want to disable it for release build? There is no debug flag in Javascript, so you'd have to invoke another command to get debug flag from Rust first. This seems too much twisted logic for such a small feature.

What @FastLight126 did only disables context menu for the release. I've tested it right now. (I know this is very old reply, but it might help someone) 

If you wish to disable it for dev environment also, just add "localhost" next to "tauri.localhost."
