### ISSUE TITLE
Support file explorer using html

### ISSUE THREAD

**Issue by TomzBench** [tauri-apps/wry#305]
**Is your feature request related to a problem? Please describe.**
I am consuming a React component from a library that will open a file explorer. The React component is not aware of Tauri. I am having trouble using this component when inside Tauri. But can use this component in a normal web context.

**Describe the solution you'd like**
My React File Upload component seemed to work in version `1.0.0-beta.1`. However, when upgrading to `dev` branch as of today, my React File Upload component will no longer open a file explorer.  Perhaps something changed in the upgrade. So if possible, it would be nice to opt into file navigation with `tauri.conf`.  I do not know what the configuration would be, because I'm not sure what has changed to no longer allow my component file explorer to work.

**Describe alternatives you've considered**
I can refactor my React File Upload component to inject an optional tauri dependency and use this dependency in tauri context, and use default behavior when not inside tauri context. However, this is only possible since I maintain the File Upload component.  Other users might not have this option when consuming UI libraries (such as Material-UI, etc).

**Would you assign yourself to implement this feature?**
- [ ] Yes
- [x] No  ...Sorry, I am unaware of the codebase related to this feature

**Comment by lemarier** [comment]
I can confirm on macOS it doesn't work

look like we need to implement an `UIDelegate`

Are you sure it was working before within tauri webview engine?

If yes, on which OS?

**Comment by TomzBench** [comment]
@lemarier 

I am using Linux, and my file upload component was working there. I do not know if it worked on Windows or Mac before the upgrade. However i am certain it worked in Linux.

**Comment by lemarier** [comment]
macOS:

https://stackoverflow.com/a/42952247
https://developer.apple.com/documentation/webkit/wkuidelegate/1641952-webview?language=objc

**Comment by lemarier** [comment]
> I am using Linux, and my file upload component was working there.

It should be fixed now (on Linux) with https://github.com/tauri-apps/wry/pull/310

**Comment by TomzBench** [comment]
Thanks. For greater portability should I be using tauri `fs` api? I develop on linux but ultimately I have to support Windows as well.

**Comment by wusyong** [comment]
@TomzBench yeah, I think it's better to us `fs` instead. Most panel/modal opening are canceled by default on mac.
It will need to take a while even just to support file panel.

**Comment by keiya01** [comment]
Could I take on this issue?
Or is it a work in progress by someone else?

**Comment by wusyong** [comment]
@keiya01 Yeah, I believe no one is working on it yet.
