### ISSUE TITLE
Html document never stretches across initial window bounds when resizing.

### ISSUE THREAD

**Issue by FrankenApps** [tauri-apps/wry#318]
**Describe the bug**
When resizing the window on Windows 10, the document never gets updated or never gets stretched across the initial window extent. Instead a black area is displayed.

**Steps To Reproduce**
For example run the `custom_protocol` example on Windows 10.

**Expected behavior**
The document should fill the window.

**Screenshots**
![resize](https://user-images.githubusercontent.com/17967303/123763626-45baed00-d8c4-11eb-94c5-dee1deeb50d1.gif)

**Platform and Versions (please complete the following information):**
OS: Windows 10
Rustc: rustc 1.52.1

**Would you assign yourself to resolve this bug?**
- [ ] Yes
- [x] No Sorry, but I have no idea how to resolve this.

**Additional context**
This works perfectly on macos...

**Comment by amrbashir** [comment]
you have to call `webview.resize()` when the `WindowEvent::Resized` gets triggered, something like this https://github.com/tauri-apps/wry/blob/4d5ab3101542ebcd10e54606e97f458590a316d6/examples/custom_titlebar.rs#L142-L144
