### ISSUE TITLE
All custom protocol handlers are called on Windows

### ISSUE THREAD

**Issue by lucasfernog** [tauri-apps/wry#323]
I believe the [`add_web_resource_requested`](https://github.com/tauri-apps/wry/blob/070f332b65a0859437b372c7e0970e4837efb38e/src/webview/webview2/win32/mod.rs#L145) should only be called once and the protocol name needs to be parsed from the URL, calling the proper protocol handler. Currently all handlers are called.

**Comment by lucasfernog** [comment]
I have a fix for this and I believe this will fix https://github.com/tauri-apps/tauri/issues/2124

**Comment by timonwimmer-git** [comment]
Maybe I did something wrong - however after trying out your fix, I am still getting that annoying ERR_NAME_NOT_RESOLVED error every third time I open my application.

**Comment by wusyong** [comment]
@timonwimmer-git Did you try wry with commit after `923d346`? Or it's just on tauri?
Tauri hasn't updated to latest update of wry I believe.

If it's on wry, I would really appreciate to see a minimum reproducible example. So I'll could track it more clearly.

**Comment by timonwimmer-git** [comment]
With commit 923d346! 
The thing is, I really can't track it down. If I create a new VM and freshly set-up tauri, it still sometimes happens on the first run! I'll keep digging and get back to you.

**Comment by wusyong** [comment]
Thanks! Hmm, I'll also test with some examples to see if I can find out at the same time.

**Comment by timonwimmer-git** [comment]
With commit 923d346, just wry without tauri and using the custom_protocol.rs example (https://github.com/tauri-apps/wry/blob/renovate/windows-0.x/examples/custom_protocol.rs) I consistently got it working!
