### ISSUE TITLE
Keyboard shortcuts support for WebKit

### ISSUE THREAD

**Issue by KaKi87** [tauri-apps/wry#345]
**Is your feature request related to a problem? Please describe.**
WebKit does not allow refreshing using `Ctrl+R` or `F5` nor opening DevTools using `Ctrl+Shift+I` or `F12`.

**Describe the solution you'd like**
Implementing those shortcuts.

**Describe alternatives you've considered**
None

**Would you assign yourself to implement this feature?**
- [ ] Yes
- [x] No

**Additional context**
None

---
Thanks

**Comment by lemarier** [comment]
Refresh can be done with javascript or a menu item.

Devtools please refer to this issue
https://github.com/tauri-apps/wry/issues/287

**Comment by KaKi87** [comment]
Yes, but in my case, refreshing is only useful during development, end users would never use that feature.

Adding `addEventListener` statements on every project only for development purposes seem overkill.

Additionally, this is a Linux-only issue : Webview2 on Windows does support those shortcuts.

Thanks
