### ISSUE TITLE
Settings persistence for WebKit DevToools

### ISSUE THREAD

**Issue by KaKi87** [tauri-apps/wry#346]
**Is your feature request related to a problem? Please describe.**
WebKit DevTools does not remember its position nor its selected theme when relaunching a Tauri app.

**Describe the solution you'd like**
Implementing persistence for WebKit DevTools settings.

**Describe alternatives you've considered**
None

**Would you assign yourself to implement this feature?**
- [ ] Yes
- [x] No

**Additional context**
None

---
Thanks

**Comment by lemarier** [comment]
Thanks a lot for your suggestion,

It's not something we'll consider right now as the devtools is a private API and we can't ship in final apps.

Again, thanks.

**Comment by KaKi87** [comment]
I see, but this is a Linux-only issue : Webview2 on Windows does have persistence for DevTools settings.
It remembers position, theme, everything.

For instance, if I want DevTools to be windowed and dark, I have to do all those clicks at every dev script start.

**Comment by lemarier** [comment]
Gotcha! We would probably accept a PR for it tho. 
But we can't put our energy into this right now, but I totally understand your pain.
