### ISSUE TITLE
Add download link support

### ISSUE THREAD

**Issue by bdjnk** [tauri-apps/wry#349]
### **Describe the bug**
Generate an `a` tag with the `download` attribute set and the `href` attribute pointing to a `blob:` URL. For example the following.

```html
<a download="hello.txt" href='#' id="link">Download</a>
<script>
const blob = new Blob(["Hello, world!"], {type: 'text/plain'});
link.href = URL.createObjectURL(blob);
</script>
```
([example source](https://javascript.info/blob#blob-as-url))

Clicking such a link in any modern browser will initiate download of the linked resource. In Tauri, nothing happens.

### **To Reproduce**
1. Generate an `a` tag with the `download` attribute set and the `href` attribute pointing to a `blob:` URL. 
2. Click on the link generated in step 1.
3. Observe nothing happens

### **Expected behavior**
Download of the linked resource should initiate.

### **Platform and Versions (required):**
```
Operating System - Arch Linux, version Unknown X64

Node.js environment
  Node.js - 16.5.0
  @tauri-apps/cli - 1.0.0-beta.6
  @tauri-apps/api - 1.0.0-beta.5

Global packages
  npm - 7.17.0
  yarn - 1.22.10

Rust environment
  rustc - 1.53.0
  cargo - 1.53.0

App directory structure
/node_modules
/public
/src
/.git
/src-tauri

App
  tauri.rs - 1.0.0-beta.5
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../public
  devPath - http://localhost:3001
```

### **Additional context**
If a valid navigable URL (eg `https://duckduckgo.com/`) is used as the `href` of an `a` tag with the `download` attribute set, clicking the resultant link navigates to the given URL instead of downloading the content there.

**Comment by lemarier** [comment]
https://developer.apple.com/documentation/webkit/wkdownload?language=objc
https://www.gfrigerio.com/download-files-in-a-wkwebview/

**Comment by wusyong** [comment]
Looks like webkitgtk has API for it, but the rust crate doesn't provide any method other than constructor.
And webview2 only has experimental function for it.
- https://docs.rs/webkit2gtk/0.14.0/webkit2gtk/struct.Download.html
- https://github.com/MicrosoftEdge/WebView2Feedback/blob/master/specs/.md

**Comment by keiya01** [comment]
Could I take on this issue?
First of all, I will try to resolve it on MacOS because I'm using MacOS now :)

**Comment by nothingismagick** [comment]
@wusyong - think we'd have time to pick this back up again?

**Comment by lucasfernog** [comment]
I believe this is handled by #530 @nothingismagick

**Comment by atlanticaccent** [comment]
With #530 merged I believe this issue has been addressed completely. Notably, it includes examples for handling "normal" downloads and blob downloads, which happen to be different enough to require separate solutions.

**Comment by lucasfernog** [comment]
Nice! Let's try to add this to Tauri v1.3.
