### ISSUE TITLE
`aarch64-unknown-linux-musl` target support

### ISSUE THREAD

**Issue by littlebenlittle** [tauri-apps/wry#357]
**Describe the bug**

I am not able to compile the "hello world" example for the `aarch64-unknown-linux-musl` target.

**Steps To Reproduce**

[This repository](https://github.com/littlebenlittle/wry-aarch64-musl-example/tree/linking) has the full code, which is basically just a stripped down version of the [hello world example](https://github.com/tauri-apps/wry/blob/dev/examples/hello_world.rs) with some build scripts.

The rundown is

```sh
#!/bin/bash

wget https://musl.cc/aarch64-linux-musl-cross.tgz
tar -xf aarch64-linux-musl-cross.tgz

ctr=`buildah from docker.io/library/rust:1.53-alpine3.13`
buildah run $ctr apk add \
    gtk+3.0 \
    webkit2gtk-dev \
    gtksourceview-dev \
    glib-dev
buildah run $ctr rustup target add aarch64-unknown-linux-musl
buildah add $ctr aarch64-linux-musl-cross /opt/aarch64-linux-musl-cross
buildah commit $ctr rs:webkit-aarch64

cat >./.cargo/config.toml <<EOF
[target.aarch64-unknown-linux-musl]
linker = "/opt/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc"
rustflags = [ "-L /opt/aarch64-linux-musl-cross/aarch64-linux-musl/lib" ]
EOF

podman run -ti --rm --name rs \
    -v ./:/mnt \
    -w /mnt \
    rs:webkit-aarch64 \
    cargo build --target=aarch64-unknown-linux-musl --release
```

This results in many linking errors, most notably `error: could not compile proc-macro-hack`

I am new to rust and coming from perl/python/js so I may be making a very trivial error as I am not accustomed to all this linking business.

**Expected behavior**

I expect a binary built for the target arch.

**Platform and Versions (please complete the following information):**
OS: alpine:3.13
Rustc: 1.53.0

**Would you assign yourself to resolve this bug?**
- [x] Yes
- [ ] No

**Comment by wusyong** [comment]
We didn't build on musl target either. I don't think this is a trivial issue, but we are welcome any help!
For cross compilation to different arch, it's easier to build with [`cross`](https://github.com/rust-embedded/cross).
But we also have a lot of system package dependency (mostly gtk), I'm not sure how far could it go.

**Comment by littlebenlittle** [comment]
I was able to get this working using [`alpine-chroot-install`](https://github.com/alpinelinux/alpine-chroot-install) and then building the app in a qemu VM using a native toolchain. I also succeeded in simply compiling on the target device, but that ran a little hot.

[example](https://github.com/littlebenlittle/wry-aarch64-musl-example)

**Comment by nothingismagick** [comment]
This is great insight. We should consider putting this insight into the documentation! What do you think @Laegel ?
