### ISSUE TITLE
SVG files not being displayed in build but are in dev 

### ISSUE THREAD

**Issue by Shotman** [tauri-apps/wry#385]
**Describe the bug**
when you use an svg it's not displayed in the release binary but it is in during the dev process .

**Steps To Reproduce**
Use an SVG in a img tag 
Build the app in release mode
Run the app
SVG file not displayed

You can clone this [repo](https://github.com/Shotman/tauri-svg-issue)

**Expected behavior**
SVG file should be displayed as it is in dev mode

OS : Windows

**Comment by wusyong** [comment]
The tauri version in that repo seems pretty old.
I updated and run it in the release build and it could show the svg.

**Comment by Shotman** [comment]
My bad I didn't see that, I ran yarn tauri deps update and it told me it was up to date. Trusted that blindly :/ I bumped the version by hand in package.json and Cargo.toml rebuilt the app and everthing worked ! 
Closing
