### ISSUE TITLE
Zoom (change scaling factor)

### ISSUE THREAD

**Issue by shiMusa** [tauri-apps/wry#388]
**Is your feature request related to a problem? Please describe.**
Currently, it is not possible to zoom the webview (e.g. via Ctrl +, Ctrl -, or Ctrl mousewheel)  as expected since every (to me) known browser supports it.

**Describe the solution you'd like**
1) Automatically enable the typical shortcuts for zooming in and out
2) typescript/javascript method for changing the scaling factor (zoom).

**Describe alternatives you've considered**
Currently, the only suggestion was to change the CSS property `document.style.zoom`.

**Comment by lemarier** [comment]
Notes;

- Let see if it require any change to the native webview settings.

- Probably manageable with HTML meta tag

**Comment by CYBAI** [comment]
Hi, I'm new to the tauri world though, this issue seems to be a good first one for me to explore!
May I work on this issue? Thank you! 🙏

**Comment by wusyong** [comment]
I'm glad you are interested! Let's focus on providing method for each platform first. For example on macOS, this is the method you should implement:
 https://developer.apple.com/documentation/webkit/wkwebview/1414996-setmagnification?language=objc

**Comment by keiya01** [comment]
This issue seems to be not touched for a long time...
Could I take on this issue?
Or is it work in progress?

**Comment by FabianLars** [comment]
@keiya01 Feel free to work on it :heart: As far as i know nobody is working on it.

**Comment by CYBAI** [comment]
@keiya01 Please feel free to work on it 🙏

**Comment by qwexs** [comment]
It works well
```
// src-tauri/src/main.rs
fn main() {
    tauri::Builder::default()
        .on_page_load(|window, _payload| {
            window.set_zoom(0.8).expect("Failed to set zoom");
        })
        .run(tauri::generate_context!());
}
```
