### ISSUE TITLE
Can't use service worker on Mac

### ISSUE THREAD

**Issue by icidasset** [tauri-apps/wry#389]
**Describe the bug**
The service worker cannot be loaded because of the custom `tauri://` protocol, it requires `https://` or `http://localhost` specifically.

**Steps To Reproduce**
Load a service worker.

You can fork this repo https://github.com/icidasset/diffuse and use the Github action to compile it on all platforms.

**Expected behavior**
The service worker should load successfully.

**Screenshots**
<img width="761" alt="Screenshot 2021-08-20 at 16 53 40" src="https://user-images.githubusercontent.com/296665/130252384-430970f5-4d4c-4174-8bac-9081512d3a39.png">

**Platform and Versions (please complete the following information):**
OS: Mac
Rustc: 1.53.0

**Would you assign yourself to resolve this bug?**
- [ ] Yes
- [x] No

**Additional context**
Chatted about this on the Tauri discord and tried this suggestion https://stackoverflow.com/questions/49673399/service-workers-unavailable-in-wkwebview-in-ios-11-3/49673400#49673400
But that doesn't work unfortunately.

**Comment by wusyong** [comment]
Looks like it's not possible in custom url contexts. But it should be possible if you host your own localhost server.
Tauri let you launch each framework's local server in dev, but register custom URL in release build afaik.

**Comment by icidasset** [comment]
Thanks for confirming. I assume there's no way to disable the custom protocol in the release build?

**Comment by wusyong** [comment]
I think it should be possible but I'm not sure how to start up a server in js before tauri begins. It's fairly easy in rust since you could just spawn a thread and run something like actix-web.

**Comment by nothingismagick** [comment]
I thought we had a mechanism that would allow the user (at least in tauri) to choose to use a different protocol. Am I wrong about this?

**Comment by lucasfernog** [comment]
We have a plugin that allows using localhost server on production, tauri-plugin-localhost.

**Comment by icidasset** [comment]
@lucasfernog Thanks I've tried the plugin and it works great!

I've followed the example and that does have one minor problem though.
I'm getting the following in the console when resizing the window:
```
TypeError: window['5ae98b93-333b-439e-a895-08f45041b522'] is not a function. (In 'window['5ae98b93-333b-439e-a895-08f45041b522']({event: "tauri://resize", payload: {"height":1690,"width":2336}})', 'window['5ae98b93-333b-439e-a895-08f45041b522']' is undefined)
```
I'm also getting something similar when the window receives or looses focus.

---

I guess I can close this, unless the goal is to support service workers on the custom `tauri://` protocol?

**Comment by icidasset** [comment]
Not possible with custom protocols.
Use https://github.com/tauri-apps/tauri-plugin-localhost
