### ISSUE TITLE
drag_window in custom_titlebar example doesn't work with touch

### ISSUE THREAD

**Issue by PerBothner** [tauri-apps/wry#390]
When running the `custom_titlebar` example, I can move the window using a mouse-drag, but not using a finger on a touchscreen.

**Platform and Versions (please complete the following information):**
OS: Fedora Linux 34 (gtk)
Rustc: 1.54.0

**Would you assign yourself to resolve this bug?**
- [ ] Yes
- [x] No

**Additional context**
Tapping the close button (i.e. "clicking with a finger") seems to work.  I'm guessing a bug in Tao (rather than Wry per se).

**Comment by amrbashir** [comment]
The example uses a js event listener on `mousedown` event, changing that to `touchstart` should make it work with touch.

**Comment by PerBothner** [comment]
Thanks! I added the following, and that seems to work:

          document.addEventListener('touchstart', (e) => {
            if (e.target.classList.contains('drag-region')) {
              window.rpc.notify('drag_window');
            }
      })

The example should probably be modified in this way - or by using a single every-listener function for both events.

**Comment by amrbashir** [comment]
The team is a bit busy right now for these trivial things but would love to see a PR to update the example.
