### ISSUE TITLE
hover over undecorated window border does not change to resize cursor

### ISSUE THREAD

**Issue by PerBothner** [tauri-apps/wry#399]
When creating a window with `custom_titlebar`, you can resize the window by dragging a border or corner. On mousedown the cursor changes to a suitable resize-cursor.  However, the cursor does not change on mouse-hover - not until you press the mouse. It would be more expected and pleasant if the cursor changes on hover.

This is on Fedora Linux 34 with Gnome/Wayland.

Interestingly, for most Gtk applications, the cursor shape on hover (i.e. before mouse-down) is different from the one used when actually dragging (i.e. after mouse-down).  However, an  frameless Electron window uses the same for both.  Either behavior would be fine, though using different cursors would be slightly preferable.

See issue #397 .

**Comment by wusyong** [comment]
Fixed by #402
