### ISSUE TITLE
getting Wry version number

### ISSUE THREAD

**Issue by PerBothner** [tauri-apps/wry#407]
There is a `webview_version` method which (on Linux) returns the WebKitGtk version number.  However, it would be nice to have a way to get the Wry version number.  I see some code in web_context.rs that calls app_info.set_version. However, I can't find a documented (or otherwise) API to get this. (I am extremely new to Rust, so I might be missing things.)

I checked in a n experimental Wry front-end for [DomTerm](http://domterm.org).  The basics work, but it could do with a bit  of polishing. Having the Wry version number isn't important in itself, but the preferrred way to test "am I running under Wry" is to check the property `DomTerm.versions.wry`.  And I can certainly set that value to a string like `"?.?.?" - but it would be nice to have a valid version number.  A version number is also nice for an "About DomTerm" Help menu entry.

**Comment by wusyong** [comment]
You could use [cargo-metadata](https://doc.rust-lang.org/cargo/commands/cargo-metadata.html) to get the version in your cargo project. It's the `req` field of the `dependencies`.

**Comment by PerBothner** [comment]
That is certainly one solution: Run `cargo-metadata`,  filter the output (maybe using the `sed` command) to extract the wry version number, and use that to generate (at build time) a small wry-version.rs file that I can link with the application.  A bit ugly, but not very difficult.

On the other hand, if the Wry maintainers/community think it would be OK to add to the API a method (or maybe a macro?) that returns the Wry version number, that would be simpler and cleaner.  I'm new to Rust, so I don't know if such a method would be appropriate.. I'm good either way.

**Comment by wusyong** [comment]
`cargo-metadata` can parse into types it defines in code. You can build a [`MetadataCommand`](https://docs.rs/cargo_metadata/0.14.0/cargo_metadata/struct.MetadataCommand.html), get [`Metadata`](https://docs.rs/cargo_metadata/0.14.0/cargo_metadata/struct.Metadata.html#structfield.packages) from `exec` method, and then get the dependency all the way from `package` field. 

This is a utility request that can be achieved outside of this crate purpose. So it's better to do it outside imho. If you couldn't figure it out. I'll make an example repo for you.

**Comment by PerBothner** [comment]
I didn't see your edit (kindly offering to make an example) until just now. Also, would your suggestion require linking in more stuff at run-time? That would be unnecessary for my needs.  So I did this to my Makefile.am:

    dt-wry/src/versions.rs:
    	echo '// This file is automatically generated from Makefile - DO NOT EDIT!' > $@
    	WRY_VERSION=`cd dt-wry && cargo metadata --format-version=1|jq '.packages|map(select(.name=="wry"))|.[0].version'`; \
    	echo "pub fn wry_version() -> &'static str { $$WRY_VERSION }" >>$@

Works perfectly and matches exactly what I need.

For my sake feel free to close this issue.  However, if you think version numbes would be useful to add to the API - or you think it would be useful to add to one of the examples - or if this is a helpful documentation topic, then feel free to leave open.

**Comment by wusyong** [comment]
I pushed a sample repo to show how to define a function to get a dependency version. It's also simpler imho.
https://github.com/wusyong/dep_version/blob/master/src/main.rs#L3

I'll close this since this should be the recommended way to do so imho.

**Comment by PerBothner** [comment]
Nice and simple.  However,  unless I misunderstand it is only a partial solution, as it depends on Cargo.toml being available when dep_version is run - and we don't we want that as a run-time dependency.  To avoid that we would have to run dep_version at build time and incorporate the result into the executable.

**Comment by PerBothner** [comment]
Could your dep_version be turned into a macro?  I don't know enough Rust to be able to do that, if but it can be done it is probably the best approach.
