### ISSUE TITLE
Webview2 binding updates

### ISSUE THREAD

**Issue by lemarier** [tauri-apps/wry#409]
**Is your feature request related to a problem? Please describe.**
Webview2 binding are outdated

**Describe the solution you'd like**
Soft fork

**Describe alternatives you've considered**
We can contribute to the sopium repo.

**Would you assign yourself to implement this feature?**
- [ ] Yes
- [x] No

**Additional context**
There is a PR here as well
https://github.com/sopium/webview2/pull/16

related issues;
https://github.com/tauri-apps/tauri/issues/2570#issuecomment-913143578

blocker for;
https://github.com/tauri-apps/wry/pull/280

**Comment by aditsachde** [comment]
The Webview2 binding crate was just updated in https://github.com/sopium/webview2/commit/79b81f879a3608b98a6ee1b60a31b29af5d2d6ef.

**Comment by aditsachde** [comment]
Upstream bindings were just updated in sopium/webview2#18, with new releases, `webview2 0.1.3` and `webview2-sys 0.1.1`. 

There's example code for setting the user agent here https://github.com/sopium/webview2/blob/d30fbb413b8e87f2f5e7f4601cfa4789b1f84f46/examples/user_agent.rs#L195

**Comment by wusyong** [comment]
This is resolved by next branch as we now use `windows-rs` and `webview2-com` instead which can auto update and generate bindings for us.
