### ISSUE TITLE
Add the possibility to create a web window with startup flags

### ISSUE THREAD

**Issue by mynameisvasco** [tauri-apps/wry#415]
**Is your feature request related to a problem?**
 Yes, developers can't use startup flags when they instantiate new web windows.

**Describe the solution you'd like**
It's common knowledge that browsers often accept startup flags. In my personal opinion, I think that this project would benefit if such an option was provided.
For instance, in WebWindows2 there are flags that allow us to use a proxy server `--proxy-server 192.168.1.0:8080`, or to change the user data directory `--user-data-dir="/random_dir"`. 

[WebView2 startup arguments](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions.additionalbrowserarguments?view=webview2-dotnet-1.0.961.33)

**Would you assign yourself to implement this feature?**
- [x] Yes
- [ ] No

**Comment by nothingismagick** [comment]
We do already permit command line flags to be used when the app is initiated, please see:

https://tauri.studio/en/docs/usage/guides/cli

**Comment by wusyong** [comment]
But that's for the app you build right?
I think this issue is more like passing argument to webview2.
Webview2 also got some functions specific for this.

I also searched similar functions(proxy server) on Linux and macOS a few days ago.
It should be fairly easy on Linux, but become pretty difficult on mac.

**Comment by mynameisvasco** [comment]
> We do already permit command line flags to be used when the app is initiated, please see:
> 
> https://tauri.studio/en/docs/usage/guides/cli

Sorry but I think you didn't understand my proposal. 
I was talking about passing flags to the webview itself, not to my own app, as @wusyong said the issue is related to webview2 and not to my Tauri app.

**Comment by geolehmann** [comment]
As a workaround in the meantime, you can use the `std::env` crate to create a temporary environment variable (it is valid as long as the app runs) at the top of your code called "WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS" to supply arguments to the webview:
  
  `env::set_var(
        "WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS",
        "--proxy-server 192.168.1.0:8080 --user-data-dir='/random_dir'"
    );`

**Comment by nothingismagick** [comment]
While what @geolehmann suggests is definitely possible this is a VERY DANGEROUS workaround, not to mention you can't guarantee any port is available without potentially clobbering or being listened to.

**Comment by geolehmann** [comment]
> 
> 
> While what @geolehmann suggests is definitely possible this is a VERY DANGEROUS workaround, not to mention you can't guarantee any port is available without potentially clobbering or being listened to.

absolutely true, this should be only used for testing and until we have a better way of doing this.

**Comment by Archieeeeee** [comment]
I have same requirements to set proxy settings for webview. As for .net implementation, multi webview2 instances can be created and each one can be applied with individual start flags, I would like this function to move to tauri, thank you
