### ISSUE TITLE
Request header of custom protocol handler is empty

### ISSUE THREAD

**Issue by wusyong** [tauri-apps/wry#422]
Despite Webkitgtk allows registering custom protocol, the parameter `URISchemeRequest` will only contain URI. Other properties will all be empty.

I haven't filed a bug on Webkit's bugzilla since trying to propose a mcve in C is more difficult than I thought. Maybe it can be simpler than `stream_range` example?

**Comment by wusyong** [comment]
Upstream tracking issue: https://bugs.webkit.org/show_bug.cgi?id=231564

**Comment by TeFiLeDo** [comment]
The upstream issue (or rather the issue it was marked as a duplicate of) has been fixed.

**Comment by wusyong** [comment]
We'll wait for 2.36 lands on all major distro, and I'll update webkit2gtk.

**Comment by wusyong** [comment]
Fixed by #721
