### ISSUE TITLE
GLib-GIO-WARNING

### ISSUE THREAD

**Issue by Apogeum12** [tauri-apps/wry#43]
I get Warning: Your application does not implement g_application_activate() and has no handlers connected to the 'activate' signal.  It should do one of these.
For run 
```rust
cargo run --example basic
```
For me this no look to no problem with example but with gio in wry.

All Shell output:
```bash
Your application does not implement g_application_activate() and has no handlers connected to the 'activate' signal.  It should do one of these.
http://localhost:3000/static/js/vendors~main.chunk.js:39300:18: CONSOLE LOG [HMR] Waiting for update signal from WDS...
1 seconds has passed.
http://localhost:3000/:1:12: CONSOLE LOG ゴ
2 seconds has passed.
http://localhost:3000/:1:12: CONSOLE LOG ゴ
3 seconds has passed.
http://localhost:3000/:1:12: CONSOLE LOG ゴ
4 seconds has passed.
http://localhost:3000/:1:12: CONSOLE LOG ゴ
5 seconds has passed.
http://localhost:3000/:1:12: CONSOLE LOG ゴ
6 seconds has passed.
http://localhost:3000/:1:12: CONSOLE LOG ゴ
7 seconds has passed.
http://localhost:3000/:1:12: CONSOLE LOG ゴ
```

**Comment by wusyong** [comment]
Thanks for the awareness!
This is because we didn't add any event to it. We probably should add a blank one even we are not actually using it.

**Comment by wusyong** [comment]
This should be solved by the latest commit. We remove the activate signal until we need it in the future.
