### ISSUE TITLE
How can I use tauri invoke function?

### ISSUE THREAD

**Issue by katopz** [tauri-apps/wry#441]
Hi, noobs question here. 🙏

From example https://github.com/tauri-apps/tauri/blob/next/examples/api/src/App.svelte#L6
I can use `invoke` function in web app to communicate with rust.
```ts
import { invoke } from '@tauri-apps/api/tauri'
```

But I can't find anything related to `invoke` api in `wry`.
Any example to use `invoke` via `wry`?
Or maybe we don't do this here and tend to use `rpc` instead?

Thanks.

**Comment by wusyong** [comment]
Invoke is basically a wrapper around rpc method.
Note that we are continuing improve rpc's implementation since it's one of bottleneck for us.
I don't recommend use it directly unless you just want to use wry as dependency.
