### ISSUE TITLE
multi_window example too simple

### ISSUE THREAD

**Issue by PerBothner** [tauri-apps/wry#459]
This isn't really a feature request but rather a request to enhance the example applications.
Warning: I am quite new to Rust, and it is quite likely an experienced Rust programmer would not have these problems.

I'm trying to create multiple non-trivial windows in the same application.  The `examples/multi_window.rs` is a bit too simple, in that window2 is relatively simple and very different from window1.  I'd like `openWindow` to create the *same kind* of window, which means using the same `new_window` function/closure to create both.  But then I get into nasty move/ownership issues, which I haven't been able to solve, so far.

Attached is what I have so far.  It builds and runs - but as soon as I uncomment the second `new_window` call I get lots of errors.  What is the clean/recommended way to get that functionality?  (Feel free to use anything in my code that you find useful if you enhance the examples.)  The use of `"http://example.com"` is just a place-holder.  Most likely would be to enhance the `UserEvent::NewWindow` to pass suitable options from JavaScript to the rpc-handler to the event_loop handler.

[main-rs.txt](https://github.com/tauri-apps/wry/files/7786394/main-rs.txt)

Note I also used the seemingly-newer `EventLoop::with_use_event` idiom from `custom_titlebar.rs`, instead of the `mpsc::channel` logic from `multi_window.rs`.

**Comment by PerBothner** [comment]
If someone with more Rush experience has a suggestion for a general approach, I can probably work out the details.

I tried converting variables to static items. However, some of them are mutable, and mutable statics aren't thread-safe. Using a bunch of unsafe code didn't seem like a promising approach.

**Comment by lucasfernog** [comment]
Maybe paste your initial code here or Discord so we can help you.

**Comment by PerBothner** [comment]
Thank you!  I managed to modify my `dt-wry` front-end based on your example.  Running the command `domterm -Bwry` multiple times creates multiple windows using a single `dt-wry` executable. I also added support for a `--geometry` option.

The source code is [here](https://github.com/PerBothner/DomTerm/blob/master/dt-wry/src/main.rs).
