### ISSUE TITLE
Can't compile the examples, `WebView2LoaderStatic` is missing.

### ISSUE THREAD

**Issue by g-berthiaume** [tauri-apps/wry#473]
**Describe the bug**
Compiling the example on windows fails.

```shell
PS C:\dev> cargo run --example hello_world
   # ...
   Compiling webview2-com-sys v0.10.0
   Compiling webview2-com v0.10.0
error: could not find native static library `WebView2LoaderStatic`, perhaps an -L flag is missing?

error: could not compile `webview2-com-sys` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Steps To Reproduce**
Steps to reproduce the behavior: `cargo run --example hello_world`

**Platform and Versions (please complete the following information):**
OS: Windows 10 Home [64-bit]
Rustc: rustc 1.58.1 (db9d1b20b 2022-01-20)

**Comment by amrbashir** [comment]
what is your rust toolchain? do you have webview2 runtime installed?

**Comment by lucasfernog** [comment]
See https://tauri.studio/docs/faq/ and run `cargo clean` after creating the config file.

**Comment by g-berthiaume** [comment]
@lucasfernog it worked.
Thanks for the tip.
