### ISSUE TITLE
Webview Window no response

### ISSUE THREAD

**Issue by payallmoney** [tauri-apps/wry#493]
**Describe the bug**
Webview Window no response when using Alt+Tab swicth to other window and back  12 times on win10

**Steps To Reproduce**
using Alt+Tab swicth to other window and back  12 times on win10
source code "examples/hello_world.rs" 

**Expected behavior**
Webview Window  should not be no response

**Screenshots**

**Platform and Versions (please complete the following information):**
OS: win10
Rustc: rustc 1.58.0-nightly (072799443 2021-11-06)
wry : both v0.13.1 and v0.12.2 has this bug

**Would you assign yourself to resolve this bug?**
- [x] No

**Additional context**

**Comment by payallmoney** [comment]
this bug can't be  reproduce when Edge update to latest version.

**Comment by payallmoney** [comment]
This bug appear again , only when repeat more times :   using Alt+Tab swicth to other window and back  20-100 times on win10 
 @amrbashir

**Comment by amrbashir** [comment]
Probably an upstream issue with webview2.

**Comment by payallmoney** [comment]
> Probably an upstream issue with webview2.

I'm not sure ,  I use C++ write a  hello world  program using webview2.h  ,   the bug cannot be reproduced

**Comment by amrbashir** [comment]
That's good to know, we will investigate on our end.

**Comment by nothingismagick** [comment]
I really wonder how we can make automated tests for this behaviour, because it seems super flaky. I will see if I can achieve the same result on macOS.

**Comment by nothingismagick** [comment]
So I just `<command> + <tab>` switched a prod version of a tauri app a couple dozen times, and while the memory pressure went up a little bit, it really didn't make much difference and it stabilized really quickly.

**Comment by nothingismagick** [comment]
A couple more questions though: 
- Are you actually building a binary, or is this a `cargo run` type of test?
- Have you updated to latest rust? (1.59.0)

**Comment by payallmoney** [comment]
> 



> A couple more questions though:
> 
> * Are you actually building a binary, or is this a `cargo run` type of test?
> * Have you updated to latest rust? (1.59.0)
* Both  cargo run and Release version has this bug ,
* Rust version is  1.58.0-nightly (072799443 2021-11-06)

**Comment by amrbashir** [comment]
I can't reproduce this at all on my machine.
```
› OS: Windows 10.0.22000 X64 (Windows 11)
› Webview2: 99.0.1150.55
```

Feel free to reopen the issue if you encounter it again and try to post a video recording of it.
