### ISSUE TITLE
feat: expose native handles to the underlying webview type

### ISSUE THREAD

**Issue by kt215** [tauri-apps/wry#495]
How do I set TLSErrorsPolicy to Ignore using set_tls_errors_policy on WebContext/DataManager?

Is there a configuration setting for this?

**Comment by amrbashir** [comment]
We currently don't expose that and I don't think we should do it and I think we should expose handles to the underlying platform-specific Webview type. 

We are currently exposing Webview2 Controller, so only Webkit2gtk and WkWebView handles are missing.

**Comment by kt215** [comment]
Thanks for considering this. I'm trying to connect a Tauri app to a server with a self-signed SSL certificate, which fails.

This works fine with a PWA app (chromium) since I'm able to add a custom root certificate on the client side.

I barely started learning rust, but I have the latest Tauri source code, so where would be the best place to hack this for now so my Tauri client app accepts self-signed server certificates?

**Comment by amrbashir** [comment]
We first need to expose the native handles and afterwards tauri can expose the same handles.
