### ISSUE TITLE
comment typos "insepctor"

### ISSUE THREAD

**Issue by PerBothner** [tauri-apps/wry#501]
$ grep insepctor src/**/*.rs
    src/webview/mod.rs:  /// Enable web insepctor which is usually called dev tool.
    src/webview/mod.rs:  /// Enable web insepctor which is usually called dev tool.
    src/webview/mod.rs:  /// Open the web insepctor which is usually called dev tool.
    src/webview/webkitgtk/mod.rs:  /// Open the web insepctor which is usually called dev tool.
    src/webview/webview2/mod.rs:  /// Open the web insepctor which is usually called dev tool.
    src/webview/wkwebview/mod.rs:  /// Open the web insepctor which is usually called dev tool.

**Comment by sacred-mercy** [comment]
Hello, I am new to open source can anyone guide me in which file this issue persist and do I have to change just spelling or any other work too.

**Comment by PerBothner** [comment]
`grep` is a old-time Unix command to search for lines in files that match a pattern. The important thing is not the `grep` command but the output: In the output, the part before the colon is the name fo the file (in the Wry source repository) containing the matching line,  These are all comment lines containing the misspelled word "insepctor".

**Comment by nothingismagick** [comment]
Thanks for wanting to contribute. We have a guide for contributors here:

https://github.com/tauri-apps/tauri/blob/dev/.github/CONTRIBUTING.md

Basically, make sure codesigning is setup, clone the repo, replace the misspellings, push to a new branch on your fork, make a PR to here from your fork.

Enjoy!

**Comment by sacred-mercy** [comment]
Yes, I will do the work you can assign me issue.

**Comment by sacred-mercy** [comment]
Thank You @nothingismagick and @amrbashir for guiding me in my first PR
