### ISSUE TITLE
Doc.rs of macOS and Windows aren't built

### ISSUE THREAD

**Issue by wusyong** [tauri-apps/wry#503]
The docs of Mac and Windows are missing after 0.13.
This is probably because of `thiserror`. Its recent patch version only generates linux target.
And on Windows, it's also because of sys-info. Since it's only used for detecting windows 7, we could add our own helper function instead.

**Comment by chippers** [comment]
> The docs of Mac and Windows are missing after 0.13. This is probably because of `thiserror`. Its recent patch version only generates linux target. And on Windows, it's also because of sys-info. Since it's only used for detecting windows 7, we could add our own helper function instead.

`serde` and family also use the same settings, it's common if there is no platform-specific behavior because linux is seen as the "default" docs.rs runner. That setting on `serde` has been set for 2 years

**Comment by amrbashir** [comment]
> And on Windows, it's also because of sys-info. Since it's only used for detecting windows 7, we could add our own helper function instead.

I already done that in the vibrancy plugin https://github.com/tauri-apps/tauri-plugin-vibrancy/blob/e4ffde2a9f87c666858a74afa15f73de8aaa3ca0/src/platform/windows.rs#L72 and lucas mentioned that we probably need to put all these utils in some sort of a crate.

**Comment by wusyong** [comment]
After a few test, I can confirm it's actually caused by objc_excpetion on macOS.
And since it's pretty useless (it basically just print the log from message of objc stack unwinds and the runtime already does that), I think we can just disable that feature.

**Comment by lucasfernog** [comment]
@wusyong check with the auditors about that, anyway you could also just disable it when building for docs.rs

**Comment by tweidinger** [comment]
> After a few test, I can confirm it's actually caused by objc_excpetion on macOS. And since it's pretty useless (it basically just print the log from message of objc stack unwinds and the runtime already does that), I think we can just disable that feature.

The `objc_excpetion ` feature also wraps all !msg_send calls in a try catch, which tries to reduce/avoid having undefined behaviour introduced from the objc code, which is afaik not handled by the default rust runtime.

```
By default, if the msg_send! macro causes an exception to be thrown, this will unwind into Rust resulting in unsafe, undefined behavior. However, this crate has an "exception" feature which, when enabled, wraps each msg_send! in a @try/@catch and panics if an exception is caught, preventing Objective-C from unwinding into Rust.
```

> just disable it when building for docs.

Sounds like a reasonable tradeoff.
I think it should be fine to be disabled for doc generation but I would rather avoid completely disabling this feature.

_EDIT:_ Nevermind the comment above :) 
https://github.com/tauri-apps/wry/blob/327a019a07fd10ca3a42ebfb8d9d626e3b91fd05/Cargo.toml#L25
introduced the exception feature as default.
