### ISSUE TITLE
Is there any way to call JavaScript function from the Rust backend?

### ISSUE THREAD

**Issue by TabulateJarl8** [tauri-apps/wry#506]
**Describe the bug**
I can't seem to find a way to call a JavaScript function from the Rust backend. I saw #66 which seems to have led to some PRs being merged, but I can't find any of the code in this repository. What happened to this, and it there any way currently to invoke JavaScript function from Rust?

**Would you assign yourself to resolve this bug?**
- [ ] Yes
- [x] No

**Comment by amrbashir** [comment]
tldr: call `webview.evaluate_script()`

You have declare your javascript functions on the `window` object and then evaluate a script that calls this function.

Example:
```js
window.greet = (name) => {
  console.log(`hi ${name}`)
}
```
then to call it you do
```rs
webview.evaluate_script("window.greet('Jack')");
```

**Comment by TabulateJarl8** [comment]
Thanks! Is there any way to call this from within the ipc handler function or do I have to do it some other way? I can't seem to figure out how to pass the webview object to my ipc handler function since the ipc handler is set before the webview is created. Again, thanks for the help.

**Comment by amrbashir** [comment]
Store the webviews in a static variable, something like:
```rs
thread_local!​ { 
 ​  ​static​ WEBVIEWS: RefCell​<​ HashMap​<​WindowId, WebView​>>​ ​=​ RefCell​::​new​(HashMap​::​new​()); 
 ​} 
```
then in ipc handler
```rs
WEBVIEWS.​with​(​|​webviews​|​ { 
  let​ webviews ​=​ webviews.​borrow​(); 
  if​ ​let​ ​Some​(wv) ​=​ webviews.​get​(​&​window.id()) {
    wv.​evaluate_script​("call-your-function-here"); 
  }
}); 
```

**Comment by TabulateJarl8** [comment]
Thank you!
