### ISSUE TITLE
No examples showing usage of window icon

### ISSUE THREAD

**Issue by TabulateJarl8** [tauri-apps/wry#508]
**Describe the bug**
There aren't any examples showing the usage of adding a window icon. I personally can't figure out how to get it to work, and an example would help greatly

**Expected behavior**
I think there should be an example showcasing the usage of this feature. It would be especially helpful if it used `include_bytes!()` or something to include the image into the binary.

**Platform and Versions (please complete the following information):**
OS: Arch Linux
Rustc: 1.58.1

**Would you assign yourself to resolve this bug?**
- [ ] Yes
- [x] No

**Comment by nothingismagick** [comment]
This isn't a bug, just a documentation request. Also, as a reminder, this library is a service library for tauri. So if you are looking for more examples, then looking into tauri should help.

E.g. https://docs.rs/tauri/1.0.0-rc.0/src/tauri/window.rs.html#727-729

**Comment by FabianLars** [comment]
Furthermore the icon stuff comes from https://github.com/tauri-apps/tao (re-exported via the application module as stated in the docs&readme).
Therefore you can find the icon example over there instead: https://github.com/tauri-apps/tao/blob/dev/examples/window_icon.rs

With that said I'd tend to close this issue as the example would basically be a duplicate :shrug:

**Comment by TabulateJarl8** [comment]
Ah, thanks! Before I close the issue, would you happen to know how to do this with `include_bytes!()` instead of with a path? I couldn't find a way to do that with the image crate, other than maybe writing the included image to a tempfile and passing that to image. Either way, thanks again for the help

**Comment by TabulateJarl8** [comment]
Nevermind, I found the [`load_from_memory_with_format`](https://docs.rs/image/0.19.0/image/fn.load_from_memory_with_format.html) method in the image crate. My resulting code was this:

```rs
let bytes: Vec<u8> = include_bytes!("icon.png").to_vec();
let imagebuffer = image::load_from_memory_with_format(&bytes, ImageFormat::Png).unwrap().into_rgba8();
let (icon_width, icon_height) = imagebuffer.dimensions();
let icon_rgba = imagebuffer.into_raw();

// and then in the window initialization
.with_window_icon(Some(Icon::from_rgba(icon_rgba, icon_width, icon_height).unwrap())) 
```
Thanks again for all of the help!

**Comment by nothingismagick** [comment]
Nice solution. Would you care to preserve your work and PR the tao crate with a new example?

**Comment by TabulateJarl8** [comment]
Sure! Would you like me to add a new example entirely or would you prefer me to somehow add onto the old one?

**Comment by nothingismagick** [comment]
I think a new one makes sense.
