### ISSUE TITLE
with_html views containing iframes can panic

### ISSUE THREAD

**Issue by robertream** [tauri-apps/wry#523]
**Describe the bug**
with_html views containing iframes can panic

**Steps To Reproduce**
1) Modify the hello_world example to use static html with an iframe instead of a url:
`.with_html(r#"<iframe sandbox seamless src="https://www.html5rocks.com/"></iframe>"#)?`
2) Run the hello_world example
3) scroll to the bottom of the iframe
4) process panic

**Expected behavior**
The process should not crash, at worst, the page should just not render.

**Platform and Versions (please complete the following information):**
OS: MacOS 12.2.1
Rustc: 1.59.0

**Would you assign yourself to resolve this bug?**
- [ ] Yes
- [x] No

**Comment by keiya01** [comment]
This issue is not occurred on my macOS.
