### ISSUE TITLE
Even if I delete it, WebView (or other?) remains.

### ISSUE THREAD

**Issue by tasuren** [tauri-apps/wry#536]
**Describe the bug**
Let's say you have a program that creates a window to play videos.
And when I created multiple of them and then deleted some, the video in the browser that I had deleted would still be playing.

**Steps To Reproduce**
Prepare code of `wry/examples/multi_window.rs`.
Add a below snipet (YouTube embed) to [here str](https://github.com/tauri-apps/wry/blob/313eaea0ff123bddbc8b5c337ded05d464d3dfaa/examples/multi_window.rs#L52).
```html
<iframe class="background" id="background" 
src="https://www.youtube.com/embed/JUGHD_YWOe4?iv_load_policy=3&amp;loop=1&amp;playlist=JUGHD_YWOe4&amp;control=0&amp;fs=0&amp;mute=On&amp;end=111&amp;modestbranding=1&amp;start=11&amp;autoplay=1" 
frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; 
picture-in-picture" allowfullscreen="" style="width: 1191px; height: 678px;"></iframe>
```
Create about five windows every almost few seconds.
After a while, when it gets too noisy, close the window a little at a time and try to get only one.
Then it remains noisy.
So the closed window is still in motion.

**Expected behavior**
To be successfully closed.

**Screenshots**
Nothing

**Platform and Versions (please complete the following information):**
OS: macOS 12.3
Rustc: 1.59.0

**Would you assign yourself to resolve this bug?**
- [ ] Yes
- [x] No

**Additional context**
Nothing

**Comment by keiya01** [comment]
This case seems to occur on MacOS :eyes:

**Comment by keiya01** [comment]
And I could reproduce this issue on MacOS.

**Comment by ahkohd** [comment]
Will this help? https://stackoverflow.com/questions/21161406/freeing-ios-uiwebview-resources-after-usage

```objc
-(void) dealloc
{

    [self.webview cleanForDealloc];
    self.webview = nil;
    [super dealloc];

}

```

**Comment by FabianLars** [comment]
I think it's this one: <https://stackoverflow.com/questions/58454042/wkwebview-instances-and-memory-leak>

I tried to test it, but i can't get obj-c to cooperate with me :joy: 

On that note i'm going to re-open this issue because we're leaking memory right now because of this.

**Comment by keiya01** [comment]
I try to fix this issue based on https://github.com/tauri-apps/wry/issues/536#issuecomment-1120459496.
I would appreciate if you review https://github.com/tauri-apps/wry/pull/587 :pray:

**Comment by keiya01** [comment]
Also maybe we need to remove WKWebsiteDataStore by using [removeDataOfTypes](https://developer.apple.com/documentation/webkit/wkwebsitedatastore/1532938-removedataoftypes?language=objc).
