### ISSUE TITLE
Known issues with cargo-play for Android and iOS

### ISSUE THREAD

**Issue by wusyong** [tauri-apps/wry#540]
As our [instruction](https://hackmd.io/XIcEwk4GSxy8APZhSa0UnA?view) note for android and ios states, there are some steps require different commands or fixes depending on different architecture. Ideally, we should just type `cargo apple/android build/run` and use each IDE without any modification.

Here are some issues around Android:
- [ ] need to add `abiFilters += listOf("arm64-v8a")` under `create("arm")` branch in `:app`'s '`build.gradle.kts` if you use arm laptop like M1.
- [ ] `cargo android run` doesn't work because SDK tools' path aren't exported.
- [ ] The library won't be built if it's built from Android Studio, so we need to build the library first and then hit the run button.

And here are iOS's:

- [ ] `cargo apple build` doesn't work for xcode, and require running `cargo build --target x86_64-apple-ios` manually.
- [ ] The library won't be built if it's built from Xcode, so we need to build the library first and then hit the run button.

**Comment by amrbashir** [comment]
I think all these issues are fixed now or at least documented in the hackmd note.
