### ISSUE TITLE
gap property of css is not supported in tauri

### ISSUE THREAD

**Issue by kaichaosun** [tauri-apps/wry#550]
**Describe the bug**
when change the gap property, it's not make any change in the window, but changes works in browser.

**Steps To Reproduce**
```
git clone git@github.com:perspect3vism/ad4min.git

npm install

npm start

./scripts/setup-binaries.sh # it download a sidecar binary used in the project

npm run tauri dev
```

**Expected behavior**
The gap property should works exactly like in browser.

**Screenshots**
Browser screenshot,
<img width="816" alt="image" src="https://user-images.githubusercontent.com/10568673/162972862-35987e4d-ed72-4a18-824b-2afd3fea7bb2.png">

Tauri screenshot,
<img width="562" alt="image" src="https://user-images.githubusercontent.com/10568673/162972977-4921e49b-af98-4b22-8854-88df43f5ff0f.png">

**Platform and Versions (please complete the following information):**
```
> tauri "info"


Operating System - Mac OS, version 10.14.6 X64

Node.js environment
  Node.js - 14.16.1
  @tauri-apps/cli - 1.0.0-rc.6 (outdated, latest: 1.0.0-rc.8)
  @tauri-apps/api - 1.0.0-rc.2 (outdated, latest: 1.0.0-rc.3)

Global packages
  npm - 6.14.12
  pnpm - Not installed
  yarn - 1.22.10

Rust environment
  rustup - 1.24.3
  rustc - 1.61.0-nightly
  cargo - 1.61.0-nightly
  toolchain - nightly-x86_64-apple-darwin

App directory structure
/node_modules
/public
/scripts
/.github
/src-tauri
/.git
/src

App
  tauri - 1.0.0-rc.4
  tauri-build - 1.0.0-rc.4
  tao - 0.6.4
  wry - 0.13.3
  build-type - bundle
  CSP - unset
  distDir - ../build
  devPath - http://localhost:3000/
  framework - React
```

**Would you assign yourself to resolve this bug?**
- [ ] Yes
- [x] No

**Comment by FabianLars** [comment]
This is not a wry bug, but a limitation of webkit. You can check the `safari` section in [caniuse.com](https://caniuse.com/?search=gap) to see if features you want are supported. Note that webkit versions are only updated on macOS version updates and don't need to match the latest available safari version.
In case of your pretty old macOS version it should match safari@v12. We have a temporary version matrix here: https://jonaskruckenberg.github.io/tauri-docs-wip/appendix/version-tables.html
