### ISSUE TITLE
Is there a plan to support custom userAgent?

### ISSUE THREAD

**Issue by sukechris** [tauri-apps/wry#552]
### Describe the problem

Hi, Thank you for your great work! I encountered a problem, inside some JavaScript library, they use `navigator.userAgent` to detect device, like this:
```javascript
// "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15"
/Version\/[\d\.]+.*Safari/.test(navigator.userAgent)
```
Howerver, `navigator.userAgent` in Tauri webkit, like this:
```javascript
// navigator.userAgent
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko)"
```
The expected device is not matched by `navigator.userAgent`.

### Describe the solution you'd like

Is there a plan to support custom userAgent?

**Comment by amrbashir** [comment]
I think you misunderstood me. `wry` does have this feature already. `tauri` needs to just expose it in its API. I will reopen the issue on `tauri` repo and close this.

**Comment by sukechris** [comment]
@amrbashir my bad, I got it
