### ISSUE TITLE
Set scroll bounce on WKWebView

### ISSUE THREAD

**Issue by promontis** [tauri-apps/wry#557]
MacOS has this bounce effect when you scroll. I would like to disable it. I think it is `webView.scrollView.bounces = NO;`. I think the default should be `false`, like it is in for example Electron.

**Describe alternatives you've considered**
Tried to do this in CSS, but I couldn't find a working solution so far. I've read that adding a certain class to all of the elements in the DOM fixes it, or applying some JS, but it is a real hassle. Most people suggest just setting the bounces property to NO.

**Would you assign yourself to implement this feature?**
- [ ] Yes
- [x] No

**Additional context**
None

**Comment by wusyong** [comment]
macOS doesn't have scrollView. You can see it's [only supported on iOS](https://developer.apple.com/documentation/webkit/wkwebview/1614784-scrollview?language=objc).
There is also a StackOverflow [issue](https://stackoverflow.com/questions/39929552/disable-bounce-scrolling-for-wkwebview-in-macos) mentioned about this.
So on macOS, we can only use workaround in #558.
For iOS, we could add it once it has alpha release on tauri.

**Comment by f91kdash** [comment]
CSS solution:
```
<style>
    html { overscroll-behavior: none; }
</style>
```

**Comment by amrbashir** [comment]
Closing this as we merged a PR to solve this a while ago for iOS, as for macOS, please use the CSS solution.
