### ISSUE TITLE
data:text/html shows in html output

### ISSUE THREAD

**Issue by jussiniinikoski** [tauri-apps/wry#56]
**Describe the bug**
data:text/html prefix shows in html output

**Steps To Reproduce**

```rust
use wry::Result;
use wry::{Application, Attributes};

fn main() -> Result<()> {
    let mut app = Application::new()?;

    let attributes = Attributes {
        url: Some(
            r#"data:text/html,
            <!doctype html>
            <html>
              <body>Hello</body>
            </html>"#
                .to_string(),
        ),
        ..Default::default()
    };

    app.add_window(attributes, None)?;
    app.run();
    Ok(())
}
```

**Expected behavior**
Should not output data:text/html

**Platform and Versions (please complete the following information):**
OS: Macos
Rustc: 1.50

**Would you assign yourself to resolve this bug?**
- [x] Yes (if needed)
- [ ] No

**Additional context**
Something like this could help

```rust
// macos.rs, line 152:
// Navigation
if let Some(url) = url {
    if url.cannot_be_a_base() {
        let url_str = url.as_str();
        let url_str = if url_str.starts_with("data:text/html,") {
            &url_str[15..]
        } else {
            url_str
        };
        w.navigate_to_string(url_str);
        // w.navigate_to_string(url.as_str());
    } else {
        w.navigate(url.as_str());
    }
}
```

**Comment by wusyong** [comment]
Thanks for the report! I used split method to get the actual HTML string. [41e6af2](https://github.com/tauri-apps/wry/commit/41e6af2ca606de0cb6f7509e78a9840cf80bef0c) should be able to fix this.

**Comment by jussiniinikoski** [comment]
Unfortunately splitting won't work if the data url contains other commas, such as 

```
<body>Hello, world!</body>
```

**Comment by wusyong** [comment]
Ah you are right!
just fixed it again. This time should be correct I think.

**Comment by jussiniinikoski** [comment]
Yes, thank you!
