### ISSUE TITLE
WebView2: Some default platform shortcuts are disabled, some are not

### ISSUE THREAD

**Issue by JensMertelmeyer** [tauri-apps/wry#569]
**Describe the bug**
By default, you can zoom in and out by
1. [Ctrl] + [minus] / [plus]
2. [Ctrl] + [Mousewheel]
3. Two-finger-pinch on trackpad
4. Two-finger-pinch on touchscreen

Currently, wry disables option 1 and 2, but option 3 and 4 are still possible.

**Steps To Reproduce**
* `cargo run --example hello_world`
* You cannot zoom by [Ctrl] + [+ / -] or [Ctrl] + [Mousewheel]
* You can, however, zoom in by using a trackpad or touchscreen

**Expected behavior**
Zooming in and out should either be enabled for all platform shortcuts or for none.
Ideally, it should be configurable, whether zoom is allowed or not.

**Screenshots**

https://user-images.githubusercontent.com/1827784/166817974-4aacf374-7616-4d1f-a00c-690fbddac350.mp4

**Platform and Versions (please complete the following information):**
OS: Windows 10
Rustc: 1.60

**Would you assign yourself to resolve this bug?**
- [x] Yes
- [ ] No

**Additional context**
I have a PR ready that will add a `with_zoom(bool)` to the WebViewBuilder which enables or disables all of the four ways to zoom (only implemented for Windows/WebView2). Please let me know if I can submit it for review.

**Comment by keiya01** [comment]
We added zoom feature in https://github.com/tauri-apps/wry/issues/388 but we need to implement shortcuts manually.

**Comment by JensMertelmeyer** [comment]
#388 added the option to manually set the zoom level in wry.
I took the above video with your (most welcome! ❤) changes from #388 already in place.

But I disagree that we should try to "imitate" the platform default shortcuts by implementing it manually again when we can, instead, just use them because it's already there.

I am suggesting to have an option to enable or disable the default platform zooming behaviour.

Right now, zooming by keyboard and mouse wheel is always off
https://github.com/tauri-apps/wry/blob/6e6ecfd3950761494887243f7400907ae31784c6/src/webview/webview2/mod.rs#L215-L216

... while zooming by touch screen or trackpad is always enabled. This is not consistent.

**Comment by amrbashir** [comment]
lets see a PR and probably just disable it without providing any options
