### ISSUE TITLE
Command+Q (quit) / Command+A (select all) / Command+C (copy) / Command+V (paste) do not work on Mac OS X

### ISSUE THREAD

**Issue by brandonros** [tauri-apps/wry#571]
**Describe the bug**

With `wry` application in focus, press Command+Q. Expect it to quit the app, it does nothing (it makes an operating system noise to acknowledge the keydown/keyup)?

Inside a textbox, Command+A does not select all contents. Command+V does not paste. Command+C does not copy.

**Comment by vdvman1** [comment]
Have you setup a menu for the app? On MacOS the menu has to have an item for the shortcut for the shortcut to work

**Comment by amrbashir** [comment]
I assume you are on macOS, in this case, you need to add a menu that contains Copy, Paste, Cut, Select All and Quit native menu items. You can use `wry::application::menu` module for that.

**Comment by brandonros** [comment]
for anybody who lands on this: https://github.com/tauri-apps/tao/releases/tag/tao-v0.22.0
