### ISSUE TITLE
Some native alert API invoked from JavaScript are not working

### ISSUE THREAD

**Issue by keiya01** [tauri-apps/wry#584]
**Is your feature request related to a problem? Please describe.**
`window.alert()` and `window.prompt()` are not working on MacOS.

**Describe the solution you'd like**
Display dialog when window.alert() and window.prompt are invoked.

**Describe alternatives you've considered**
We can use [dialog api](https://tauri.studio/v1/api/js/modules/dialog/) in tauri.
Is there the reason why Tauri has a dialog api?

**Would you assign yourself to implement this feature?**
- [x] Yes
- [ ] No

**Additional context**

**Comment by lucasfernog** [comment]
Did you enable the `dialog > message` allowlist in the tauri.conf.json?
Also we're not injecting our API in `window.prompt` yet so it won't work.

**Comment by keiya01** [comment]
> Did you enable the dialog > message allowlist in the tauri.conf.json?

I see. But is there reason why not use window.alert?

And could I try to implement window.prompt?

**Comment by keiya01** [comment]
I understood some reason about using dialog.

https://github.com/electron/electron/issues/472
