### ISSUE TITLE
Allow setting proxy settings

### ISSUE THREAD

**Issue by SoniEx2** [tauri-apps/wry#588]
**Is your feature request related to a problem? Please describe.**

We're trying to embed overlay networks into our project.

**Describe the solution you'd like**

We need to set an HTTP or SOCKS proxy for use with the overlay networks.

**Describe alternatives you've considered**

Wrapping HTTP over a custom protocol is not a suitable alternative. It comes with too many drawbacks.

**Would you assign yourself to implement this feature?**
- [ ] Yes
- [x] No

**Additional context**

**Comment by FabianLars** [comment]
https://github.com/tauri-apps/wry/pull/1006
