### ISSUE TITLE
Please remove tray and ayatana-tray from default features

### ISSUE THREAD

**Issue by akhilman** [tauri-apps/wry#594]
**Is your feature request related to a problem? Please describe.**
I am unable to compile a [Dioxus](https://dioxuslabs.com/) UI project on Fedora.
Dioxus uses wry with default features as a dependency of the desktop target. Wry by default requires `libayatana-appindicator3`, but Fedora does not have a package with this library in its repository.
Moreover, in many cases the tray is not actually needed and this feature should be opt-in.

**Describe the solution you'd like**
Remove `tray` and `ayatana-tray` features from defaults.

**Describe alternatives you've considered**
I can not see any alternatives beside forking wry or dioxus.

**Would you assign yourself to implement this feature?**
- [X] Yes
- [ ] No

**Comment by FabianLars** [comment]
We're working on the appindicator feature (flags) right now, see [here](https://github.com/tauri-apps/tao/pull/404) for a start.

Apart from that you should probably ask the Dioxus maintainers to disable wry's default features for a quicker solution (they'd need to manually update wry anyway if we'd remove it from the default features)
