### ISSUE TITLE
All requests show up in Wry as GET requests without body or headers.

### ISSUE THREAD

**Issue by aarchangel64** [tauri-apps/wry#614]
**Describe the bug**
No matter what I call to `fetch()` in JS or add to HTML forms, all requests seem to show up as GET requests with only the URI, and no headers or body data. 

**Steps To Reproduce**
1. To see the issue, add `dbg!(request)` to [line 26 of form_post](https://github.com/tauri-apps/wry/blob/e8d9bbc2704fa614fc623a7c49f82d1f7c1db05e/examples/form_post.rs#L26) so it looks like this:
```Rust
    .with_custom_protocol("wry".into(), move |request| {
      dbg!(request)
      if request.method() == Method::POST {
```
2. Run `cargo run --example form_post`
3. Submit the form.
4. Optionally, try using `fetch()` from the Dev Console.

**Expected behavior**
The `request` object in Rust should have the correct method (in this specific case, POST) and should contain the form data and headers.

**Screenshots**
This is the console output, note the second request is a GET request but _should_ be a POST request with the form data. 
```
Wry application started!
[examples/form_post.rs:27] request = Request {
    method: GET,
    uri: "wry://examples/form.html",
    headers: {},
    body: [],
}
[examples/form_post.rs:27] request = Request {
    method: GET,
    uri: "wry://examples/form.html#",
    headers: {},
    body: [],
}
```

**Platform and Versions (please complete the following information):**
OS: Arch Linux
Rustc: 1.61.0 (fe5b13d68 2022-05-18)

**Would you assign yourself to resolve this bug?**
- [ ] Yes
- [x] No

**Comment by aarchangel64** [comment]
So I see that this functionality is not yet implemented for webkitgtk / Linux, as per [here](https://github.com/tauri-apps/wry/blob/e8d9bbc2704fa614fc623a7c49f82d1f7c1db05e/src/webview/webkitgtk/web_context.rs#L227). Could this be mentioned in the documentation or the example README? Is this planned to be implemented?

Thanks!

**Comment by amrbashir** [comment]
webkit2gtk didn't have support for headers in the custom protocol until recently in [v2.36](https://webkitgtk.org/2022/03/21/webkitgtk2.36.0-released.html) but some distros doesn't have the package in their packages repo yet so it is gotta wait for a while.

**Comment by amrbashir** [comment]
Also this is documented in https://docs.rs/wry/latest/wry/http/struct.Request.html and https://docs.rs/wry/latest/wry/http/struct.Response.html and subscribe to https://github.com/tauri-apps/wry/issues/422 for more info.

**Comment by chairmanwow** [comment]
It's been 4 months since the bug and 6 since v2.36 released. Would you all accept a pull request for this?
