### ISSUE TITLE
Webview frozen until mouse moves on Windows

### ISSUE THREAD

**Issue by AmionSky** [tauri-apps/wry#616]
**Describe the bug**
On windows (webview2) after clicks sometimes noting happens until the mouse moves or until ~2 second passes.
The bug was discussed before at https://github.com/tauri-apps/tauri/issues/3691

**Steps To Reproduce**
```cargo run --example hello_world```
Open and close the hamburger menu by clicking on it and don't move the mouse
Sometimes it won't open instantly but a second later

**Expected behavior**
Menu opens/closes instantly always

**Platform and Versions (please complete the following information):**
OS: Windows 11 Pro 22000.739
Rustc: 1.61.0 (fe5b13d68 2022-05-18)

**Would you assign yourself to resolve this bug?**
- [ ] Yes
- [x] No

**Additional context**
Last working commit: https://github.com/tauri-apps/wry/commit/3a6eefae66c41da0f09293911675cb3c094e58b5
First commit with the bug: https://github.com/tauri-apps/wry/commit/219d20ce66a6bdf6c3e1af6156c9f2a74f2eed29

Since that commit is a merge and the commits inside of it are tricky to build I'm not certain of this but the possible culprit:
https://github.com/tauri-apps/wry/pull/414 (https://github.com/tauri-apps/wry/pull/477/commits/e056fb2a15e29de1b8ed85a548cfeb1f85031357)

From my testing the [webview2-rs](https://github.com/wravery/webview2-rs/tree/main/crates/webview2-com) example does not have this issue

**Comment by wusyong** [comment]
I found that it won't happen if control flow is poll, and Device Motion Events seem sending like crazy.
Might worth it to replace tao with winit and test it.

Edit: I can confirm it begins from this commit https://github.com/tauri-apps/wry/commit/e056fb2a15e29de1b8ed85a548cfeb1f85031357
This is exact commit we switch to webview2-com

**Comment by wusyong** [comment]
Okay, I got some new findings. I tried more approaches like creating the minimum webview, use `winit` instead, and toggle several options. They all failed. Here is the branch I tested: https://github.com/tauri-apps/wry/tree/wv2-frozon-where-es-mah-suit

What's interested is if I don't call any Windows API in `thread_event_target_callback`, the freeze is gone. So you either turn to `ControlFlow::Poll`, or remove the event target callback in tao's implementation.

I'll try to see if I can recreate it in `webview2-rs`.

**Comment by McZazz** [comment]
Is this the ControlFlow::Poll in "event_loop.rs" (found in the .cargo\registry\src\github**somenumber**\tao-0.11.2\src\platform_impl\windows folder)? I poked around with it for a bit, but am unable to even hack this file to bits such that it causes a panic, or build failure, or gives any response showing that my changes are propagating to a build.

Is there some step prior to or in addition to doing "cargo tauri build" that I should do to make sure whatever I change in the dependency source code reflects in a build?

I have literally all summer to figure it out :D

**Comment by wusyong** [comment]
@McZazz Thanks for willing to help!
I have a fix in https://github.com/tauri-apps/tao/pull/427. But I'm still testing if this will bring any subtle change.

**Comment by wusyong** [comment]
We have lighter PR in https://github.com/tauri-apps/tao/pull/465
But it probably need some more tests.

**Comment by AmionSky** [comment]
Tried https://github.com/tauri-apps/tao/pull/465 but it does not seem to fix this issue

**Comment by wusyong** [comment]
@AmionSky Did you try with `DeviceEventFilter::Always`?

**Comment by AmionSky** [comment]
@wusyong I have not. Sorry. With the filter set it fixes this

**Comment by Specy** [comment]
i'm also having the same issue

**Comment by rgwood** [comment]
I've been experiencing this in Tauri for a while. It's a little difficult to understand how `wry` and the fix in `tao` relate to Tauri; am I correct in understanding that the fix can't be used in Tauri yet?

**Comment by FabianLars** [comment]
@rgwood In theory you can tell Cargo to use only wry from git, but iirc wry and tauri changed a bit too much compared to 1.0.5 so you probably need to use tauri from git instead, see https://tauri.app/v1/guides/faq#how-can-i-use-unpublished-tauri-changes

**Comment by amrbashir** [comment]
this now has landed in tauri, do you still face the same issue?

**Comment by AmionSky** [comment]
Looks like it's fixed. No longer have the issue in wry or tauri.
