### ISSUE TITLE
Slow CSS animation performance on Linux.

### ISSUE THREAD

**Issue by aarchangel64** [tauri-apps/wry#617]
**Describe the bug**
CSS seem animations / transitions to be much slower than in Chromium and Firefox (at least on Linux). You can notice this if you go to pages that make heavy use of CSS animations. 

~~If I use a transparent window especially, I get low FPS / stuttering even on a simple page with only a few CSS animations.~~ EDIT: This is incorrect, apologies.

Using [this benchmark](https://greensock.com/js/speed.html), with the engine set to CSS Transitions and number of Dots set to 50, I get these results:

- Vivaldi Browser (Chromium): ~100 FPS
- Epiphany Browser: ~14 FPS
- Wry (hello_world.rs): ~14 FPS

Note the Epiphany browser is also slow, so to me this seems to be an issue with WebKit. 

**Steps To Reproduce**
1. Edit the hello_world.rs example to go to this URL: https://greensock.com/js/speed.html (or any other CSS animation heavy page)
2. Run `cargo run --example hello_world --release`
3. If using the above benchmark, set "Engine" to CSS Transitions and "Dots" to a small amount (I used 50).

**Expected behavior**
CSS animations should be smooth like in Firefox or Chromium. The FPS should be comparable to other browsers.

**Screenshots**
Video of the benchmark running in Wry:
https://user-images.githubusercontent.com/13304815/174199291-461be883-55ab-42f3-81e3-be35c87855b7.mp4

**Platform and Versions (please complete the following information):**
OS: Arch Linux
Rustc: 1.61.0 (fe5b13d68 2022-05-18)

**Would you assign yourself to resolve this bug?**
- [ ] Yes
- [x] No

**Additional context**
Hardware:  AMD Ryzen 3900X, Nvidia GTX 980ti, 32GB RAM.

**Comment by aarchangel64** [comment]
I've also just noticed that there's stuttering on that page when moving the mouse, no matter the selected engine. Curious thing is, it _doesn't_ stutter in Epiphany, so that seems like an issue in Wry?

Video of stuttering:
https://user-images.githubusercontent.com/13304815/174200010-274d5565-7e1e-4550-b4c2-338d36f98513.mp4

**Comment by aarchangel64** [comment]
I was a little stupid, and I was moving my mouse while testing transparent windows, which caused the stuttering I mentioned above. From a cursory search I can't find this problem being reported previously, so I'll make yet another issue about it.

**Comment by wusyong** [comment]
Closed by #618
