### ISSUE TITLE
showWindowAfterResourcesLoadFinish

### ISSUE THREAD

**Issue by clysto** [tauri-apps/wry#636]
**Is your feature request related to a problem? Please describe.**
For example, if I have an html page with black background, the application will start with white (for a short moment) and then change to black, which is not good for the user.

**Describe the solution you'd like**
Whether an option can be added. If this option is on, the application window will be displayed only when all the resources are loaded.

**Would you assign yourself to implement this feature?**
- [ ] Yes
- [x] No

**Comment by amrbashir** [comment]
create an invisible window, add an initialization script similar to this
```js
window.addEventListener('DOMContentLoaded', (event) => {
    window.invoke("show_window");
});
``` 
and in your IPC handler show the window.
