### ISSUE TITLE
First click if the window is not focused don't get propagated to the webview

### ISSUE THREAD

**Issue by jp-amis** [tauri-apps/wry#637]
**Describe the bug**
Every time the window is not in focus the first click you give to it will make it gain focus but will not act as a click itself. 

**Steps To Reproduce**
1. Create a window with a `<button />` and some action like on click alert or log.
2. With the window open click on any other app in order to lose focus on the Tauri app letting the window still visible3. 
3. Click in the not focused Tauri window directly in the `<button />` that should do the programmed action. 

**Expected behavior**
The click should propagate to the webview as expected on native apps. This makes it possible to create floating windows for example that don't require a double click to interact with.

**Screenshots**
![bug-gif](https://user-images.githubusercontent.com/1953162/179645721-c295df1e-bd99-4497-9a8c-9654d35fce99.gif)

**Platform and Versions (please complete the following information):**
OS: MacOS 12.4
Rustc: rustc 1.61.0 (fe5b13d68 2022-05-18)

**Would you assign yourself to resolve this bug?**
- [ ] Yes
- [x] No

**Comment by keiya01** [comment]
Sorry for delay. This was reproduced in my environment.
And I think this should work as you say, so I will investigate this issue.

**Comment by Hupka** [comment]
Hey @jp-amis,

What you describe is not a bug but the native behavior of macOS. UI elements on window can only receive a click (or key stroke) _after_ the window was activated. Your GIF shows it: the first click activates the window and the second then clicks a UI element. This is how every window in macOS works. 

This document explains the terminology: https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/WinPanel/Concepts/ChangingMainKeyWindow.html#//apple_ref/doc/uid/20000236-BCIDFJFH

What you want is a little harder to achieve: you want a window that responds to clicks without your window `activating`. This is rather complicated to achieve and requires subclassing `NSWindow` (or `NSPanel`) and overwriting inherited functions.  

"Spotlight"-like floating windows on macOS are a bit tricky and nothing that can be easily added to either Tauri/Tao/Wry.

**Comment by amrbashir** [comment]
maybe this winit feature could be helpful https://github.com/rust-windowing/winit/commit/48b843e42d8b807e8147217b666a732db41db31a ?

**Comment by jp-amis** [comment]
Apparently when you interact with native (not within webview) it works directly with only one click without the need to get focus first.

This can be easily reproduced with safari where with the window without focus if clicked within the webpage will only gather the focus while if the same is done but clicking on the + sign to create a new tab it will get the focus AND create the new tab.

If it's not doable directly like passaging through the click if possible to get coordinates of the click at least it would be possible to do some calculation and trigger from JS the click on the element.

Don't know enough on winit to help though :(

**Comment by jp-amis** [comment]
> maybe this winit feature could be helpful https://github.com/rust-windowing/winit/commit/48b843e42d8b807e8147217b666a732db41db31a ?

seems something like it, and as I said maybe will not be able to pass through to the webview but if getting the coordinate is possible it's almost there and good enough I think.

edit:

https://developer.apple.com/documentation/appkit/nsview/1483410-acceptsfirstmouse

> This allows the user to click on a view in an inactive window, activating the view with one click, instead of clicking first to make the window active and then clicking the view.

**Comment by amrbashir** [comment]
follow https://github.com/tauri-apps/tao/issues/575 for more updates on this
