### ISSUE TITLE
Don't support WebP image format?

### ISSUE THREAD

**Issue by spirityy** [tauri-apps/wry#638]
![image](https://user-images.githubusercontent.com/424997/180121791-d080218d-b419-4122-a7cf-9e6040a616e6.png)

this is chrome:
![image](https://user-images.githubusercontent.com/424997/180123100-ce886f20-cf3e-4dfe-842f-b9acf5889f48.png)

**Comment by keiya01** [comment]
Could you tell me your OS version?

**Comment by spirityy** [comment]
Mac and Ubuntu do not support WebP , windows verison does.

**Comment by FabianLars** [comment]
macOS should support webP on big sur (11) and up. i don't know about Linux but i don't see why it wouldn't be similar (aka a recent Ubuntu version should hopefully work too)

**Comment by spirityy** [comment]
<img width="526" alt="image" src="https://user-images.githubusercontent.com/424997/180180775-0362010e-adfa-4b87-9f5b-97cfe5a3bd0f.png">

This is my system configuration. I think this is about the WebView that run cargo tauri build , not the system.

code is here, you can try it.

![image](https://user-images.githubusercontent.com/424997/180181772-ec0f9170-48f3-4551-a5c1-e5b637013b0f.png)

**Comment by FabianLars** [comment]
> This is my system configuration

Hmm weird that the webview user agent reports 10.15, but probably just a webview thing.

> I think this is about the WebView that run cargo tauri build , not the system.

Well the webview version is coupled to the system version, ~~but i guess wkwebview behaves different than plain Safari yet again (because my prior message was based on Safari)~~

**Comment by keiya01** [comment]
Currently `toDataURL` for webp is not supported in webkit(safari).
(We are using webkit in macos and linux.)
https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL#browser_compatibility

**Comment by spirityy** [comment]
Chrome Broswer is totally work on every ststem. So why not use blink? Any other solution can solve this problom?

**Comment by FabianLars** [comment]
> So why not use blink?

Because that's not the _system_ webview, to use blink we'd have to go for the electron approach and bundle a browser with the app.

> Any other solution can solve this problom?

Well, as stupid as it may sound, don't use toDataURL for webp conversions. If you'd be a normal webdev, you'd have to do the same because Safari is pretty popular :/
