### ISSUE TITLE
Implement `window.open`

### ISSUE THREAD

**Issue by miniBill** [tauri-apps/wry#649]
**Is your feature request related to a problem? Please describe.**
A "library" I'm using (Elm's built-in debugger), uses `window.open` to pop up the debugger in a new window.

**Describe the solution you'd like**
An implementation of `window.open` that works similarly to the browser.

**Describe alternatives you've considered**
Using tauri APIs to open the new window wouldn't work because the code is in a library. Critically, the code also accesses the `window` object of the newly opened window.

**Would you assign yourself to implement this feature?**
- [ ] Yes
- [X] No

**Comment by amrbashir** [comment]
This is currently not possible because we have no access to the javascript context running by the webview so even if we provided a polyfill for `window.open` we can't make a `WindowProxy` of the newly created window because we don't have native access to the js context of that window.

**Comment by miniBill** [comment]
:(
Thanks for taking the time to answer
