### ISSUE TITLE
Consider bi-directional RPC communication

### ISSUE THREAD

**Issue by tmpfs** [tauri-apps/wry#66]
**Is your feature request related to a problem? Please describe.**
Not a problem but I think the ergonomics of the `Callback` API could be improved or potentially replaced with a higher-level RPC API.

**Describe the solution you'd like**
As I call `wry` callbacks from Javascript I don't want to define a new `Callback` for every function and I want to transparently return data to my Javascript code via Promises. I am currently writing a wrapper on top of the `Callback` API that achieves this using `JSON-RPC` but it feels icky because `wry` is already using `JSON-RPC` under the hood so I am effectively embedding a `JSON-RPC` message in the parameter of a `JSON-RPC` message.

I would like to propose a solution that uses a `Service` trait instead of a `Callback` function and RPC messages are handled transparently using a simple embedded Javascript client (`window.rpc` maybe?). The Javascript client would expose two public functions `call()` to call out to a service and receive a reply (via a `Promise`) and `send()` which would **not** include the `id` and therefore not receive a response from the `Service` implementation(s). 

**Describe alternatives you've considered**
I have a working prototype but I think this is such a common requirement that it should be part of `wry`.

**Would you assign yourself to implement this feature?**
- [x] Yes (Linux only)
- [ ] No

**Additional context**
The existing Rust `JSON-RPC` libraries are not a good fit for various reasons so I put together this [json-rpc2](https://docs.rs/json-rpc2/) crate that I am using for the service implementation.

Happy to share more if this interests you.

**Comment by wusyong** [comment]
`Callback` and its implementation are inspired by the original webview repo. I can't say I'm happy with the interface either.
In general, I'm glad to see any improvement toward it as long as we still communicate via message handler from each webview platform.
I think the Service trait seems pretty promising, but I'm not the one eating the dog food. Perhaps @lucasfernog and @nklayman  you guys have more feedbacks about this?

**Comment by tmpfs** [comment]
Great, I think this can be done with a view to augmenting the existing `Callback` mechanism. Maybe an enum for `Function`: 

```rust
let rpc = Callback {
  name: "rpc".to_owned(),
  function: Function::Rpc { /* Service handlers go here */ },
}
```

Or for a callback like the existing logic:

```rust
let rpc = Callback {
  name: "callback".to_owned(),
  function: Function::Call(/* boxed closure like we do now */),
}
```

Then when callback functions are invoked it's just a `match` and service handlers are invoked using the RPC request whilst `Function::Call` follows the existing code path.

**Comment by lucasfernog** [comment]
Tbh that looks like something that's supposed to be handled on the user side, like the way we do it on Tauri. But if Yu-Wei think it's a good addition, let's do it.

**Comment by wusyong** [comment]
If tauri already handles [this](https://github.com/tauri-apps/tauri/blob/80286f83e7f505dc80af65ed671ac5678f8e9a5d/tauri/src/app/utils.rs#L276), we probably don't need another variant for it. What I hope is we can get a balance between ergonomic and low-level system access in this crate. Maybe we could return just raw string and provide options for users to define the rpc routine themselves (in both rust and js)?

**Comment by tmpfs** [comment]
I understand, maybe something as simple as exposing the decoded RPC `Value` to the `Callback` would allow  me to implement what I want without the nested `JSON-RPC` message?

However, I would encourage you to reconsider doing this in *user land* because it is such a standard thing to want to return a value transparently to JS via a Promise.

Note that in my case I am not using the Tauri framework but embedding `wry` directly in an existing application so any higher-level API exposed by Tauri won't help me.

Thanks for your time folks and great work on Tauri :+1:

**Comment by tmpfs** [comment]
I did a little research into the simple fix exposing the raw `String` value, it's quite easy to implement but it won't work as the `method` name corresponds to the `Callback` name therefore cannot be delegated correctly to a service method.

**Comment by tmpfs** [comment]
> Maybe we could return just raw string and provide options for users to define the rpc routine themselves (in both rust and js)?

If this strikes the correct balance it may be the way to go, from my current limited understanding this would need to be separate from the current `Callback` mechanism and I am not sure they could happily co-exist so maybe one or the other?

```
app.set_rpc_handler(/* Some API function */);
```

Maybe? Which when set would override all `Callbacks` invocations.

**Comment by tmpfs** [comment]
I think I can see a way forward with this. The main trick will be to decouple the callback *function* name from the RPC *method* name. So instead of what we have now:

```javascript
window.external.invoke(JSON.stringify({{
    id: seq,
    method: name,
    params: Array.prototype.slice.call(arguments),
}}));
```

It would be more like:

```json
{"function": "callback_name", "payload": { /* RPC message goes here */}}
```

Then we can update the webview callback parsing and method invocation so that we could support both the existing callback mechanism and a `RpcCallback` passed to `set_rpc_server`.

The `RpcCallback` would be equivalent to `Callback` except it takes the `WindowProxy` and raw `String` value extracted from `payload`.

**Comment by wusyong** [comment]
Maybe we should move callback handling to the application layer. And make `Webview` just offer general methods like `set_rpc_server` you mentioned. We already did a similar thing on `WinodwProxy` so it should be possible. But this also means massive refactoring on each platform implementation. I'll take some time this weekend to explore.

I wish the request format could stick with that since it follows JSON-RPC spec (I know the response doesn't but we could improve that.)

If all of these can work out, then users won't notice anything and they also get more freedom on how RPC communication is handled.

**Comment by nothingismagick** [comment]
Would this approach have any security implications?

**Comment by wusyong** [comment]
All calls, in the end, should come from the message handler of each webview platform. So it's the same as the one we do right now. But if it's the message handler goes wrong, we probably need to report to upstream then.

**Comment by tmpfs** [comment]
@wusyong, I am happy to explore this further and see how it might work with your blessing? I just need to know:

* Do you want to keep the existing `Callback` functionality?
* Are you ok with some logic to pass the RPC response back into the web view via a `Promise`?

I suggest we keep the existing callback functionality but internally map it to a Javascript function that just uses the underlying RPC mechanism to return a `Promise`. So to summarise I imagine:

* In the rust code there will only ever be a single `Callback` which passes RPC messages to/from user code and Javascript
* In the Javascript code the RPC proxy is exposed as a field: `window.rpc` with an API like `send()` and `notify()`?
* For convenience named Javascript callbacks can be injected which defer to `window.rpc` and return the `Promise` returned by `send()` (`notify()` would not expect a reply to the `Promise` would yield immediately).

**Comment by wusyong** [comment]
yeah we will still have `Callback` as a simpler abstraction to public.

**Comment by nothingismagick** [comment]
How can we verify that the rpc message sender is authentic? Any chance to bind something like noise protocol in here using session-based ephemeral keys?

**Comment by tmpfs** [comment]
Hi @nothingismagick, this would only be an attack vector for people running untrusted Javascript which ideally should not be done (I know none of my apps will!) but people will do this so we should consider it.

If the webview embeds a URL running untrusted code and it detects the RPC entry point (let's call it `window.external.rpc`) it can then send messages to the host RPC callback function. But it still needs to know the method names otherwise it will just get method not found responses. There are two ways to achieve this 1) by calling `toString` on Javascript functions that include RPC calls or 2) running `strings` on the compiled executable.

I think in terms of running untrusted code it *must always be sandboxed in an iframe* so it cannot access `window.external.rpc`; we could do something like you suggest but ultimately without the iframe code will be able to access the session based ephemeral key because it would need to be embedded in the Javascript so legitimate client code can communicate.

Happy to be corrected if someone knows a better solution to hardening the communication. If there is a mechanism for key exchange with the Javascript code that does not embed the key in Javascript it is worth doing it; @wusyong are there any Webview specific features that might allow this?

An idea, maybe we could override `Function.prototype.toString()` so it always prints the `[native code]` type function content (for `release` builds only)? Security through obscurity but no harm if it works.

**Comment by tmpfs** [comment]
@wusyong, I don't want to invest too much time into this if you don't like the direction I am taking, can you please look at this diff:

https://github.com/tmpfs/wry/commit/42abc414d18f432e3c00dd61b9a148674ec68750

It illustrates how I think we can handle the RPC mechanism whilst keeping the existing `Callback` API. There is no client Javascript yet and I have sketched handling requests on the Linux platform - no code to send response back to the Javascript yet!

So far the only public API changes are to add `set_rpc_handler()` to `WebViewBuilder`.

An observation, generating the sequence number as an `i32` in `Rust` and passing it to into the embedded Javascript strikes me as not ideal. I think we should expect an `u64` and generate it randomly in the Javascript, my prototype client does this:

```javascript
Math.floor(Math.random() * Number.MAX_SAFE_INTEGER)
```

We don't really need a sequence, just a unique identifier for the message. This would be a breaking change for the signature of the `Callback` function if you agree it should be changed.

**Comment by wusyong** [comment]
I think security is another topic. We probably need another issue with it. If we would like to enhance the security, we need proper credentials, verifier for it imho.

@nothingismagick Could you open an issue and maybe provide some thoughts and candidates?

**Comment by tmpfs** [comment]
Hello folks, I think this [PR](https://github.com/tauri-apps/wry/pull/83) lays the groundwork for this feature.

Run the `rpc` example on Linux to try it out.

It needs some attention on Mac/Windows, but if my understanding of the code is correct, all that is necessary is to update the callback invocation code to match the Linux version:

https://github.com/tmpfs/wry/blob/rpc-example/src/platform/linux.rs#L54-L141

If we can get the `rpc` example running on Mac/Windows then I think there is a strong case for updating `Callback` to have the same signature as `RpcHandler`, ie: it takes a `WindowProxy` and `RpcRequest` and returns `Option<RpcResponse>`. However, this would be a major breaking change!

The only question I wonder about is whether you would prefer `Result<Option<RpcResponse>>` and convert errors from the handler function to *internal errors* sent back to the Javascript side. This would be a convenience to allow the `?` error propagation operator in these functions.

Some notes, we may be able to replace the `Arc` with an `Rc`; not sure at the moment. Also I decided that rather than wrapping the `Callback` function (to pass a `WindowProxy`) I would just pass around a reference to `WindowProxy` which seems a bit cleaner to me. Finally, rpc handlers are `Fn` not `FnMut` - we may want to change this but it could get a little tricky. Because `WindowProxy` methods all take `&self` I think we should discourage mutating captured variables and stick with `Fn`.

/cc @wusyong

**Comment by wusyong** [comment]
@tmpfs Many thanks for delivering this feature! Now we can set the RPC handler.

**Comment by tmpfs** [comment]
It was a pleasure working with you @wusyong, thanks for being so responsive and helpful and happy to see these changes land!
