### ISSUE TITLE
[feat] access to `URISchemeRequest` body on Linux

### ISSUE THREAD

**Issue by JonasKruckenberg** [tauri-apps/wry#666]
**Is your feature request related to a problem? Please describe.**

Both the Rust type [URISchemeRequest](https://docs.rs/webkit2gtk/0.18.0/webkit2gtk/struct.URISchemeRequest.html) and upstream [WebKitURISchemeRequest](https://webkitgtk.org/reference/webkit2gtk/stable/WebKitURISchemeRequest.html) do not expose a way to access the requests body. For a variety of usecases including Tauri's IPC system it would be great if we could actually access the main content of the request.

**Describe the solution you'd like**
Implement this functionality in upstream projects mirroring the one from WKWebView [URLRequest](https://developer.apple.com/documentation/foundation/urlrequest) namely `httpBody` and `httpBodyStream` so we can consume the body both blocking and through a Rust `Stream`.

**Describe alternatives you've considered**
Not have access to the body on Linux and marking this as a platform difference, but sadly this is kind of a really important core feature. It being absent makes the custom protocol pretty useless.

**Would you assign yourself to implement this feature?**
- [x] Yes
- [ ] No

**Additional context**

**Comment by wusyong** [comment]
Do we have an upstream issue to track it?

**Comment by amrbashir** [comment]
I don't think we opened one for it yet.

**Comment by TingPing** [comment]
This is tricky to implement in WebKitGTK.

There is no "request body" sitting around, it is a `GInputStream` that is read on-demand as network writes happen. In order to access a body a complete copy would have to be stored in-memory, which isn't reasonable in some cases.

**Comment by JonasKruckenberg** [comment]
Let's expose that stream though, we actually care much more about that stream than a full body. Wry itself already has code to read a stream into a `Vec<u8>` on macOS too

**Comment by TingPing** [comment]
"Just expose a stream" still has complications. It is possible for a stream to be read-once. In which case you have to copy the entire thing into memory. It is also possible for a stream to be `GSeekable` and read multiple times but you can't seek a stream that is being actively read somewhere else.

**Comment by TingPing** [comment]
I am mostly thinking about this from a libsoup perspective, the http library webkitgtk uses, its possible things work out nicer inside of WebKit.

**Comment by wusyong** [comment]
Upstream issue created: https://bugs.webkit.org/show_bug.cgi?id=252564

**Comment by ModProg** [comment]
seems like the upstream issue was fixed: https://github.com/WebKit/WebKit/pull/10714

**Comment by amrbashir** [comment]
right, this has been implemented in wry behind `linux-body` feature flag
