### ISSUE TITLE
[feat] Replace `http` module with `hyper` re-export

### ISSUE THREAD

**Issue by JonasKruckenberg** [tauri-apps/wry#668]
**Is your feature request related to a problem? Please describe.**
We currently use our http primitives, located in the `http` module. While this works, it is really bad for interoperability as most of the rust ecosystem has settled on shared crates for this purpose. Users would have to translate between standard types and wry types all the time. 

**Describe the solution you'd like**
Replace the `http` module with the more standard and widely adopted `hyper` crate that provides proven and more comprehensive http primitives than our own module. This makes both our life easier as we have less to maintain and the life of users easier as integration with server crates becomes easier. 

It will also enable the streaming protocol PR (#667), as the `Body` type of `hyper` can wrap async streams.

**This is a breaking change ❗**

While adapting to the new Type isn't difficult (see the changes I had to make to the examples here #667 for reference) it's still breaking users code.

**Describe alternatives you've considered**
We could use the `http` crate that we currently use under the hood, but it's DX story around streams isn't great.

**Would you assign yourself to implement this feature?**
- [x] Yes
- [ ] No

**Additional context**

**Comment by amrbashir** [comment]
Seems like the better choice here is to use `http` crate directly and when streams is needed we can add `http-body` crate too
