### ISSUE TITLE
[feat] Remote Debugging

### ISSUE THREAD

**Issue by liesauer** [tauri-apps/wry#678]
**Is your feature request related to a problem? Please describe.**
with remote debugging enabled, we can easily debug the tauri app(frontend side) like a normal web project. https://github.com/tauri-apps/tauri-docs/issues/842 for more details.

**Describe the solution you'd like**
add a option setting to enable the remote debugging.

**Describe alternatives you've considered**

**Would you assign yourself to implement this feature?**
- [ ] Yes
- [x] No

**Additional context**
https://github.com/tauri-apps/tauri-docs/issues/842 for more details

**Comment by amrbashir** [comment]
This can be done by using an Environment Variable. For Webview2, it is `WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS` and I think other platforms has a similar env var to set the remote debugging port.

**Comment by liesauer** [comment]
i don't think environment variable is a good idea. considering this, not only one tauri app is using webview2, this enforces all apps/projects who using webview2 enable remote debugging and use the same port. what if i am developing two tauri app at the same time? environment variable should never be a solution, it is what we have no alternative but to do choice.

**Comment by amrbashir** [comment]
no, the environment variable could be set for the current session only so you can debug 2 tauri apps at the same time. 

in a powershell instance run:
```powershell
$env:WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS="--remote-debugging-port=1421"; npm run tauri dev
```
and in another powershell instance do the same but with different port and different app:
```powershell
$env:WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS="--remote-debugging-port=1422"; npm run tauri dev
```
