### ISSUE TITLE
Modifying navigator.userAgentData

### ISSUE THREAD

**Issue by antiaim** [tauri-apps/wry#699]
**Is your feature request related to a problem? Please describe.**
WebViewBuilder::with_user_agent currently sets navigator.userAgent but not navigator.userAgentData

**Describe the solution you'd like**
A method to set navigator.userAgentData, possibly in WebViewBuilder

**Describe alternatives you've considered**
There doesn't seem to be any other existing method of setting navigator.userAgentData

**Would you assign yourself to implement this feature?**
- [ ] Yes
- [ ] No

**Additional context**

**Comment by FabianLars** [comment]
The webviews don't have APIs to change this property.

macOS and Linux are based on webkit and don't support userAgentData at all and WebView2 on windows will set userAgentData to null once you overwrite userAgent if i remember correctly.
