### ISSUE TITLE
Webpage screenshots

### ISSUE THREAD

**Issue by sciguy16** [tauri-apps/wry#70]
**Is your feature request related to a problem? Please describe.**
I think it would be useful to be able to capture screenshots of the rendered document/webpage, for example to programmatically screenshot web servers of as part of automated testing.

Stretch goal: potentially build a viable replacement for [phantomjs](https://phantomjs.org/), but that's probably not in scope for this issue.

**Describe the solution you'd like**
Ideally, some way to read the rendered framebuffer into a Vec of pixels so that it can be processed/encoded as PNG/etc.

**Describe alternatives you've considered**
In theory it should be possible to achieve this by injecting a copy of [html2canvas](https://github.com/niklasvh/html2canvas) into the page and then somehow getting the captured image back out of the webview, but some method for directly reading the rendered page would be cleaner (and more performant).

**Would you assign yourself to implement this feature?**
- Yes - if it turns out to be relatively simple
- No - if it requires major changes to Wry as I'm not familiar with the codebase

**Additional context**

**Comment by nothingismagick** [comment]
Thanks for the idea. I am pinging @tensor-programming because he has been working on how to rig Tauri for testing purposes, and the domain seems similar.

**Comment by nothingismagick** [comment]
It might be worthwhile to look into how tools like cypress and webdriver.io do screencaptures.

**Comment by sciguy16** [comment]
I've created an example using html2canvas to capture webpages as png, but it doesn't work for all sites (probably origin issues as you suggested on discord): https://github.com/sciguy16/wry-screenshot

**Comment by nklayman** [comment]
Linux: https://gist.github.com/bellbind/138778/c8687ceb7a7715811fcf03340fbf2ed76cfd757f

**Comment by nothingismagick** [comment]
So, taking this one step further, could we use something like this to send that PNG to a PDF (and kill two flies with one swat):

This uses printpdf under the hood: https://github.com/Quantaly/jpeg-to-pdf/blob/main/Cargo.toml

**Comment by nklayman** [comment]
The problem with that is it would only have the content shown in the viewport, not the whole page, right?.

**Comment by nothingismagick** [comment]
Look what I just found (thanks @lucasfernog ) 
https://webkitgtk.org/reference/webkit2gtk/stable/WebKitWebView.html#WebKitSnapshotRegion
```
enum WebKitSnapshotRegion
Enum values used to specify the region from which to get a WebKitWebView snapshot

Members
WEBKIT_SNAPSHOT_REGION_VISIBLE
  Specifies a snapshot only for the area that is visible in the webview

WEBKIT_SNAPSHOT_REGION_FULL_DOCUMENT
  A snapshot of the entire document.
```

**Comment by nothingismagick** [comment]
Please see #236 - this resolves for ALL platforms and creates proper PDF.
