### ISSUE TITLE
Chromium Embedded Framework as a universal fallback

### ISSUE THREAD

**Issue by Starz0r** [tauri-apps/wry#703]
**Describe the solution you'd like**
A feature flag like `libcef-fallback` or `libcef-global-override`. Having the flag enabled for a specific platform should just override the system's native webview component, or just utilize it when the system component either cannot initialize or cannot be found. Not sure if there is a way to get it to place nice with the system webview, since you can really only have one or the other, with no distinction.

**Describe alternatives you've considered**
There are CEF bindings for Rust, but they're almost 8 years old at this point, so I'd consider using them in any capacity to be a security risk. They're also not very idiomatic, being built for a very old version of Rust as well.

**Would you assign yourself to implement this feature?**
- [ ] Yes
- [x] No

**Additional context**
My main motivation for filling this out was being able to render a webview offscreen as described in this issue: https://github.com/tauri-apps/wry/issues/391. Currently, only some platforms are actually capable of doing this (macOS & Linux), meaning this is entirely platform dependent. Having libcef support, and its raw settings & handle (similar to webview4gtk) properly exposed would mean I could implement most of this myself, without having to wait for Microsoft to support it in their own WebView2 product.

Doing this also means we also get some BSD support for free, just by having it. There are some other benefits like, mostly consistent rendering, JavaScript evaluations, DOM handling behaviors that I'd also consider a plus. CEF being a C shared library, also means you can just swap out the library for another that implements the same C API.

**Comment by amrbashir** [comment]
Tbh I don't think me or any one in the team are going to work on this, because: 
1. this needs a lot of time and efforts which we can't spare at the moment
2. we are slowly exploring making our own webrenderer so any time or effort we have will be towards that instead of CEF

**Comment by Starz0r** [comment]
That's completely understandable, and exciting to hear! Having a stripped down webrenderer written in Rust would be amazing, and would satisfy the same use case for me, so I'm greatly looking forward to it.

**Comment by m4heshd** [comment]
> 2\. we are slowly exploring making our own webrenderer so any time or effort we have will be towards that instead of CEF

This, as an optional feature would be really huge for the devs. Thank you.
