### ISSUE TITLE
Option to disable Smart screen on windows

### ISSUE THREAD

**Issue by claudioluciano** [tauri-apps/wry#704]
**Is your feature request related to a problem? Please describe.**
Disable the SmartScreen on windows

**Describe the solution you'd like**
There's a flag (`msSmartScreen Protection`) on the init of the webview2, it's possible to make it accessible to us create an app without the annoying smart screen?

**Describe alternatives you've considered**

**Would you assign yourself to implement this feature?**
- [ ] Yes
- [x] No

**Additional context**
https://github.com/tauri-apps/wry/blob/dev/src/webview/webview2/mod.rs#L121

https://github.com/tauri-apps/tauri/issues/1345
https://github.com/MicrosoftEdge/WebView2Feedback/issues/834#issuecomment-765053961

**Comment by FabianLars** [comment]
I do agree that there should be an option (maybe even disabled by default?) - But you can also disable it in your code by setting an env var before starting wry (or tauri). Should be something like this:
```rs
std::env::set_var("WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS", "--disable-features=msSmartScreenProtection");
```

**Comment by claudioluciano** [comment]
> I do agree that there should be an option (maybe even disabled by default?) - But you can also disable it in your code by setting an env var before starting wry (or tauri). Should be something like this:
> 
> ```rust
> std::env::set_var("WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS", "--disable-features=msSmartScreenProtection");
> ```

wow cool i didn't know i could define it like this, i will test this, but an option will be better to have

**Comment by amrbashir** [comment]
is there a reason why someone might want that? should we be disabling it by default @FabianLars ?

**Comment by FabianLars** [comment]
there is probably no reason to enable it in the context of use cases we officially "support". I guess it _may_ only be relevant for the browser-like use case so it should be fine to just disable it without an option (especially since the people asking browser related questions apparently didn't care about security anywayyy)

**Comment by amrbashir** [comment]
I went ahead and disabled it by default. Unfortunately setting the env var is not enough because it was overridden internally so I added a method to disable internal args. tauri will need to expose this new method.

**Comment by amrbashir** [comment]
I have changed it to allow passing the arguments instead for better security see #711
