### ISSUE TITLE
MacOS: window.print() margins and dialog options differ

### ISSUE THREAD

**Issue by sc00** [tauri-apps/wry#713]
**Describe the bug**
When printing using the window.print() method in the context of MacOS, page margins as well as dialog options differ from Safari. Margins are significantly larger and paper size and orientation options are absent.

**Steps To Reproduce**
Initialise Tauri Vanilla app, call window.print() method.

**Expected behavior**
Default margins and all options available.

**Screenshots**
![image](https://user-images.githubusercontent.com/5355771/193288074-114be90f-511c-49dd-8328-abe74b73cde8.png)
![image](https://user-images.githubusercontent.com/5355771/193288130-b3deadf5-143e-4342-a348-9944e385eaeb.png)

**Platform and Versions (please complete the following information):**
OS: macOS 12.6
Rustc: 1.57

**Would you assign yourself to resolve this bug?**
- [ ] Yes
- [x] No

**Additional context**
The @page rule is not implemented with Safari. Setting the printable area to "position: fixed;" and "top: 0; right: 0; left: 0;" does not influence the margins. Using negative inset will result in cutting the content off.

**Comment by FabianLars** [comment]
Here's the discord convo about this because it goes further than that. The print dialog is also different from the Safari one and doesn't make it possible to change the margins: https://discord.com/channels/616186924390023171/731495028677148753/1025386181720023050
