### ISSUE TITLE
Question: why re-export tao rather than let the user use tao directly?

### ISSUE THREAD

**Issue by felixf4xu** [tauri-apps/wry#736]
Hi,

I'm new to wry and rust in general.

When I read the document, it says that `wry` _re_export_ tao and I checked the implementation a little bit.

My understanding of the _re-exporting_ is that the user of `wry` can use [wry](https://docs.rs/wry/latest/wry/index.html)::[application](https://docs.rs/wry/latest/wry/application/index.html)::[accelerator](https://docs.rs/wry/latest/wry/application/accelerator/index.html#).

I'm not sure, but I guess the user of `wry` can also use [tao](https://docs.rs/tao/latest/tao/index.html)::[accelerator](https://docs.rs/tao/latest/tao/accelerator/index.html#) directly.

I'd like to get idea of the _re-exporting_, is it a *pattern* in rust world?

**Comment by FabianLars** [comment]
i think the main advantage here is that it makes it easy to sync the correct tao version 🤔

**Comment by amrbashir** [comment]
As Fabian said, you need to use the same tao version as the one `wry` depends on, otherwise the app won't compile because rust treats types from different versions as different so re-exporting eliminates the need to sync versions.
