### ISSUE TITLE
Crash on creating `WebView` instance with large HTML source on Windows

### ISSUE THREAD

**Issue by rhysd** [tauri-apps/wry#737]
**Describe the bug**

I'm considering to use WebView for showing some graphical outputs in my app. I don't want to manage HTML/CSS/JS sources outside the executable only for the UI. So I'm trying to embed sources in the executable.
I bundled JS/CSS into single HTML file (about 1.7MB) and loaded it with `WebViewBuilder::with_html`. It worked on macOS, but it crashed on Windows with invalid parameter error.

**Steps To Reproduce**

[bundle.html.zip](https://github.com/tauri-apps/wry/files/9878445/bundle.html.zip)

1. Download and unzip the `bundle.html.zip`. Single HTML file `bundle.html` (1.7MB) can be found.
2. Run the following code which was slightly modified from Wry's example
3. It opens and closes a blank window immediately
4. Error message is shown in console

```rust
fn main() -> wry::Result<()> {
    use wry::{
        application::{
            event::{Event, StartCause, WindowEvent},
            event_loop::{ControlFlow, EventLoop},
            window::WindowBuilder,
        },
        webview::WebViewBuilder,
    };

    const HTML: &str = include_str!("bundle.html");

    let event_loop = EventLoop::new();
    let window = WindowBuilder::new().build(&event_loop)?;
    let _webview = WebViewBuilder::new(window)?.with_html(HTML)?.build()?;

    event_loop.run(move |event, _, control_flow| {
        *control_flow = ControlFlow::Wait;

        match event {
            Event::NewEvents(StartCause::Init) => println!("Wry has started!"),
            Event::WindowEvent { event: WindowEvent::CloseRequested, .. } => {
                *control_flow = ControlFlow::Exit
            }
            _ => (),
        }
    });
}
```

**Expected behavior**

WebView window shows up with loading the HTML file.

**Screenshots**

Since no window shows up, there is no screenshot. Instead, the following error message is output to console.

```
Error: WebView2Error(WindowsError(Error { code: 0x80070057, message: パラメーターが間違っています。 }))
```

Note: `パラメーターが間違っています。` is a Japanese localized message of 'invalid parameters'.

**Platform and Versions (please complete the following information):**
OS: Windows 10 21H2
Rustc: `rustc 1.64.0 (a55dd71d5 2022-09-19)`

**Would you assign yourself to resolve this bug?**
- [ ] Yes
- [x] No

**Additional context**

I confirmed smaller HTML source (about 1.0MB) can be loaded correctly. I also confirmed all requirements are met on my Windows machine (VC14 runtime and WebView2 runtime).

I'd like to know this is intended behavior or not. If not, I'd like to know a workaround for loading a large HTML source on memory if exists.

**Comment by amrbashir** [comment]
You could instead leverage the custom protocol, see https://github.com/tauri-apps/wry/blob/dev/examples/custom_protocol.rs

**Comment by rhysd** [comment]
Thank you. I'll take a look.

**Comment by amrbashir** [comment]
webview2 `NavigateToString` can only support 2MB https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2?view=webview2-1.0.1370.28#navigatetostring, I will document this.
