### ISSUE TITLE
Keyboard event is not sent to WebView just after window launches

### ISSUE THREAD

**Issue by rhysd** [tauri-apps/wry#739]
**Describe the bug**
Until clicking the window content, no keyboard event is sent to WebView rendered in the window.

**Steps To Reproduce**

1. Run the following code
2. Enter some keys
3. Check if the string in the window was changed
4. The string is still `No input yet`, which means no keyboard event happened

```rust
fn main() -> wry::Result<()> {
  use wry::{
    application::{
      event::{Event, StartCause, WindowEvent},
      event_loop::{ControlFlow, EventLoop},
      window::WindowBuilder,
    },
    webview::WebViewBuilder,
  };

  let event_loop = EventLoop::new();
  let window = WindowBuilder::new()
    .with_title("Hello World")
    .build(&event_loop)?;
  let _webview = WebViewBuilder::new(window)?
    .with_html(
      "
    <body>
      <div id='hello'>No input yet</div>
      <script>
        window.addEventListener('keydown', e => {
          document.getElementById('hello').textContent = `input: ${e.key}`;
        });
      </script>
    </body>
    ",
    )?
    .build()?;

  event_loop.run(move |event, _, control_flow| {
    *control_flow = ControlFlow::Wait;

    match event {
      Event::NewEvents(StartCause::Init) => println!("Wry has started!"),
      Event::WindowEvent {
        event: WindowEvent::CloseRequested,
        ..
      } => *control_flow = ControlFlow::Exit,
      _ => (),
    }
  });
}
```

**Expected behavior**

Keyboard events can be received just after window launches.

**Screenshots**

<img width="912" alt="screenshot" src="https://user-images.githubusercontent.com/823277/198288634-fdfeed33-6e0f-4507-aa1f-551ccbf12045.png">

**Platform and Versions (please complete the following information):**
OS: macOS 11
Rustc: 1.64.0

**Would you assign yourself to resolve this bug?**
- [x] Yes
- [ ] No

**Additional context**

Once clicking content within the window, keyboard events start to be received by the event listener.

I will try to fix this.

**Comment by wusyong** [comment]
Thanks for contributing! Closed by #740
