### ISSUE TITLE
HTTP package conflict in docs and outside project

### ISSUE THREAD

**Issue by rockisch** [tauri-apps/wry#744]
**Describe the bug**
If you go to the documentation of `wry::http` module, the definitions won't match what's being done in examples. If you try to run the examples in a separate project with only a `wry` dependency, they will fail.

But, if you try to run the examples with `cargo run --examples <example`, everything works as expected.

**Steps To Reproduce**

The file https://github.com/tauri-apps/wry/blob/dev/examples/form.rs uses `Response::builder`. Such method does not exists in the documentation:
https://docs.rs/wry/0.21.1/wry/http/struct.Response.html

Same with the method `path` on `Request.uri`. If you run the example inside the project, `uri` returns a `URI` object, but the docs says it returns a `&str`, which makes the `path` call invalid:
https://docs.rs/wry/0.21.1/wry/http/struct.Request.html#method.uri

The docs behavior reflects what happens in separate projects. Create a project, add `wry = "0.21.0"` to `Cargo.toml`, and try to do:

```rs
use wry::http::Response

fn main() {
    let _ = Response::builder();
}
```

It will fail.

**Expected behavior**
The docs, separate projects, and the examples should all have the same behavior.

**Platform and Versions (please complete the following information):**
OS: Windows
Rustc: 1.64.0

**Additional context**
I have no idea what exactly is happening btw. I don't even know where the `wry::http` package is coming from.

**Comment by lucasfernog** [comment]
We've updated the http module, it now just re-exports the http crate, so that's why it's different. You can either update your wry dependency to pull from git or check the example code before the http update: https://github.com/tauri-apps/wry/pull/706/files

**Comment by rockisch** [comment]
Shouldn't something be done to fix the docs though?
