### ISSUE TITLE
Audio continues when a new window is closed

### ISSUE THREAD

**Issue by shakyShane** [tauri-apps/wry#750]
**Describe the bug**
A second window opened at startup will continue to play audio 

**Steps To Reproduce**
Steps to reproduce the behavior, just this:

```rust
#![cfg_attr(
    all(not(debug_assertions), target_os = "windows"),
    windows_subsystem = "windows"
)]

fn main() {
    tauri::Builder::default()
        .setup(|app| {
            tauri::WindowBuilder::new(
                app,
                "oops-this-will-close-but-audio-will-continue",
                tauri::WindowUrl::External("https://www.youtube.com/watch?v=JhSZw8fiTLc".parse().unwrap()),
            )
                .always_on_top(true)
                .build()?;
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
```

**Expected behavior**
When I close the second window, I expect the youtube video to stop playing, but instead the audio continues in the background

**Screenshots**

**Platform and Versions (please complete the following information):**
OS: macos
Rustc: 1.65

**Would you assign yourself to resolve this bug?**
- [ ] Yes
- [x] No

**Additional context**

**Comment by shakyShane** [comment]
This is a big blocker for me, is there anything I can do to help track down the bug ? 🙏🏻

**Comment by FabianLars** [comment]
hmm, a really tedious approach would be to go through all the commits that changed something in src/webview/wkwebview and check which commit broke it again 😪 (that's coming from someone with no idea about the macos backend)

For reference here's the old issue: https://github.com/tauri-apps/wry/issues/536 and where it was fixed: https://github.com/tauri-apps/wry/pull/556

**Comment by shakyShane** [comment]
https://github.com/tauri-apps/wry/commit/16d192450ed639f94cf8b7137fa5fea1a319f8b5 seems to be where the `self.navigate("about:blank")` was removed

**Comment by shakyShane** [comment]
Ok re-adding that fixes it, but a bigger issue seems to be the lack of automated test for this to prevent such a bad bug from popping up again in the future. I will have a think of a way to add one :)

**Comment by FabianLars** [comment]
16d1924 was actually the fix. the about:blank navigation merely resets the process, but doesn't close it which is what we actually want and what #556 implemented back then. But some commit between #556 and today broke it again (it indeed worked correctly, as in no zombie processes, for this timeframe)

**Comment by FabianLars** [comment]
ah sorry i messed up the PR numbers, #587 was the fix. #556 was only the reset workaround, to stop audio from playing.

**Comment by shakyShane** [comment]
Ahh, ok fair enough :)

**Comment by shakyShane** [comment]
at least I can help with a git bisect to find exact commit :)

**Comment by shakyShane** [comment]
this is the first bad commit https://github.com/tauri-apps/wry/commit/2eba8c9c26ff5f9512b0039ac04bc7fd27a5256f

the commit before this one works correctly
