### ISSUE TITLE
How to hide scrollbars ?

### ISSUE THREAD

**Issue by FluffyDiscord** [tauri-apps/wry#759]
Hi, I am trying to hide scrollbars and scroll thumbs, but none of the CSS candidates work.

My device is running PopOS 22.04 (basically ubuntu)

**Comment by Winnetoe24** [comment]
Hi, on windows this works:
html,
body {
  -ms-overflow-style: none;  /* IE and Edge */
  scrollbar-width: none;  /* Firefox */
}

/* Hide scrollbar for Chrome, Safari and Opera */
html::-webkit-scrollbar {
  display: none;
}

i think it should work for you as well.

**Comment by amrbashir** [comment]
the selectors mentioned here https://www.w3schools.com/howto/howto_css_custom_scrollbar.asp should work

**Comment by A-caibird** [comment]
> Hi, on windows this works: html, body { -ms-overflow-style: none; /* IE and Edge _/ scrollbar-width: none; /_ Firefox */ }
> 
> /* Hide scrollbar for Chrome, Safari and Opera */ html::-webkit-scrollbar { display: none; }
> 
> i think it should work for you as well.

that's wrong 

::-webkit-scrollbar {
  width: 0px;
}

or 

 ::-webkit-scrollbar {
    display: none;
  }
