### ISSUE TITLE
<code> tags not rendering

### ISSUE THREAD

**Issue by nova446** [tauri-apps/wry#762]
**Describe the bug**
text within ```<code>``` tags is showing up as normal text.

**Steps To Reproduce**
window created using following code from example in readme where html contains text in ```<code>``` tags
``` 
let event_loop = EventLoop::new();
let window = WindowBuilder::new()
    .with_title(filename)
    .build(&event_loop)?;
let html = markdown::to_html(&markdown);
let _webview = WebViewBuilder::new(window)?
    .with_html(&html)
    .build()?;
```

**Expected behavior**
the text in ```<code>``` tags renders as ```code```

**Platform and Versions (please complete the following information):**
OS: Windows 10
Rustc: rustc 1.67.0-nightly (c5d82ed7a 2022-11-19) and rustc 1.65.0 (897e37553 2022-11-02)
both produce same behavior

**Would you assign yourself to resolve this bug?**
- [ ] Yes
- [x] No

**Additional context**

**Comment by amrbashir** [comment]
Works fine for me. I think you want to have the `<code>` to behave as code blocks in markdown but that is markdown not HTML. In HTML, `<code>` [renders the text using the monospace font](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/code). If you want the makrdown style, then you need write your own markdown styling in CSS or use something like https://github.com/sindresorhus/github-markdown-css
