### ISSUE TITLE
[macOS] Keyboard Shortcut isn't working in --release mode

### ISSUE THREAD

**Issue by hamza72x** [tauri-apps/wry#774]
**Describe the bug**

The keyboard shortcut isn't working in `--release` mode.
But the `debug` version is working fine.

**Steps To Reproduce**

- Clone latest dev branch
- Run following

```sh
RUSTFLAGS="-l framework=WebKit" cargo build --example menu --release
```
- Open the app/executable (`target/release/examples/menu`)
- Try `CMD+Q`
- It will not work

**Expected behavior**
- The app should close

**Platform and Versions (please complete the following information):**
OS: macOS 13.0 (22A380)
Rustc: rustc 1.65.0 (897e37553 2022-11-02)

**Would you assign yourself to resolve this bug?**
- [ ] Yes
- [x] No

**Additional context**
The keyboard shortcut is working in `debug` mode.
Please note that: All of other `MenuItem -> native_item (s)` aren't working either.

**Comment by wusyong** [comment]
I cannot reproduce this. I have tried `RUSTFLAGS="-l framework=WebKit" cargo build --example menu --release` and `cargo run --example menu --release`.
They both can work by pressing `CMD+Q`.

**Comment by hamza72x** [comment]
> I cannot reproduce this. I have tried `RUSTFLAGS="-l framework=WebKit" cargo build --example menu --release` and `cargo run --example menu --release`. They both can work by pressing `CMD+Q`.

How can I send some sort of more debug info?

**Comment by hamza72x** [comment]
> I cannot reproduce this. I have tried `RUSTFLAGS="-l framework=WebKit" cargo build --example menu --release` and `cargo run --example menu --release`. They both can work by pressing `CMD+Q`.

Update:

1. My `m1` machine is working fine.
2. `Intel` based isn't working.

Both are using the same rustc and macOS version.

**Comment by wusyong** [comment]
@hamza72x Did you really tes wry's menu example rather than just tested on your project?
I just resolved similar issue in https://github.com/tauri-apps/tauri/issues/5669.
It might because of misoptimization.

**Comment by hamza72x** [comment]
@wusyong  I tested the menu example, and also did again right now:


https://user-images.githubusercontent.com/48919542/204963645-98ecdd32-8233-4462-8cab-8d723cc92d0e.mp4

**Comment by wusyong** [comment]
@hamza72x Thanks for confirmation again!

Is it normal in wry 0.21 and before? I feel like we should just roll back at this rate. WinitView/TaoView has too many custom behavior we probably should just add with native NSView.

**Comment by hamza72x** [comment]
@wusyong Yeah, wry v0.21 worked.

Please note: latest wry is working in `m1` machine. Only my `intel` version is making this problem.


https://user-images.githubusercontent.com/48919542/204985250-0de3d801-2895-4945-816d-5dae6744d21c.mp4
