### ISSUE TITLE
IPC takes ~30sec on Windows, sometimes

### ISSUE THREAD

**Issue by FredrikNoren** [tauri-apps/wry#775]
**Describe the bug**
For some reason IPC calls take around 30seconds from being issued to being handled by `with_ipc_handler`, but only on windows, and only some times.

**Steps To Reproduce**
- Register a handler with `with_ipc_handler`
- Post a message with `window.ipc.postMessage`
- Wait for the event

**Expected behavior**
I'd expect it to be instantaneous

**Platform and Versions (please complete the following information):**
OS: Windows
Rustc: nightly-2022-08-30

**Would you assign yourself to resolve this bug?**
- [ ] Yes
- [x] No

**Additional context**
I'm running the wry window as a sub-process to another process. Not sure if that should matter in any way though.

**Comment by amrbashir** [comment]
Can't reproduce, please provide a minimal repro

**Comment by FredrikNoren** [comment]
Hm.. I'm starting to suspect this was an error on my end. I'll close for now
