### ISSUE TITLE
[Safari]<a> download attribute  not available base64

### ISSUE THREAD

**Issue by WonderLand33** [tauri-apps/wry#780]
**Describe the bug**
The HTML <a> download attribute  not available Base64, and cannot save to local.

```
<a download="test.jpg" class="btn" href="data:image/jpeg;base64,******">Save</a>
```

**Steps To Reproduce**
 Click `Save`

**Platform and Versions (please complete the following information):**
OS: macOS 13.0 (22A380)
Rustc: 1.65.0 (897e37553 2022-11-02)
WebView: Safari

**Would you assign yourself to resolve this bug?**
- [ ] Yes
- [x] No

**Comment by wusyong** [comment]
You have to call [with_download_started_handler](https://docs.rs/wry/latest/wry/webview/struct.WebViewBuilder.html#method.with_download_started_handler) and [with_download_completed_handler](https://docs.rs/wry/latest/wry/webview/struct.WebViewBuilder.html#method.with_download_completed_handler).
See download_event example for reference.
