### ISSUE TITLE
Getting `Secure` cookies from Rust

### ISSUE THREAD

**Issue by grilme99** [tauri-apps/wry#785]
I need to be able to retrieve `Secure` cookies from the WebView in Rust. As far as I can tell, this is not currently possible.

Ideally, I would be able to access some Map that contains all cookies stored by the WebView. This needs to be supported on both Windows and Mac for my use case.

So far, I've also considered the following:
- Accessing cookies from JavaScript. This isn't possible because the cookies are Secure.
- Accessing the cookies from the file system. This doesn't work because Mac doesn't write cookies back to disk until the application closes, and Windows encrypts the SQLite cookie database (a rabbit hole I do not want to go down).
- Access cookies through a custom protocol. Not possible again because cookies are Secure.

If all else fails, I will have to fork the library and implement the functionality on Windows and Mac myself. I would assign myself this issue.

**Comment by keiya01** [comment]
It's duplicated with https://github.com/tauri-apps/wry/issues/444.
