### ISSUE TITLE
Security of message passing

### ISSUE THREAD

**Issue by nothingismagick** [tauri-apps/wry#79]
**Is your feature request related to a problem? Please describe.**
In #66 we began discussions about how to enhance the security model around message passing between wry and the webview. Specifically in the case of the RPC approach, we need to figure out a lightweight method for message authentication and potential encryption. Generally speaking it would be wise to NEVER use untrusted javascript, but we know that people will always do so. Tailor-made attack endpoints, if they know they are being consumed by a tauri / wry app, can leverage this knowledge in order to use / abuse the backend API. 

**Describe the solution you'd like**
I would like to have a discussion about methods by which such a channel can use a system like noise protocol to generate ephemeral keys at startup (between trusted JS and Rust) in order for JS to send Rust a message. Since Rust OWNS the webview, it might seem that we do not need Rust to authenticate itself, but this is not the case. An evil thread might try to send a message to the webview, and this is why having a secure transport layer is important.

A lightweight solution (that will admittedly have overhead) might be to use one-time-keys / salts that our trusted rust generates each time a message has been received and places in the WEBVIEW JS domain for the next message. This key could be used with some cryptolib to encrypt the message coming from the webview.

Now, the problem still remains, how do we protect an evil iFrame (or worse, some remote script from a corrupt CDN) from knowing / discovering this key, using it "appropriately", and then using our RPC / window.evaluate ?

Another heavyhanded option might be to actually inspect the javascript caller from rust and then "acceptlist it" or run it through some kind of "DOMpurifier", although to be fair I have no idea if this would really work.

Can we inspect and "approve" remote JS before letting it sexecute?

Overwriting and freezing Object primitives seems similarly heavyhanded, but if I were a totally paranoid about security, I would definitely consider this.

**Describe alternatives you've considered**
We looked at some approaches here: https://github.com/tauri-apps/wry/issues/66#issuecomment-785522478

At the moment we have several mitigations in place:

1. CSP injected by tauri can prevent remote execution (not always an option)
2. Recommend that iframes are sandboxed (does not treat e.g. `<SVG>` or `<OBJECT>`attack vectors)
3. Randomize the function handler names (can be inspected at runtime and brute forced)

**Would you assign yourself to implement this feature?**
- [x] Yes with regard to the security review

**Comment by nklayman** [comment]
`window.parent` and `window.frameElement` are blocked when the iframe is from a different source than the parent, so I don't think there is a risk of an invasive iframe, even if we don't have a special key. As for a malicious script loaded directly into the window, I think I have an idea that might work. Pretty much what it would do is only allow local content to access Tauri APIs, so remote scripts that could be compromised won't have access. To do this, we need to provide a special key to local scripts at runtime. How do we do this? Custom protocol to the rescue again. When loading a resource with the custom protocol, we can check if it is a script. If it is, we can modify the contents to wrap it in a closure (so variables are isolated) and then add something like `const __TAURI_KEY__ = 'supersecret'` to the beginning of it. Then, we make the `INVOKE_HANDLER` callback require that key on the Rust side. Would this fit the required criteria?

**Comment by tmpfs** [comment]
Hello folks, if SES (Secure ECMAScript) hasn't crossed your radar it might be worth researching as a possible solution:

https://github.com/Agoric/ses-shim

If you bundled the SES runtime and used a capability policy defined by Tauri (I think you already have this) the *compartments* provided by SES might solve a lot of the attack vectors from third-party untrusted code.

**Comment by wusyong** [comment]
Since this issue also related to #253. I would like to close this and move the future discussion to there.
