### ISSUE TITLE
Best approch to disable key error sound

### ISSUE THREAD

**Issue by wusyong** [tauri-apps/wry#799]
After #798, we remove all keyDown implementations. Because key events on macOS is too messy, it's not worth it to implement our own. This will bring back beep sound when pressing key.

The error sound will fire when the view doesn't handle it, eg. there's no menu accelerator for it, or users are not typing in the textarea. To remove it, we can offer a config to add `keyDown` back again with several workaround. But I think we should not handle any accelerator without `Ctrl` and `Cmd` this time. Because the key event chain is totally different without them, and I have struggled to satisfy every scenarios. See this [slides](https://docs.huihoo.com/apple/wwdc/2010/session_145__key_event_handling_in_cocoa_applications.pdf) for more information. Official Apple apps seem to follow this convention too. They don't have acceleartors without `Ctrl` and `Cmd`.

Do you think this is a good idea: add a option to disable error sound but menu accelerator won't work without `Cmd` and `Ctrl`. And should it be default?

**Comment by probablykasper** [comment]
Here are some uninformed suggestions that were probably already considered/tried:

#### A
1. Make the webview be the first to receive keydown events using `makeFirstResponder`
2. Afterwards, have a catchall keydown handler on NSView which runs `performKeyEquivalent`

#### B
2. Make the webview be the first to receive keydown events using `makeFirstResponder`
3. Have a catchall keydown handler in a subview

#### C
Something with [`interpretKeyEvents`](https://developer.apple.com/documentation/appkit/nsresponder/1531599-interpretkeyevents)? not sure what it does

#### D
Put webview inside a subview _inside the contentview_, if that's any different from what was done before which removed resize/cursor events.

#### E
Override the webview's keydown handler itself

The missing events were the only functional issue with the subview approach, right? Did you figure out why exactly the events didn't work with that setup?

**Comment by wusyong** [comment]
Yeah I have tried above but they all have something doesn't work. Like `Cmd+*` accelerator not working, or `Shift+*` not working.

The approach before #798 also have issues that accelerators without `Cmd` and `Ctrl` will fire twice. And I don't know why calling `super.performKeyEquivalent` can't trigger `Esc` key call. It has to be `super.keyDown`. And if we just call `keyDown`, the beep sound returns.

**Comment by probablykasper** [comment]
Is Electron's usage of `performKeyEquivalent` helpful in any way?
https://github.com/search?q=repo%3Aelectron%2Felectron%20performKeyEquivalent&type=code

**Comment by probablykasper** [comment]
I think I might've actually managed to fix it 🤞
