### ISSUE TITLE
Resize is lagging.

### ISSUE THREAD

**Issue by thienpow** [tauri-apps/wry#80]
it would be good to have 
min-width, max-width <-- this 2 is good for PWA, if user resized it too small, it would become ugly.
maximized <-- this would be maximized on first load.

another thing would be, try delay webview resize when the host window resize, like how all the browser did, this would make sure PWA reflective size won't response immediately... current resize is seriously lagging for PWA but it was smooth in browser.

_Originally posted by @thienpow in https://github.com/tauri-apps/tauri/issues/539#issuecomment-656070094_

**Comment by wusyong** [comment]
Testing on all platforms, this looks like a Linux bug.

**Comment by nklayman** [comment]
I think this one is out of our control. Even Gnome Web lags horribly on resize. Since we can't do anything about it, I'm gonna close this.
