### ISSUE TITLE
callback for when document.title is changed?

### ISSUE THREAD

**Issue by PerBothner** [tauri-apps/wry#804]
If a document in a WebView sets `document.title`, it would be nice to get a some kind of notification. This could be used to update the window title. Electron has a `page-title-updated` event, Of course this is only needed when you don't control the JavaScript in the window, so the priority is probably low.

**Comment by amrbashir** [comment]
This seems to be possible on all platforms:
- Windows: https://docs.rs/webview2-com/latest/webview2_com/Microsoft/Web/WebView2/Win32/struct.ICoreWebView2.html#method.add_DocumentTitleChanged
- Linux: https://docs.rs/webkit2gtk/latest/webkit2gtk/trait.WebViewExt.html#tymethod.connect_title_notify
- Android: https://developer.android.com/reference/android/webkit/WebChromeClient#onReceivedTitle(android.webkit.WebView,%20java.lang.String)
- macOS/iOS: https://developer.apple.com/documentation/webkit/wkwebview/1415015-title?language=objc , this property is KVO compliant which means it can be tracked using [`addObserver`](https://developer.apple.com/documentation/objectivec/nsobject/1412787-addobserver)
