### ISSUE TITLE
Additional HTTP header with loading URL

### ISSUE THREAD

**Issue by realwakka** [tauri-apps/wry#816]
I want to open a URL that needs additional custom http header. Is there any way to add custom http header?

It seems that android webview has a feature what I want.
https://developer.android.com/reference/android/webkit/WebView#loadUrl(java.lang.String,%20java.util.Map%3Cjava.lang.String,%20java.lang.String%3E)

It would be good to add some function for WebviewBuilder like below.

```

let _webview = WebViewBuilder::new(window)?
        .with_url(&some_url)?     
        .with_http_header("some", "header")
        .build()?;
```

I tried to add header with initialization_script but it failed.

**Would you assign yourself to implement this feature?**
- [ ] Yes
- [x] No

**Comment by amrbashir** [comment]
Overall seems possible ~~but Webkit2gtk (Linux) doesn't have a way to do it, but I will reference other platforms here until webkit2gtk exposes something for this~~.

Windows: https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2_2?view=webview2-1.0.1462.37#navigatewithwebresourcerequest
Android: https://developer.android.com/reference/android/webkit/WebView#loadUrl(java.lang.String,%20java.util.Map%3Cjava.lang.String,%20java.lang.String%3E)
macOS/iOS: https://developer.apple.com/documentation/webkit/wkwebview/1414954-loadrequest?language=objc
Linux: https://webkitgtk.org/reference/webkit2gtk/stable/method.WebView.load_request.html (needs testing)

**Comment by FabianLars** [comment]
It's supported on Linux too, a modified load_url method could look something like this:
```rs
pub fn load_url(&self, url: &str) {
    let req = URIRequest::builder().uri(url).build();
    let headers = req.http_headers().unwrap();
    headers.append(
      "My-Header",
      "This only works when you're creating new requests, you can't modify ones created by the webview itself.",
    );
    self.webview.load_request(&req);
  }
```

**Comment by amrbashir** [comment]
`http_headers` from `WebkitURIRequest` is read-only.

**Comment by FabianLars** [comment]
I tested this before i sent the message:

![grafik](https://user-images.githubusercontent.com/30730186/209684672-f2c0c69e-ca09-4751-91ff-950e8b35ac74.png)

I know where you're coming from tho, until now i only ever tried it for modifying requests from `fetch` for example which indeed doesn't work (unless one uses web extensions, super annoying imo)

**Comment by amrbashir** [comment]
Oh nice, thanks @FabianLars. Apparently, I was looking at the wrong struct https://webkitgtk.org/reference/webkit2gtk/2.32.1/WebKitURIResponse.html

**Comment by amrbashir** [comment]
@realwakka do you have an example we can use to test this?

**Comment by realwakka** [comment]
Thanks! I just have tested the patch in feat/load-with-headers branch with this code below..

```rust
let webview = WebViewBuilder::new(window)?
        .with_url("https://tauri.studio")?
        .with_devtools(true)
        .build()?;


    let mut header = HeaderMap::new();
    header.append("X-CUSTOM-HEADER", HeaderValue::from_static("SOME_VALUE"));
    webview.load_url_with_headers("https://www.whatismybrowser.com/detect/what-http-headers-is-my-browser-sending", header);
```

And it works correctly!

![image](https://user-images.githubusercontent.com/6241577/210122908-7fcac260-128a-4dd2-932f-abedb9f9900b.png)

I've tested in ubuntu which uses webkit2gtk.

**Comment by amrbashir** [comment]
thanks @realwakka for testing, it will be merged soon

**Comment by realwakka** [comment]
@amrbashir Thanks for code!
