### ISSUE TITLE
Using Local Files in HTML

### ISSUE THREAD

**Issue by colin99d** [tauri-apps/wry#820]
**Describe the bug**
Trying to load local assets causes: `not allowed to load local resource`.

**Steps To Reproduce**
When using the WebBuilderView with_html function, include a link to a local asset. For example, send this html:
`<img src="file:///Users/colindelahunty/Desktop/sample.png" width="500" height="600">`

**Expected behavior**
I would expect the file to load properly.

**Screenshots**
<img width="809" alt="Screenshot 2022-12-23 at 2 26 33 PM" src="https://user-images.githubusercontent.com/72827203/209397198-3032eac1-5ff5-472a-923a-6c062dbec35a.png">

**Platform and Versions (please complete the following information):**
OS: MacOs Ventura
Rustc: 1.66.0

**Would you assign yourself to resolve this bug?**
- [ ] Yes
- [x] Point me in the right direction and I will definitely try to fix it myself
- [ ] No

**Additional context**
I see how to fix in Tauri, but can't get it figured out for wry alone:
- https://github.com/tauri-apps/tauri/discussions/1438
- https://stackoverflow.com/questions/71455924/tauri-not-allowed-to-load-local-resource

**Comment by amrbashir** [comment]
you can emulate a similar thing using [custom protocol](https://docs.rs/wry/latest/wry/webview/struct.WebViewBuilder.html#method.with_custom_protocol), see the custom_protocol example https://github.com/tauri-apps/wry/blob/ca7c8e44832b3236f08022f7ea3469be9a65aa3f/examples/custom_protocol.rs#L38
