### ISSUE TITLE
cant build for target_os=android

### ISSUE THREAD

**Issue by alexzanderr** [tauri-apps/wry#828]
# cant build for target_os=android

hello

im trying to build the simplest dioxus example for android

here is the reference to dioxus issue: https://github.com/DioxusLabs/dioxus/issues/688 to not duplicate code

when trying to compile the example for android the compile errors say that `WebContextImpl` and other items are not found

in the source is obvious that they are imported and also can be found, but they are behind a cfg feature and i dont see any android as target_os here
```rust
#[cfg(any(
  target_os = "linux",
  target_os = "dragonfly",
  target_os = "freebsd",
  target_os = "netbsd",
  target_os = "openbsd"
))]
use crate::webview::webkitgtk::WebContextImpl;
#[cfg(any(target_os = "macos", target_os = "ios"))]
use crate::webview::wkwebview::WebContextImpl;
```

in fact there is no `android` word inside the entire codebase

so my question is: can this project be used for android? or compiled?

this question answer (`NO`) was obvious for me until i saw the issues with `android` being present https://github.com/tauri-apps/wry/issues?q=android.

by seeing some android in the issues i guess there is some relationship with android, right?

please, someone, enlighten me

what is happening? what am i missing? what am i doing wrong? how can i fix the issue?

note: the version that was used for compilation was `wry-0.13.3`

thanks in advance!

**Comment by amrbashir** [comment]
> in the source is obvious that they are imported and also can be found, but they are behind a cfg feature and i dont see any android as target_os here

Android and Windows impl (Which are empty structs) are at the end of that file.

The issue you linked from dioxus seems like a conflict of dependencies which is not our fault. Try using `xbuild` as suggested in that issue.

Anyways, WRY supports Android and you can follow this [note](https://hackmd.io/XIcEwk4GSxy8APZhSa0UnA?view) to setup a project.

**Comment by alexzanderr** [comment]
thanks for the response!

i've followed the `xbuild` method and i got the app working on the phone
