### ISSUE TITLE
Initialisation Script of `""` crashes the Webview

### ISSUE THREAD

**Issue by TheBrenny** [tauri-apps/wry#833]
**Describe the bug**
Forgive me for using bad terminology: I'm a JS guy...

I'm building a wrapper around Wry which uses child processes to spawn Webviews (because technically they're considered enough of a "main thread" to let it work - idk why). I'm making this into as much of a flexible API as I can, and so when it came to implementing the WebView's options, one caused my WebViews to crash: `.with_initialization_script`. Passing it a parameter of `""` kept causing the crashes, even though it works as expected when you send `"()=>{}"` which leads me to believe that sending an empty string causes incorrect behaviour.

After doing a very very very shallow dive of the code on [docs.rs](https://docs.rs/wry/latest/src/wry/webview/mod.rs.html#366-369), it looks like (on the surface at least) that many init scripts can be included, and they'll all be added to a big chunk prior to passing to the platform specific API. If that's the case then I don't know why an empty script would cause issues, because an empty script is valid JS?

**Steps To Reproduce**
1. Create a Wry WebView with `.with_initialization_script("()=>{}")`
2. Successful run
3. Modify the init script to be `""` (an empty string)
4. Run and expect crash

**Expected behavior**
`.with_initialization_script("")` should not cause a crash.

**Platform and Versions (please complete the following information):**
OS: Windows 11 Pro, `10.0.22621`
Rustc: `rustc 1.66.0 (69f9c33d7 2022-12-12)`

**Would you assign yourself to resolve this bug?**
- [ ] Yes
- [x] No (I don't Rust - this shit too hard. 😞)

**Additional context**
If there's any insight as to why this bug happens, or if it's platform specific, I'd love to know!

**Comment by wusyong** [comment]
@TheBrenny Thank you for opening the issue! I think we can just check if it's empty string when calling it in [`src/webview/webview2/mod.rs`](https://github.com/tauri-apps/wry/blob/dev/src/webview/webview2/mod.rs#L312)
```rust
for js in attributes.initialization_scripts {
    if !js.is_empty() {
      Self::add_script_to_execute_on_document_created(&webview, js)?;
    }
}
```

I think it's a good first issue. Do you want to give it a try?

**Comment by TheBrenny** [comment]
Yeah, I guess I can give it a go, if it's just a simple fix! (And maybe it might help me understand the inner workings when I keep working on my wrapper!)

**Comment by TheBrenny** [comment]
Wouldn't it be more appropriate to check if the script is empty higher up in the call chain, like at [`src/webview/mod.rs`](https://github.com/tauri-apps/wry/blob/dev/src/webview/mod.rs#L377)? That way we can be more sure that the init scripts won't get empty strings, _and_ it becomes more cross platform? I'm not sure if this bug is reproducible on Mac and Linux as well, but I'd assume so?

**Comment by wusyong** [comment]
It doesn't happen on Linux when I tested it. But I think you are right. It's better to check in [src/webview/mod.rs](https://github.com/tauri-apps/wry/blob/dev/src/webview/mod.rs#L377)
