### ISSUE TITLE
Integrate external functions into wry

### ISSUE THREAD

**Issue by gi-dellav** [tauri-apps/wry#837]
Hi,

I'm trying to implement a desktop app using `wry`, but I would need to expose some Rust functions and make them usable from the JavaScript code running inside the web app running with `wry` and I wanted to ask if it was possible and if yes, how.

Thanks in advance.

**Comment by amrbashir** [comment]
You need to register an [IPC Handler](https://docs.rs/wry/latest/wry/webview/struct.WebViewBuilder.html#method.with_ipc_handler) and invoke it using `window.postMessagew("functionNameHere")` and in the ipc handler, you check the message and call the appropriate rust function.

See this example for reference https://github.com/tauri-apps/wry/blob/ceb209eddc20d284be748ee382ba8aef7686863b/examples/custom_titlebar.rs
