### ISSUE TITLE
Start making WRY more DRY

### ISSUE THREAD

**Issue by nothingismagick** [tauri-apps/wry#84]
If you are looking to get your hands dirty, this is a great issue to get started working with Rust and WRY. 

In this PR, https://github.com/tauri-apps/wry/pull/82 there is some code repetition, and if you look closely in the codebase, there are some other cases of it. With regard to mime types (aka media types), there may be situations where we need to add others as time goes on, so having the list in one place makes it easier to update and know that we have feature parity.

Feel free to ask questions here in the issue, or on our discord server.

**Comment by Shriram-Balaji** [comment]
I'd like to take this up.

For starters, I think I'll add a `mimetypes.rs` file that declares an enum that looks like 

```rust
enum MimeTypes {
 CSS,
 CSV,
 JSON,
 JSONLD,
 // . . . 
}
```

and then implement the `Display` trait for the enum, so that `MimeType::JSON.to_string()` returns "application/json". 

I'm also thinking to add a `parse` function which basically takes in a URI and gets the last suffix, to transform that into a MimeType.

**Comment by lucasfernog** [comment]
That sounds great!

**Comment by nothingismagick** [comment]
Awesome. The secret sauce here though, is in the header bytes - and these extra mime types are for those situations where INFER cannot guess what exactly is going on. Good luck!!!

**Comment by Shriram-Balaji** [comment]
@nothingismagick yup, that makes sense. Essentially when you cannot get the mimetype from the content, try to get the file extension from the uri and set a mimetype instead.

**Comment by Shriram-Balaji** [comment]
However, I do have a specific question about when an `application/octet-stream` would occur. If we take a look at the snippet used to split the url by `.`:

```
        let suffix = uri.split(".").last();
        match suffix {
         // . . . all other valid extensions
         None => "application/octet-stream"
        }
```

I'm just trying to come up with a URI to simulate the `None` arm here. Any clue?

**Comment by lucasfernog** [comment]
I think None would never reach since the split iterator always has at least one item.

**Comment by lucasfernog** [comment]
So in the case a file path doesn't have an extension, the match would be Some("").

**Comment by Shriram-Balaji** [comment]
Right, yeah that's what I was confused about too. `None` is never reachable, and we always assume `text/html` anyways.
