### ISSUE TITLE
Android - rust logs do not show up in the output of `tauri andoid dev`

### ISSUE THREAD

**Issue by doums** [tauri-apps/wry#853]
**Describe the bug**
Hi, Im trying to debug the rust core process of our application. When running on android using 
```
RUST_BACKTRACE=1 RUST_LOG=trace RUST_TRACE_OPERATIONS=1 cargo tauri android dev -vv
```
there is no logs coming from the rust process shown in the terminal except those kind of window related messages
```
01-27 13:24:48.753 15707 15766 I RustStdoutStderr: s_glBindAttribLocation: bind attrib 2 name localCoord
01-27 13:24:48.755 15707 15766 I RustStdoutStderr: s_glBindAttribLocation: bind attrib 0 name position
01-27 13:24:48.755 15707 15766 I RustStdoutStderr: s_glBindAttribLocation: bind attrib 1 name color
```
We are using the `log` crate to output logs. Only raw `println!` are shown. Any idea on how to have those logs showing up in the command output?

**Platform and Versions (please complete the following information):**

```
Environment
  › OS: Arch Linux Unknown X64
  › Node.js: 16.17.1
  › npm: 8.15.0
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.66.1
  › cargo: 1.66.1
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
WARNING: no lock files found, defaulting to npm
  › @tauri-apps/cli [NPM]: 2.0.0-alpha.1
  › @tauri-apps/api [NPM]: 2.0.0-alpha.0
  › tauri [RUST]: git+https://github.com/tauri-apps/tauri?branch=next#1af9be904a309138b9f79dc741391000b1652c75 (2.0.0-alpha.2),
  › tauri-build [RUST]: git+https://github.com/tauri-apps/tauri?branch=next#1af9be904a309138b9f79dc741391000b1652c75 (2.0.0-alpha.0),
  › tao [RUST]: 0.16.0,
  › wry [RUST]: git+https://github.com/tauri-apps/wry?branch=dev#0a3e0070f1c6f987bb664674b9a0d7238772f277 (0.24.1),

App
  › build-type: bundle
  › CSP: default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  › distDir: ../dist
  › devPath: http://localhost:9000/
  › framework: React
  › bundler: Webpack

App directory structure
  ├─ public
  ├─ src-tauri
  ├─ .storybook
  ├─ node_modules
  ├─ src
  └─ dist
```

**Comment by wusyong** [comment]
You'll need to call `android_logger` I believe. Wry template actually have [this line](https://github.com/tauri-apps/tauri-mobile/blob/dev/templates/apps/wry/src/lib.rs.hbs#L20).
Close this since this is not wry related.

**Comment by ghost** [comment]
I do not see any logs as well on the rust side even after calling logging pluginfgfrom tauri

**Comment by viniciuscr** [comment]
> You'll need to call `android_logger` I believe. Wry template actually have [this line](https://github.com/tauri-apps/tauri-mobile/blob/dev/templates/apps/wry/src/lib.rs.hbs#L20). Close this since this is not wry related.

Line 8 does the init for android, but still does not work.
