### ISSUE TITLE
Event handling overhaul

### ISSUE THREAD

**Issue by wusyong** [tauri-apps/wry#86]
**Is your feature request related to a problem? Please describe.**
Despite we now offer lots of methods in the application layer, it still lacks the ability like exposing Window or Webview types.

**Describe the solution you'd like**
We provide just one type of proxy and it just sends the events as winit does.
Users define their closure in the run method. We offer all the necessary params for them.
This should give users total control of the application behaviors.

**Describe alternatives you've considered**
Offer just another event manager. But I'm fear this will increase the interface complexity,

**Would you assign yourself to implement this feature?**
Yes

**Comment by wusyong** [comment]
Tried a few approaches and it still became way too complex in the end. If users really want to control all by themselves they could just use webview module. I think we'll keep the event manager in tauri then.

**Comment by wusyong** [comment]
Reopen it since event handling is still an issue for some ppl. The easiest way is set up a channel to propagate the event siganl.

**Comment by wusyong** [comment]
My current plan is we also expose an event listener (something like `Receiver<Event>`) when creating `Application`. But it will have limited variants.
I will explore gtk support on winit afterward.

**Comment by hediet** [comment]
Sounds great, thank you!
What do you mean with limited variants though?

**Comment by wusyong** [comment]
I mean enum variants. I think I'll just start with the closing window event.
If they are more required by others, we could add them furthermore.

**Comment by hediet** [comment]
Btw. I'd be happy to help you with this!

**Comment by hediet** [comment]
Nice, feels very thought out!
I guess the minimum example in the readme should look different now?

**Comment by wusyong** [comment]
ah right, documentation should be listed in #165 too.
