### ISSUE TITLE
WebViewBuilder.with_url crash in widows release

### ISSUE THREAD

**Issue by IllusionPerdu** [tauri-apps/wry#863]
**Describe the bug**

After v0.23.4 :  
`WebViewBuilder::new(window).unwrap().with_url(&uri).unwrap().build().unwrap();`
crash when i build in release mode with this error
`thread 'main' panicked at 'called 'Result::unwrap()' on an 'Err' value: WebView2Error(WindowsError(Error { code: 0x80070057, message: Paramètre incorrect. }))'`

If i use 
`WebViewBuilder::new(window).unwrap().with_url_and_headers(&uri, wry::http::HeaderMap::new()).unwrap().build().unwrap();`

It's work.

**Steps To Reproduce**
build with `cargo build --release` don't work when exec binary
build with `cargo build`  work when exec binary

**Expected behavior**
`WebViewBuilder::new(window).unwrap().with_url(&uri).unwrap().build().unwrap();`
Don't crash ;)

**Screenshots**

**Platform and Versions (please complete the following information):**
OS: Windows 10 (19044.2486)
Rustc: rustc 1.68.0-nightly (ec56537c4 2022-12-15)

**Would you want to assign yourself to resolve this bug?**
- [ ] Yes
- [x] No

**Additional context**

**Comment by wusyong** [comment]
I cannot reproduce this with `hello_world` example. It also uses `with_url` and release build seems working fine on my end.

**Comment by IllusionPerdu** [comment]
Ooo i try to simplify my code and i find :
in my projet i use mimalloc (https://github.com/purpleprotocol/mimalloc_rust) when i don't use it it's work :s

It's strange before v0.23.4 it's work but after if they are mimalloc it don't work. And with the `with_url_and_headers` it always work.

My project is inspired from the `multi_window`. 

If you want i can do a minimal repro...

(Sorry for my bad English)

**Comment by wusyong** [comment]
Yes a minimum reproducible example is appreciated. It can narrow the scope a lot for me to investigate the problem.

**Comment by IllusionPerdu** [comment]
I have create this git https://github.com/IllusionPerdu/test-wry

**Comment by IllusionPerdu** [comment]
I think is hear :  src\webview\webview2\mod.rs line 705
Change this
```
          let url = PCWSTR::from_raw(encode_wide(url_string).as_ptr());
          unsafe {
            webview
              .Navigate(url)
              .map_err(webview2_com::Error::WindowsError)?;
          }
```
To
```
          unsafe {
            webview
              .Navigate(PCWSTR::from_raw(encode_wide(url_string).as_ptr()))
              .map_err(webview2_com::Error::WindowsError)?;
          }
```
Don't crash
the reverse change was made in #826

**Comment by IllusionPerdu** [comment]
I have open a pull request https://github.com/tauri-apps/wry/pull/865
