### ISSUE TITLE
Add a few patches to v0.24

### ISSUE THREAD

**Issue by wusyong** [tauri-apps/wry#868]
Tauri version 1 will stick to 0.24 but there are a few patches I think are good to merge into it too.
Here are the commits and pull requests I would like to merge:
- [x] #865

**Comment by wusyong** [comment]
I open a branch v0.24.1. Please open a PR against it.

**Comment by amrbashir** [comment]
Closing as we periodically put patches to v0.24.1 when needed, we don't need an issue to track
