### ISSUE TITLE
Getting a real path of file type input

### ISSUE THREAD

**Issue by sanket143** [tauri-apps/wry#87]
**Is your feature request related to a problem? Please describe.**
I am trying to get a the real path of file selected in `<input type="file" id="myFile">` but I dunno how to.

I tried `document.getElementById("myFile").files` which gives array of `File` which contains following information.

```
lastModified: 1597767566000
name: "filename.py"
size: 859
type: "text/x-python"
webkitRelativePath: ""
```

**Describe the solution you'd like**
Electron adds a `path` property in `File` object. I don't know how exactly it is happening and will it be possible in Tauri
but this seems to be one possible solution to me.
https://github.com/electron/electron/blob/master/docs/api/file-object.md

**Comment by ken0x0a** [comment]
@wusyong Is this feature implemented?
If so, could you add a reference please?

**Comment by wusyong** [comment]
Ah sorry, closed this because we now have a file drop handler for it.
See [dragndrop](https://github.com/tauri-apps/wry/blob/master/examples/dragndrop.rs) example to see how it works.

**Comment by ken0x0a** [comment]
@wusyong Thank you for the line!
Can we get absolute path for the file?

**Comment by wusyong** [comment]
Yes, it's the absolute path.

**Comment by mihirsamdarshi** [comment]
Hi, is there an example of how I would handle dragging and dropping files using the JS Tauri API? I have a React component that utilizes the `drag` and `drop` HTML APIs with event listeners, and it can handle it just fine in a web browser, but I am unsure how I would use that to hook into my Tauri application?

**Comment by FabianLars** [comment]
@mihirsamdarshi 
Listen to the `tauri://file-drop` and `tauri://file-drop-hover` (and `tauri://file-drop-cancelled`) events with tauri's event listener: https://tauri.studio/en/docs/api/js/modules/event/#listen

**Comment by mihirsamdarshi** [comment]
@FabianLars thank you!

**Comment by Jan-Eckerlein** [comment]
https://tauri.app/v1/api/js/dialog#open

**Comment by MS90D3V** [comment]
I am going to leave this behind here, I wanted to drop files and get the fullpath. This is how I was able to get this working:

tauri.conf.json (https://v2.tauri.app/reference/javascript/api/namespaceevent/)

```
....
app: {
          "withGlobalTauri": true,
           "windows": [
				"dragDropEnabled": true // This should be enabled by default!
              ]
....
}
...
```


In my case I used svelte, so I needed to put this in my .svelte component between <script></script>

```
import { listen } from '@tauri-apps/api/event';

listen('tauri://drag-drop', (event) => {
		console.log(event);
});
```

There is **no need** for ondrop="" or  ondragstart="" on the div components themselves.
