### ISSUE TITLE
cargo test fails on macos due to gtk.rs example 

### ISSUE THREAD

**Issue by Shriram-Balaji** [tauri-apps/wry#89]
**Describe the bug**
When running `cargo test` on macos, the build fails as it seems to compile `gtk.rs`. From my limited knowledge, I believe we probably need a `cfg` flag of some sort to ignore compilation of this example on macos.

```rust
  |
3 | use cairo::*;
  |     ^^^^^ use of undeclared crate or module `cairo`

error[E0432]: unresolved import `gtk`
 --> examples/gtk.rs:4:5
  |
4 | use gtk::*;
  |     ^^^ use of undeclared crate or module `gtk`

error[E0433]: failed to resolve: use of undeclared crate or module `gtk`
 --> examples/gtk.rs:7:5
  |
7 |     gtk::init()?;
  |     ^^^ use of undeclared crate or module `gtk`

error[E0433]: failed to resolve: use of undeclared type `WindowType`
 --> examples/gtk.rs:8:30
  |
8 |     let window = Window::new(WindowType::Toplevel);
  |                              ^^^^^^^^^^ use of undeclared type `WindowType`

error[E0433]: failed to resolve: use of undeclared crate or module `gtk`
  --> examples/gtk.rs:31:5
   |
31 |     gtk::main();
   |     ^^^ use of undeclared crate or module `gtk`

error[E0433]: failed to resolve: use of undeclared type `Window`
 --> examples/gtk.rs:8:18
  |
8 |     let window = Window::new(WindowType::Toplevel);
  |                  ^^^^^^ not found in this scope
  |
help: consider importing one of these items
  |
1 | use winit::window::Window;
  |
1 | use wry::platform::window::Window;

```

**Steps To Reproduce**
- Run `cargo test` in the root.

**Expected behavior**
Tests should work.

**Platform and Versions (please complete the following information):**
OS: macOS 11.2.1
Rustc: rustc 1.52.0-nightly (94736c434 2021-02-27)

**Would you assign yourself to resolve this bug?**
- [x] Yes
- [ ] No

**Comment by wusyong** [comment]
Sorry about the mess in the examples. We are still using it as a playground. Maybe come back to this issue once we publish v0.6 😅

**Comment by wusyong** [comment]
Close this because examples now have a conditional compilation flag.
Gtk example can now run on mac safely.
