### ISSUE TITLE
Request to Disable Swipe Navigation by Default

### ISSUE THREAD

**Issue by linesoft2** [tauri-apps/wry#895]
**Is your feature request related to a problem? Please describe.**
I've noticed that the wry library enables swipe navigation by default, which can make the user interface unpredictable and difficult to control in certain situations.

**Describe the solution you'd like**
I would like to request that the wry library be updated to disable the ```SetIsSwipeNavigationEnabled``` option by default. This will ensure that the behavior of the application is always predictable and prevent unintended navigation or actions when the user is scrolling or swiping on the screen.

**Describe alternatives you've considered**
One alternative that could be considered is to provide an option in the library's settings to enable or disable swipe navigation, allowing developers to customize the behavior of the application as needed. However, I believe that disabling this feature by default is the safest and most predictable approach.

**Would you want to assign yourself to implement this feature?**
- [ ] Yes
- [x] No

**Additional context**
tauri-apps/tauri#5958

**Comment by zaynekomichi** [comment]
Is there documentation on how this can be implemented, i ended up having to work on the index.html file but i'd prefer to use the wry method, here is what i did

```
<!-- index.html -->

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Your Tauri App</title>
  <style>
    /* Disable gesture navigation */
    body {
      overscroll-behavior: none;
      touch-action: none;
    }
  </style>
</head>
<body>
  <!-- Your web content goes here -->
  <script>
    // Optionally, you can also prevent touchmove events
    document.addEventListener('DOMContentLoaded', function () {
      document.body.addEventListener('touchmove', function (e) {
        e.preventDefault();
      }, { passive: false });
    });
  </script>
</body>
</html>

```

**Comment by daveycodez** [comment]
I cannot get swipe gestures to work on mobile anymore after hours of digging. -___- why was this disabled

**Comment by zaynekomichi** [comment]
Maybe im wrong but this was for desktop not mobile

**Comment by FabianLars** [comment]
you're indeed correct.

**Comment by daveycodez** [comment]
Backward forward navigation gestures not working on iOS and no idea how to enable it

**Comment by seivan** [comment]
If you're having this issue on macOS, it could be that winit internally has swipes registered for the touchpad and signals tauri. In general, I don't think (if I am correct) that Tauri should trigger anything with swipes other than signal the app code that a swipe event has occured.
