### ISSUE TITLE
Failing doc-tests

### ISSUE THREAD

**Issue by Shriram-Balaji** [tauri-apps/wry#90]
**Describe the bug**
As discussed in #88, while running `cargo test` doctests seem to fail. This seems to be because one of two reasons:
-  The required module is not imported, and the code snippet is unable to compile
-  The API behind using a method has been changed. (For e.g. I came across an error where `app.add_window` API required 1 argument and was supplied 2 arguments, not sure why that's the case as it looks like the 2nd argument takes an `Option<T>` 🤷 )

> **NOTE**: Inspite of using the `no_run` attribute, rust still tries to compile the examples. As mentioned by @wusyong we could use the `ignore` attribute instead, but there's a slight chance that the docs become out-of-date .

**Steps To Reproduce**
Run `cargo test` in the root.

**Expected behavior**
Doctests should ideally work to ensure https://docs.rs/wry/0.5.1/wry/ stays correct.

**Platform and Versions (please complete the following information):**
OS: macOS 11.2.1
Rustc: rustc 1.52.0-nightly (94736c434 2021-02-27)

**Would you assign yourself to resolve this bug?**
- [x] Yes
- [ ] No

**Comment by wusyong** [comment]
Closed it with all doc codes are now with ignore attributes.
