### ISSUE TITLE
Examples fail to open on windows. 

### ISSUE THREAD

**Issue by tensor-programming** [tauri-apps/wry#91]
**Describe the bug**
On the current iteration of WRY, if you attempt to run any of the examples on windows it will fail.  A transient window will pop up before it is quickly closed and a `WebView2Error(Error { hresult: -2147024894 })` error is produced in the console. 

**Steps To Reproduce**
On windows, call `cargo run --example` and use any example aside from GTK.

**Expected behavior**
The window should open properly. 

**Screenshots**

**Platform and Versions (please complete the following information):**
OS: Windows 10
Rustc: 1.50.0 (cb75ad5db 2021-02-10)

**Would you assign yourself to resolve this bug?**
- [ ] Yes
- [x] No

**Additional context**
This wasn't a problem with the version of wry from about a week ago. 

Checked the webview 2 library and it also is throwing all sorts of errors.  `'Failed to Create WebView2 Environment - webview2 error, HRESULT 0x80070002'` for example.

**Comment by makitsune** [comment]
Is there a solution for this? I'm trying the example myself and I'm getting the same issue. Using latest Windows 10 Pro and Rust.

**Comment by nklayman** [comment]
@makitsune have you downloaded the [Webview2 runtime](https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section)?
