### ISSUE TITLE
WebViewBuilder::with_url: support unix domain sockets

### ISSUE THREAD

**Issue by cablehead** [tauri-apps/wry#910]
This would allow wry to be paired with small services that are only locally exposed.

Example usage with [`http-sh`](https://github.com/cablehead/http-sh)

```bash
$ http-sh ./sock -- echo Hello world
```

```rust
    let _webview = WebViewBuilder::new(window)?
        .with_url("unix://./sock")?  
        .build()?;
```

**Comment by amrbashir** [comment]
if I understand correctly, `unix://./sock` is a socket, so you need to use `WebSockets` in javascript to connect to it and update the HTML as needed, or you can connect to it from rust and then render the received html as it comes using wry.

**Comment by FabianLars** [comment]
afaik you can't access unix sockets from the browser as it will block all but ws: and wss: schemes. That said, you're right about unix sockets being "normal" sockets so if one can add a proxy that proxies from ws:// to unix:// it should be able to connect to it (i only know how to do that with nginx&apache lol) - of course that isn't enough to serve your frontend over it as you said.

**Comment by cablehead** [comment]
Oh, of course. You're right @FabianLars browsers won't allow access to a local unix socket. I'll close this issue 🙏
