### ISSUE TITLE
Bug: start example project got panic

### ISSUE THREAD

**Issue by bxb100** [tauri-apps/wry#911]
**Describe the bug**
got panic: `thread 'main' panicked at 'Ivar taoState not found on class NSKVONotifying_WryWebViewParent`

**Steps To Reproduce**
start any example project and *unfocus* window will get that panic

**Expected behavior**

**Screenshots**
<img width="1316" alt="image" src="https://user-images.githubusercontent.com/20685961/227321565-7148afd3-a05a-45b5-9c46-c86bdbe49525.png">

**Platform and Versions (please complete the following information):**
OS: `MacOS m1 13.2.1 (22D68)`
Rustc: `rustc 1.67.1 (d5a82bbd2 2023-02-07)`

**Would you want to assign yourself to resolve this bug?**
- [ ] Yes
- [x] No

**Additional context**

1. https://github.com/tauri-apps/wry/issues/739 fix with `[ns_window, setContentView: parent_view];`

2. so this PR https://github.com/tauri-apps/tao/commit/76ae625bae429148f295fc3eaf3e90984cf0c7ad using `contentView` not same as https://github.com/tauri-apps/tao/blob/407a9feaedd3d888a21cf4c0743ed79cc46009af/src/platform_impl/macos/window.rs#L482

3. It seem `window_did_resign_key` should use original `TaoView` not the `WryWebViewParent` view

**Comment by wusyong** [comment]
What example did you try? I tried `hello_world` example and it seems fine when it's unfocused.
But I appreciate additional contexts you provide. From my understanding, it looks like we should revert a few change from https://github.com/tauri-apps/tao/commit/76ae625bae429148f295fc3eaf3e90984cf0c7ad

**Comment by bxb100** [comment]
all of the examples, cause the same problem.

https://user-images.githubusercontent.com/20685961/227454371-dd4be793-a2e8-4c7e-85e1-23c53b02522d.mov

I am attempting to revert the changes made to `ns_view`, and it works as I thought. However, I'm uncertain that not breaking others' PR purpose.

**Comment by wusyong** [comment]
Okay I can reproduce them now. I forgot to update tao version as well.
I believe we don't need to revert all the change. Just some code that could cause it.

Edit: I'll update this asap. https://github.com/tauri-apps/tao/pull/714

**Comment by bxb100** [comment]
ok

**Comment by wusyong** [comment]
Tao v0.18.3 has published! https://github.com/tauri-apps/tao/releases/tag/tao-v0.18.3
Thanks for reporting this bug! @bxb100
