### ISSUE TITLE
Extend WebAssembly with Host Functions

### ISSUE THREAD

**Issue by brandonros** [tauri-apps/wry#938]
**Is your feature request related to a problem? Please describe.**
Right now what is possible: Wry loads HTML/JavaScript, which can load a WASM module, which can call code that was written in Rust that has been compiled to WebAssembly. What if the Rust you've written can't compile to WebAssembly due to thinks like `dlopen` / `dlsym` (FFI)? If you could provide host functions (in this case `dlopen` / `dlsym`) into the Wry WebView WASM runtime, it opens a new world of opportunity.

**Describe the solution you'd like**
Wry to somehow mesh the WebView WASM logic/runtime with something more powerful/robust (like Wasmer, etc.)

**Describe alternatives you've considered**

WebView IPC bridge through JSON messaging.

**Would you want to assign yourself to implement this feature?**
- [ ] Yes
- [X] No

**Additional context**

https://www.secondstate.io/articles/extend-webassembly/#:~:text=For%20Wasm%2C%20the%20Host%20Function,functionality%20to%20a%20large%20extent.

https://wasmedge.org/book/en/sdk/c/hostfunction.html

https://docs.wasmer.io/integrations/examples/host-functions

**Comment by amrbashir** [comment]
unfrotunately this is not possible since we don't have much control over the js/wasm runtimes and I don't think we would work on this any time soon plus I think your use-case could be off-loaded to the rust process that runs Wry instead of through wasm.

**Comment by brandonros** [comment]
@amrbashir would it have been a better question if I asked "could the existing with_ipc_handler be extended to pass Uint8Array buffers instead of just String to enable more efficient passing of binary encoded payloads"?

**Comment by amrbashir** [comment]
While it is possible right now with the current method, it requires serialization on both ends and results in slow performance.

We are actively investigating improving the IapC performance, see #454 and https://github.com/tauri-apps/tauri/discussions/5690

**Comment by brandonros** [comment]
> While it is possible right now with the current method

Passing something other than a `String` does not seem to be supported on Mac OS X from what I can tell.

```
window.ipc.postMessage(new TextEncoder().encode('Hello, world!'))
```

```
2023-04-24 16:51:40.059 foo[60701:659390] -[__NSFrozenDictionaryM UTF8String]: unrecognized selector sent to instance 0x6000015b1000
thread 'main' panicked at 'Uncaught exception <NSException: 0x600001b915f0>', /Users/brandonros/.cargo/registry/src/github.com-1ecc6299db9ec823/wry-0.28.0/src/webview/wkwebview/mod.rs:103:37
stack backtrace:
   0:        0x100b18c64 - std::backtrace_rs::backtrace::libunwind::trace::h2000fb4d08dbcc59
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x100b18c64 - std::backtrace_rs::backtrace::trace_unsynchronized::h2b5e61495350674d
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x100b18c64 - std::sys_common::backtrace::_print_fmt::h05f5bfbdb3415936
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:65:5
   3:        0x100b18c64 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h105074e3d85f800b
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x100b301a8 - core::fmt::write::h34766cf8fff7af1e
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/fmt/mod.rs:1232:17
   5:        0x100b16890 - std::io::Write::write_fmt::hd64c4cf6e7adea59
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/io/mod.rs:1684:15
   6:        0x100b18a78 - std::sys_common::backtrace::_print::hd92783a665d3ebfb
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:47:5
   7:        0x100b18a78 - std::sys_common::backtrace::print::h2a6828a537036cf9
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:34:9
   8:        0x100b1a154 - std::panicking::default_hook::{{closure}}::h4e82ce6ccef941b2
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:271:22
   9:        0x100b19eac - std::panicking::default_hook::h29f62f8795c5cb00
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:290:9
  10:        0x100b1a664 - std::panicking::rust_panic_with_hook::h19862cbd0fbda7ba
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:692:13
  11:        0x100b1a598 - std::panicking::begin_panic_handler::{{closure}}::h3f3626935e1669fe
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:583:13
  12:        0x100b19084 - std::sys_common::backtrace::__rust_end_short_backtrace::h5054ef52bd507d0a
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:150:18
  13:        0x100b1a2f4 - rust_begin_unwind
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
  14:        0x100b3efb0 - core::panicking::panic_fmt::h7e47e10600a90221
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
  15:        0x100a89474 - core::panicking::panic_display::h509e9028a372fa53
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:147:5
  16:        0x100991b2c - wry::webview::wkwebview::InnerWebView::new::did_receive::h3fa5c70ecfe6125d
                               at /Users/brandonros/.cargo/registry/src/github.com-1ecc6299db9ec823/wry-0.28.0/src/webview/wkwebview/mod.rs:103:37
  17:        0x1beee272c - <unknown>
fatal runtime error: failed to initiate panic, error 5
Abort trap: 6

```

**Comment by amrbashir** [comment]
That's what I meant by serialization on both sides, you need to use JSON.stringify on JS side before sending to Rust, then deserialize on it on rust

**Comment by wusyong** [comment]
I've explored quite a bit on better IPC in #454.
Theoretically, all platforms can do so. But it's rough to come up with unified interface.
I suggest using [custom protocol](https://docs.rs/wry/latest/wry/webview/struct.WebViewBuilder.html#method.with_custom_protocol) which can be more flexible and performant.

**Comment by brandonros** [comment]
I just tried with_custom_protocol

It seems if you use with_url on an https:// site, no mixture of CORS/CSP headers will allow your custom protocol to not be seen as insecure? Is that accurate? aka you can only use custom protocols with http://-served content, not https://?

```
[Warning] [blocked] The page at https://foo/index.html was not allowed to display insecure content from foo://test. (index.html, line 59)
[Error] Not allowed to request resource
  (anonymous function) (index.html:59)
  (anonymous function) (index.html:54)
[Error] Fetch API cannot load foo://test due to access control checks.
  (anonymous function) (index.html:59)
  (anonymous function) (index.html:54)
[Error] Unhandled Promise Rejection: TypeError: Load failed
  (anonymous function) (index.html:59)
```

**Comment by wusyong** [comment]
You can use https but will need to handle CORS.
Tauri itself hosts a dev server when developing but uses custom protocol directly in release build.

**Comment by brandonros** [comment]
![image](https://user-images.githubusercontent.com/8949910/234647647-1e1b2888-76ce-4789-a196-153b3808d5a7.png)

![image](https://user-images.githubusercontent.com/8949910/234647430-10eade55-1559-462d-80ba-346c16755ba8.png)


```
access-control-allow-origin: *
content-security-policy: default-src 'self' 'unsafe-inline' ipc:;
```

if those 2 response headers aren't enough, what else is needed to circumvent:

```
[Warning] [blocked] The page at https://redacted.app/ was not allowed to display insecure content from ipc://test. (redacted.app, line 8)

[Error] Not allowed to request resource

  (anonymous function) (redacted.app:8)
  run (redacted.app:7)
  Module Code (redacted.app:19)
[Error] Fetch API cannot load ipc://test due to access control checks.

  (anonymous function) (redacted.app:8)
  run (redacted.app:7)
  Module Code (redacted.app:19)
[Error] Unhandled Promise Rejection: TypeError: Load failed

  (anonymous function) (redacted.app:8)
```

**Comment by wusyong** [comment]
According to [doc](https://docs.rs/wry/latest/wry/webview/struct.WebViewBuilder.html#warning), you should set ACAO to `ipc://test` if you are on macOS.

**Comment by brandonros** [comment]
![image](https://user-images.githubusercontent.com/8949910/234906290-c4cbc8ff-19b9-4cae-8c2d-cf2c0875c8cc.png)

Same error.

**Comment by wusyong** [comment]
hmmm could you file another issue with steps to reproduce.
Because from tauri side, it can work with dev server with custom protocol enabled.
I'm curious what doesn't work in this case.

Edit: it's `asset://` protocol/scheme in tauri's case
Btw I feel like I should share some context to improve your DX.
Custom protocol should stay in production use. It's weird you need a web server to combine with any IPC IMHO.
If you can do anything locally or in the host, you should do it entirely. In tauri case, that's why we use this.
If everything needs to do with remote, you just provide an URL and follow what web development should do.
