### ISSUE TITLE
file not found for module `web_context` in new release v0.24.2

### ISSUE THREAD

**Issue by zhuyanxi** [tauri-apps/wry#952]
**Describe the bug**
The error message in my console after running cargo check:
```bash
error[E0583]: file not found for module `web_context`
 --> /Users/jackzhu/.cargo/registry/src/github.com-1ecc6299db9ec823/wry-0.24.2/src/webview/wkwebview/mod.rs:8:1
  |
8 | mod web_context;
  | ^^^^^^^^^^^^^^^^
  |
  = help: to create the module `web_context`, create file "/Users/jackzhu/.cargo/registry/src/github.com-1ecc6299db9ec823/wry-0.24.2/src/webview/wkwebview/web_context.rs" or "/Users/jackzhu/.cargo/registry/src/github.com-1ecc6299db9ec823/wry-0.24.2/src/webview/wkwebview/web_context/mod.rs"

For more information about this error, try `rustc --explain E0583`.
error: could not compile `wry` due to previous error
warning: build failed, waiting for other jobs to finish...
```

**Expected behavior**
cargo check pass

**Screenshots**
![image](https://user-images.githubusercontent.com/4001245/236630343-74d976e8-69e6-4669-8e3f-134783e430d3.png)

**Platform and Versions (please complete the following information):**
OS: MacOS Catalina 10.15.7
Rustc: v1.69.0

**Additional context**
Since the changelog of v0.24.2 mentioned that webcontext implementation is removed on MacOS and IOS. I found that this code of line `mod web_context;` is still in file `/src/webview/wkwebview/mod.rs`.
This will lead to the error: `file not found for module `web_context``

**Comment by wusyong** [comment]
yeah sorry about that. I just published 0.24.3 to fix this

**Comment by Levminer** [comment]
@wusyong I get the same error in Tauri 1.3.0, any workaround until a tauri update is released?

**Comment by FabianLars** [comment]
Run `cargo update` in your src-tauri dir. The fix should already be available.
