### ISSUE TITLE
[feat] option to hide android action bar

### ISSUE THREAD

**Issue by jhutchins** [tauri-apps/wry#971]
**Is your feature request related to a problem? Please describe.**

I know there was a recent change to default to having the action bar on Android (https://github.com/tauri-apps/wry/pull/968), but I would like the ability to configure it without needing to add kotlin code or android configs for my project. I assume some people want it and other don't.

**Describe the solution you'd like**
I would like whether to have this or not be a configuration on the window builder. 

**Describe alternatives you've considered**
Obviously we could make it so uses need to create their own base kotlin class where they override the value or apply a themes.xml file, but I think that a config option would be better.

**Would you want to assign yourself to implement this feature?**
- [x] Yes
- [ ] No

**Additional context**
If this feature were in place then there could be an option in the tauri config for whether to have the action bar or not. Probably it would default to on (as is the Android default), but it could be a simple boolean there.

**Comment by amrbashir** [comment]
I am against this tbh, WRY is supposed to be a lower-level library with bare minimum features, and I don't see any major blocker preventing WRY users from applying this change in their project, either through `themes.xml` or by inheriting `WryActivity` class and calling the needed method there.

I should also note that while #968 removes it from WRY, it will still be added by default for Tauri see https://github.com/tauri-apps/tauri/pull/7164

**Comment by jhutchins** [comment]
That works for my use case.
