### ISSUE TITLE
a with _blank target

### ISSUE THREAD

**Issue by ghost** [tauri-apps/wry#982]
**Is your feature request related to a problem? Please describe.**
I have a hyperlink in my app, and I would like it to open in a new browser window.

**Describe the solution you'd like**
Make it so that _blank hyperlinks open in the default browser

**Would you want to assign yourself to implement this feature?**
- [ ] Yes
- [x] No (Sadly I'm too busy since the last few days)

**Comment by FabianLars** [comment]
i personally think this is out of scope of Wry.
In Tauri we solved it by [registering a listener](https://github.com/tauri-apps/tauri/blob/0111b88d753721e788d5c1512a50b4eaee0a10f2/core/tauri/scripts/core.js#L90) on all `a` elements which invokes a tauri command onclick which in turn uses https://docs.rs/open to open the link in the browser.
