### ISSUE TITLE
Disable javascript in webview

### ISSUE THREAD

**Issue by ademcaglin** [tauri-apps/wry#986]
I am exploring the use of Tauri for my desktop application, and I have a specific requirement to disable JavaScript within the webview. However, I couldn't find any built-in option or documentation related to this feature. 

Does anyone  have experience with disabling JavaScript in the Tauri webview or know of any potential solutions?

**Comment by FabianLars** [comment]
Wry does not have a built-in api for that yet but you can use the webview bindings to do it yourself. For example on Windows there's https://docs.rs/webview2-com/latest/webview2_com/Microsoft/Web/WebView2/Win32/struct.ICoreWebView2Settings.html#method.SetIsScriptEnabled
